### ISSUE TITLE
pt-BR sources

### ISSUE THREAD

**Issue by Luiz-bro** [KotatsuApp/kotatsu-parsers#1]
sources suggestions in Brazilian portuguese:
https://mangayabu.top/
http://unionleitor.top/home
https://www.brmangas.com/
https://muitomanga.com/

**Comment by danielcrv** [comment]
https://mangahosted.com/
https://mangalivre.net/

**Comment by davvarrr** [comment]
Close for : Source already requested in another issue, source already pressing or source dead.
