### ISSUE TITLE
MangaParser for specific theme

### ISSUE THREAD

**Issue by OshekharO** [KotatsuApp/kotatsu-parsers#10]
### Describe your suggested feature

Hii can you please make MangaParser for this theme asurascans.com just like you made for madara theme.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/nv95/Kotatsu/issues/new/choose).
- [X] I have updated the app to version **[3.2](https://github.com/nv95/Kotatsu/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by nv95** [comment]
https://themesia.com/mangastream-wordpress-theme/

How I can find other sites that also use this theme?

**Comment by OshekharO** [comment]
Wait i will list some sites which are using this theme

**Comment by OshekharO** [comment]
@nv95 bro just make the template for this theme i will keep on adding sites as soon as I get.

https://www.asurascans.com
https://manhwax.com

Will soon list more sites

**Comment by OshekharO** [comment]
> https://themesia.com/mangastream-wordpress-theme/
> 
> How I can find other sites that also use this theme?

inurl:/az-lists/

**Comment by OshekharO** [comment]
@nv95 

https://github.com/happywillow0/tachiyomi-extensions/tree/83b14a7de6d58bebbbaeaf48d07b47aab98acb99/multisrc/overrides/wpmangastream

https://github.com/happywillow0/tachiyomi-extensions/tree/83b14a7de6d58bebbbaeaf48d07b47aab98acb99/multisrc/overrides/wpmangareader

Bro add these 2 theme like madara sources already given on above link but I will add other sources also.
