### ISSUE TITLE
Isekai Scan Extension 

### ISSUE THREAD

**Issue by ImpenetrableNoble** [KotatsuApp/kotatsu-parsers#100]
### Source information

Isekai Scan

### Steps to reproduce

1. Improve loading as it continuously loads whenever I try to read a manga called Ragnarok crimson.

### Kotatsu version

4.0.2

### Android version

Android 11

### Other details

I tried reading chapter one of the manga story called ragna crimson from the Isekai Scan extension but it wouldn't let me since it kept on loading continuously so I was wondering if the kotatsu team may resolve this issue. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
The 2 sources Isekai Scan work very well.
