### ISSUE TITLE
Cannot access BlogTruyen or read any manga in source BlogTruyen

### ISSUE THREAD

**Issue by nguyenhoanthienit** [KotatsuApp/kotatsu-parsers#1007]
### Source information

BlogTruyen

### Steps to reproduce

1. Go to "Explore"
2. Choose source BlogTruyen
3. Issue appears "Cannot find "section.list-mainpage.listview"
![0d0ced1aad2b0975503a](https://github.com/user-attachments/assets/fc3c34a5-09bd-4656-b66a-eaebdfe98de8)
![0dc186f1d1c0759e2cd1](https://github.com/user-attachments/assets/c3e83580-6058-4493-add8-e60e619818cf)

### Kotatsu version

7.4.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by dragonx943** [comment]
> ### Source information
> BlogTruyen
> 
> ### Steps to reproduce
> 1. Go to "Explore"
> 2. Choose source BlogTruyen
> 3. Issue appears "Cannot find "section.list-mainpage.listview"
>    ![0d0ced1aad2b0975503a](https://private-user-images.githubusercontent.com/23012783/357807679-fc3c34a5-09bd-4656-b66a-eaebdfe98de8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDk5NjIsIm5iZiI6MTcyMzcwOTY2MiwicGF0aCI6Ii8yMzAxMjc4My8zNTc4MDc2NzktZmMzYzM0YTUtMDliZC00NjU2LWI2NmEtZWFlYmRmZTk4ZGU4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA4MTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MjEyMzFmZmYyMTZkYWFlOWY2OTc1YzRkY2ZjYzZjZmI2Mjk0MGJiZWI2ODlkYzU3ZTkzNWE0YWRjOGQ4NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DI5VsYwtr_LtPhoufyeZY-RzYI1VvvZghDtioJkcEZg)
>    ![0dc186f1d1c0759e2cd1](https://private-user-images.githubusercontent.com/23012783/357807692-c3e83580-6058-4493-add8-e60e619818cf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDk5NjIsIm5iZiI6MTcyMzcwOTY2MiwicGF0aCI6Ii8yMzAxMjc4My8zNTc4MDc2OTItYzNlODM1ODAtNjA1OC00NDkzLWFkZDgtZTYwZTYxOTgxOGNmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA4MTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmYTUwOTUwZWNlNTY3MDBhYTUxOTc0OWE3Y2VmZDg0YWNjOTMxMTAyZGFjZTIzMTY1MTQ3ZGExOTIxMTNhM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P90qggujCEWsY7N9y2IYigrPA4St4sdD0yuEJ2-VdpU)
> 
> ### Kotatsu version
> 7.4.2
> 
> ### Android version
> Android 10
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

https://github.com/KotatsuApp/kotatsu-parsers/pull/1003
