### ISSUE TITLE
Source : Hitomi - English, Chinese, Japanese

### ISSUE THREAD

**Issue by Kurumii-ii** [KotatsuApp/kotatsu-parsers#1008]
### Source name

Hitomi

### Source link

https://hitomi.la

### Language

English, Chinese, Japanese

### Other details

It is 18+ source

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by AwkwardPeak7** [comment]
this exists, change to "Various languages" or "all languages" in the source screen

**Comment by Kurumii-ii** [comment]
> this exists, change to "Various languages" or "all languages" in the source screen

Damn bro tysm

**Comment by Kurumii-ii** [comment]
The source has already been added
