### ISSUE TITLE
Source not working

### ISSUE THREAD

**Issue by Kkodak01** [KotatsuApp/kotatsu-parsers#1011]
### Source information

Cerisescans

### Steps to reproduce

1. I open Cerisescans source
2. Its show "an error occured"
3. I click in "try again" and it doesnt work

### Kotatsu version

7.4.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
#718
