### ISSUE TITLE
[Bug] Hitomi.la red thumbnails

### ISSUE THREAD

**Issue by Ero-gamer** [KotatsuApp/kotatsu-parsers#1048]
### Source information

Hitomi

### Kotatsu version

7.5.2

### Android version

Android 9

### Other details

Red thumbnails when accessing Hitomi.la source instead of visible thumbnails, although it's visible only when viewing individual galleries. This happen only (I think?) on Hitomi.la source as Nhentai thumbnails are visible all the time. At first I thought red thumbnails is due to app nsfw settings but that's not the case.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Ero-gamer** [comment]
![Screenshot_2024-09-07-15-29-39-40](https://github.com/user-attachments/assets/d1dd87cd-b951-437c-ae4d-5a921157cdac)

**Comment by Ero-gamer** [comment]
> Test by activating the image proxy in the network settings

Image optimization proxy? Tried both image op services but same results, red thumbnails and the same goes for DNS. I think issue is related to Hitomi.la thumbnails parser but the strange part is that thumbnails show up only when you click on gallery but not when exploring/searching which is annoying to click every gallery just to check on cover thumbnail.

**Comment by dragonx943** [comment]
thats exactly parsers problem :p
![image](https://github.com/user-attachments/assets/232e9ad6-fc88-407d-a2c1-e270d0708a61)

**Comment by Ero-gamer** [comment]
Finally! Problem is fixed on v7.6.5. Thanks to Dev and contributors :)

**Comment by Am483345** [comment]
Hello guys, can anyone help me please.I am facing this red thumbnail  issue in the latest version of kotatsu and I have tried everything but nothing is working. Is someone also facing it.If yes? then how to solve it.

**Comment by Ero-gamer** [comment]
> Hello guys, can anyone help me please.I am facing this red thumbnail issue in the latest version of kotatsu and I have tried everything but nothing is working. Is someone also facing it.If yes? then how to solve it.

Currently issue is related to new Hitomi.la thumbnails parser/logic change in the latest version and is not solvable until a patch related to this issue is released in future version. For now, you have to click every red thumbnail gallery to view cover then hit back to search and repeat process. BTW there is another huge problem other than this tho, most of downloaded/parsed gallery images on Hitomi.la source are now PNG files rather than the usual WEBP files which are 5 times or more bigger in size and that's a big problem, at least for me, since this is the only reason why I use Hitomi.la. I did few tests run and I find it always fetch PNG files instead of compressed WEBP files (almost no visible difference in image quality between WEBP and PNG) and yes, Komikku/Mihon Hitomi.la extension still work perfectly as usual fetching/downloading WEBP images and even AVIF images which have tiny sizes.

Boss @dragonx943 can you possibly fix this?
