### ISSUE TITLE
[Source request] Manhwaid

### ISSUE THREAD

**Issue by alpqm** [KotatsuApp/kotatsu-parsers#105]
Manhwaid

### Source link

https://manhwaid.info

### Language

Indonesian 

### Other details

Nsfw

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by alpqm** [comment]
Please add

**Comment by alpqm** [comment]
when will this be added

**Comment by ztimms73** [comment]
No ETA

**Comment by alpqm** [comment]
> No ETA

🙂

**Comment by alpqm** [comment]
Close web Off
