### ISSUE TITLE
Cmanga source request 

### ISSUE THREAD

**Issue by Karuto2k7** [KotatsuApp/kotatsu-parsers#1069]
### Source name

Cmanga

### Source link

https://cmanga03.com/

### Language

Vietnamese

### Other details
Nsfw = yes
- Nedding save login request in this extension
Q: can you create to push plus 1 when readed (this web have an ranking to read some chapter like if you read more chapter you can read an locked chapter) 
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by dragonx943** [comment]
@Koitharu now i have:

- https://cmanga03.com/api/user_album_suggest
- https://cmanga03.com/api/home_album_list
- https://cmanga03.com/api/home_album_top?type=pin

after 1-2m read the source of home site, hmmmmm 🐧

**Comment by dragonx943** [comment]
> ### Source name
> Cmanga
> 
> ### Source link
> https://cmanga03.com/
> 
> ### Language
> Vietnamese
> 
> ### Other details
> Nsfw = yes
> 
> * Nedding save login request in this extension
>   Q: can you create to push plus 1 when readed (this web have an ranking to read some chapter like if you read more chapter you can read an locked chapter)
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have checked that the source does not already exist on the app.
> * [x]  I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

nếu tính theo rank và phải đọc 1 chap thì mới đọc được chap tiếp theo (bị khóa chap) thì chưa chắc đã có source này trong kotatsu :p

**Comment by dragonx943** [comment]
Chưa có ý định làm + Chưa nắm bắt được hết trang web / parsers

**Comment by Karuto2k7** [comment]
> Chưa có ý định làm + Chưa nắm bắt được hết trang web / parsers

Bạn có thể tham khảo code ở vbook của bạn kur21 nhé https://github.com/kur21/vbook-ext/tree/main/cmanga

**Comment by dragonx943** [comment]
> > Chưa có ý định làm + Chưa nắm bắt được hết trang web / parsers
> 
> Bạn có thể tham khảo code ở vbook của bạn kur21 nhé https://github.com/kur21/vbook-ext/tree/main/cmanga Bên vbook làm dc mấy tháng r á @dragonx943

vấn đề là ở phần login để đọc, tôi chưa nắm rõ parser này nhiều nên vẫn còn hạn chế về mặt code, nó công khai như vcomic hay các trang khác thì ít ra tôi vẫn làm được

**Comment by Karuto2k7** [comment]
> > > Chưa có ý định làm + Chưa nắm bắt được hết trang web / parsers
> > 
> > 
> > Bạn có thể tham khảo code ở vbook của bạn kur21 nhé https://github.com/kur21/vbook-ext/tree/main/cmanga Bên vbook làm dc mấy tháng r á @dragonx943
> 
> vấn đề là ở phần login để đọc, tôi chưa nắm rõ parser này nhiều nên vẫn còn hạn chế về mặt code, nó công khai như vcomic hay các trang khác thì ít ra tôi vẫn làm được

Phần đấy thì miễn là kotatsu lưu cookie thì vẫn dùng được nhé (mà phần này cx không khác gì đâu) 
Bro có thể lấy mấy bộ mở để làm https://cmangaop.com/album/sam-yi-tai-sinh-50568
Bên vbook theo như mình thấy thì mình chỉ cần đăng nhập ở webview r sau này nó tự mở á) cái này thì cmanga yêu cầu cày tu vi để mở (cái này làm dc bro đọc truyện nhiều ở bên này với lại lưu nhiều bộ hành ngày là nó mở

**Comment by dragonx943** [comment]
> > > > Chưa có ý định làm + Chưa nắm bắt được hết trang web / parsers
> > > 
> > > 
> > > Bạn có thể tham khảo code ở vbook của bạn kur21 nhé https://github.com/kur21/vbook-ext/tree/main/cmanga Bên vbook làm dc mấy tháng r á @dragonx943
> > 
> > 
> > vấn đề là ở phần login để đọc, tôi chưa nắm rõ parser này nhiều nên vẫn còn hạn chế về mặt code, nó công khai như vcomic hay các trang khác thì ít ra tôi vẫn làm được
> 
> Phần đấy thì miễn là kotatsu lưu cookie thì vẫn dùng được nhé (mà phần này cx không khác gì đâu) Bro có thể lấy mấy bộ mở để làm https://cmangaop.com/album/sam-yi-tai-sinh-50568 Bên vbook theo như mình thấy thì mình chỉ cần đăng nhập ở webview r sau này nó tự mở á) cái này thì cmanga yêu cầu cày tu vi để mở (cái này làm dc bro đọc truyện nhiều ở bên này với lại lưu nhiều bộ hành ngày là nó mở

kotatsu có lưu cookie, nếu là @Koitharu thì có thể làm được nguồn này nhưng với tôi thì tôi đoán là nope, vì tôi chưa từng làm nguồn nào có phần đăng nhập / yêu cầu tài khoản cao cấp để đọc (dù đã được hướng dẫn qua về cách khai thác nhưng tôi vẫn chưa hiểu nhiều về nó)

**Comment by VietAnh14** [comment]
Mình có thử implement nhưng ko có account có coin để test khúc unlock chapter, khi nào được merge and release rồi thì bạn có thể test thử xem sao

**Comment by dragonx943** [comment]
> Mình có thử implement nhưng ko có account có coin để test khúc unlock chapter, khi nào được merge and release rồi thì bạn có thể test thử xem sao

@VietAnh14 bác có Discord k DM tôi với: deleted_user_3a4e21e3f9ab

**Comment by VietAnh14** [comment]
@dragonx943 DM làm gì bạn, Discord lâu rồi mình ko dùng, quên account rồi, giờ kiếm lại hơi mệt =)

**Comment by dragonx943** [comment]
> @dragonx943 DM làm gì bạn, Discord lâu rồi mình ko dùng, quên account rồi, giờ kiếm lại hơi mệt =)

tạo mới đi:))
