### ISSUE TITLE
[Source request] Komikcast

### ISSUE THREAD

**Issue by alpqm** [KotatsuApp/kotatsu-parsers#107]
### Source name

komikcast

### Source link

https://komikcast.site/

### Language

Indonesian 

### Other details

No Nsfw 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by alpqm** [comment]
Please add 🙏

**Comment by ztimms73** [comment]
Duplicate #79
