### ISSUE TITLE
[Source request] Mangasusu

### ISSUE THREAD

**Issue by ghost** [KotatsuApp/kotatsu-parsers#108]
### Source name

Mangasusu

### Source link

https://194.233.87.209/

### Language

Indonesian 

### Other details

Nsfw

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by alpqm** [comment]
http://mangasusu.cc

**Comment by alpqm** [comment]
> http://mangasusu.cc

https://mangasusu.co.in/

**Comment by Start38** [comment]
> http://mangasusu.cc

This url doesn't work anymore

**Comment by Start38** [comment]
> > http://mangasusu.cc
> 
> https://mangasusu.co.in/

Replace with this URL

**Comment by OshekharO** [comment]
Resolved #147
