### ISSUE TITLE
Better way to scrape Mangaworld

### ISSUE THREAD

**Issue by DomHeadroom** [KotatsuApp/kotatsu-parsers#1106]
### Describe your suggested feature

All the data to generate the manga page URLs is available in a json inside a script tag at the end of the manga page on Mangaworld, so you don't need to manually scrape each manga page from the site one by one.

I created this concept in Python to demonstrate how it works.

```python
from bs4 import BeautifulSoup
import requests
import orjson

url = "https://www.mangaworld.ac/manga/1692/jojo-s-bizarre-adventure-part-7-steel-ball-run-official-colored"

response = requests.get(url)
if response.status_code == 200:
    html_content = response.text
else:
    print(f"Failed to retrieve the page. Status code: {response.status_code}")
    exit()

soup = BeautifulSoup(html_content, 'html.parser')

script_tag = soup.find('script', string=lambda t: t and '$MC=(window.$MC||[]).concat(' in t)

if script_tag:
    script_content = script_tag.string

    json_start = script_content.find('concat(') + len('concat(')
    json_end = script_content.rfind(');')
    json_string = script_content[json_start:json_end].strip()

    json_string = json_string.lstrip(',')

    try:
        json_data = orjson.loads(json_string)
        data = json_data['o']['w'][3][2]
        manga = json_data['o']['w'][0][2]["manga"]
        volumes = data['pages']['volumes'][0]
        chapter = volumes['chapters'][2]
        volume = volumes["volume"]
        page = chapter["pages"][1]
        
        print(f"{data['CDN_URL']}/chapters/{manga['slugFolder']}-{manga['_id']}/{volume['slugFolder']}-{volume['id']}/{chapter['slugFolder']}-{chapter['id']}/{page}")
        
    except orjson.JSONDecodeError as e:
        print(f"Error parsing JSON: {e}")
```  
This only generates the data for a manga page, but the JSON also contains other unused data like extraTitles and genres. If you want to extract those with my Python code, you just need to access manga['genres'] or manga['extraTitles']

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by dragonx943** [comment]
> ### Describe your suggested feature
> All the data to generate the manga page URLs is available in a json inside a script tag at the end of the manga page on Mangaworld, so you don't need to manually scrape each manga page from the site one by one.
> 
> I created this concept in Python to demonstrate how it works.
> 
> ```python
> from bs4 import BeautifulSoup
> import requests
> import orjson
> 
> url = "https://www.mangaworld.ac/manga/1692/jojo-s-bizarre-adventure-part-7-steel-ball-run-official-colored"
> 
> response = requests.get(url)
> if response.status_code == 200:
>     html_content = response.text
> else:
>     print(f"Failed to retrieve the page. Status code: {response.status_code}")
>     exit()
> 
> soup = BeautifulSoup(html_content, 'html.parser')
> 
> script_tag = soup.find('script', string=lambda t: t and '$MC=(window.$MC||[]).concat(' in t)
> 
> if script_tag:
>     script_content = script_tag.string
> 
>     json_start = script_content.find('concat(') + len('concat(')
>     json_end = script_content.rfind(');')
>     json_string = script_content[json_start:json_end].strip()
> 
>     json_string = json_string.lstrip(',')
> 
>     try:
>         json_data = orjson.loads(json_string)
>         data = json_data['o']['w'][3][2]
>         manga = json_data['o']['w'][0][2]["manga"]
>         volumes = data['pages']['volumes'][0]
>         chapter = volumes['chapters'][2]
>         volume = volumes["volume"]
>         page = chapter["pages"][1]
>         
>         print(f"{data['CDN_URL']}/chapters/{manga['slugFolder']}-{manga['_id']}/{volume['slugFolder']}-{volume['id']}/{chapter['slugFolder']}-{chapter['id']}/{page}")
>         
>     except orjson.JSONDecodeError as e:
>         print(f"Error parsing JSON: {e}")
> ```
> 
> This only generates the data for a manga page, but the JSON also contains other unused data like extraTitles and genres. If you want to extract those with my Python code, you just need to access manga['genres'] or manga['extraTitles']
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

too roundabout, i thought this site has API :p
