### ISSUE TITLE
New source doctruyen3q

### ISSUE THREAD

**Issue by azsasr** [KotatsuApp/kotatsu-parsers#1108]
### Source name

doctruyen3q

### Source link

https://doctruyen3qto.pro/

### Language

Vietnamese

### Other details

This source fastest update chapters in Vietnamse. I hope dev team can added this source to Kotatsu. Thanks you for reading

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by dragonx943** [comment]
> ### Source name
> doctruyen3q
> 
> ### Source link
> https://doctruyen3qto.pro/
> 
> ### Language
> Vietnamese
> 
> ### Other details
> This source fastest update chapters in Vietnamse. I hope dev team can added this source to Kotatsu. Thanks you for reading
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have checked that the source does not already exist on the app.
> * [x]  I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

:p khá giống nettruyen

**Comment by azsasr** [comment]
> > ### Source name
> > doctruyen3q
> > ### Source link
> > https://doctruyen3qto.pro/
> > ### Language
> > Vietnamese
> > ### Other details
> > This source fastest update chapters in Vietnamse. I hope dev team can added this source to Kotatsu. Thanks you for reading
> > ### Acknowledgements
> > 
> > * [x]   I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> > * [x]   I have checked that the source does not already exist on the app.
> > * [x]   I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.
> 
> :p khá giống nettruyen

Đúng rồi bạn, web này update nhanh lắm như nettruyen hồi xưa, bạn thêm vào được source thì hay quá.

**Comment by dragonx943** [comment]
> > > ### Source name
> > > doctruyen3q
> > > ### Source link
> > > https://doctruyen3qto.pro/
> > > ### Language
> > > Vietnamese
> > > ### Other details
> > > This source fastest update chapters in Vietnamse. I hope dev team can added this source to Kotatsu. Thanks you for reading
> > > ### Acknowledgements
> > > 
> > > * [x]    I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> > > * [x]    I have checked that the source does not already exist on the app.
> > > * [x]    I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.
> > 
> > 
> > :p khá giống nettruyen
> 
> Đúng rồi bạn, web này update nhanh lắm như nettruyen hồi xưa, bạn thêm vào được source thì hay quá.

https://github.com/KotatsuApp/kotatsu-parsers/pull/1109
tôi lười, kêu dev khác làm đi :p

**Comment by azsasr** [comment]
Cảm ơn bác @dragonx943 nhiều
