### ISSUE TITLE
Cannot load source CuuTruyen

### ISSUE THREAD

**Issue by nguyenhoanthienit** [KotatsuApp/kotatsu-parsers#1114]
### Source information

CuuTruyen

### Steps to reproduce

1. Go to explore
2. Select "NetTruyen" in mganga sources
3. Page not display anything
![image](https://github.com/user-attachments/assets/acd0c2bb-51ed-4c5b-94fb-4048fedf6266)

### Kotatsu version

7.6

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by dragonx943** [comment]
> ### Source information
> CuuTruyen
> 
> ### Steps to reproduce
> 1. Go to explore
> 2. Select "NetTruyen" in mganga sources
> 3. Page not display anything
>    ![image](https://private-user-images.githubusercontent.com/23012783/371871772-acd0c2bb-51ed-4c5b-94fb-4048fedf6266.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2Mjg1NTgsIm5iZiI6MTcyNzYyODI1OCwicGF0aCI6Ii8yMzAxMjc4My8zNzE4NzE3NzItYWNkMGMyYmItNTFlZC00YzViLTk0ZmItNDA0OGZlZGY2MjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDE2NDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMDJmMjRhZmJiNTRjNmMxMjQ1YTY1YTBjMmE2OTNjZmRiNDViNjdjY2NhZjFmOTYzMzcwM2Q2MTI1NGUyZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mp8ZP0YtMxa3sbS8pAKqCJPe8bZ64wwkQ--Snyqqibw)
> 
> ### Kotatsu version
> 7.6
> 
> ### Android version
> Android 10
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

là do mạng của bạn đang chặn nguồn (giống VNPT), dùng 1.1.1.1 là đọc được :p

**Comment by nguyenhoanthienit** [comment]
> > ### Source information
> > CuuTruyen
> > ### Steps to reproduce
> > 
> > 1. Go to explore
> > 2. Select "NetTruyen" in mganga sources
> > 3. Page not display anything
> >    ![image](https://private-user-images.githubusercontent.com/23012783/371871772-acd0c2bb-51ed-4c5b-94fb-4048fedf6266.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2Mjg1NTgsIm5iZiI6MTcyNzYyODI1OCwicGF0aCI6Ii8yMzAxMjc4My8zNzE4NzE3NzItYWNkMGMyYmItNTFlZC00YzViLTk0ZmItNDA0OGZlZGY2MjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDE2NDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMDJmMjRhZmJiNTRjNmMxMjQ1YTY1YTBjMmE2OTNjZmRiNDViNjdjY2NhZjFmOTYzMzcwM2Q2MTI1NGUyZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mp8ZP0YtMxa3sbS8pAKqCJPe8bZ64wwkQ--Snyqqibw)
> > 
> > ### Kotatsu version
> > 7.6
> > ### Android version
> > Android 10
> > ### Other details
> > _No response_
> > ### Acknowledgements
> > 
> > * [x]   I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> 
> là do mạng của bạn đang chặn nguồn (giống VNPT), dùng 1.1.1.1 là đọc được :p

Mình cảm ơn nhiều nhé. Mình resolve ok rồi

**Comment by nguyenhoanthienit** [comment]
Resolved with using any VPN app.

**Comment by dragonx943** [comment]
> Resolved with using any VPN app.

@Koitharu need to remove Tags with this source (like i said before)
