### ISSUE TITLE
DocTruyen3Q Nothing found

### ISSUE THREAD

**Issue by azsasr** [KotatsuApp/kotatsu-parsers#1115]
### Source information

DocTruyen3Q

### Steps to reproduce

Thank devs for fast add my new source request in https://github.com/KotatsuApp/kotatsu-parsers/issues/1108, but it have some problem.
1. Open source Doctruyen3q
2. See error.
![image](https://github.com/user-attachments/assets/6b61bcd7-77db-4f46-85de-08e900e6d0a3)

### Kotatsu version

7.6.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by dragonx943** [comment]
> ### Source information
> DocTruyen3Q
> 
> ### Steps to reproduce
> Thank devs for fast add my new source request in #1108, but it have some problem.
> 
> 1. Open source Doctruyen3q
> 2. See error.
>    ![image](https://private-user-images.githubusercontent.com/162137914/371873762-6b61bcd7-77db-4f46-85de-08e900e6d0a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MzA1NzksIm5iZiI6MTcyNzYzMDI3OSwicGF0aCI6Ii8xNjIxMzc5MTQvMzcxODczNzYyLTZiNjFiY2Q3LTc3ZGItNGY0Ni04NWRlLTA4ZTkwMGU2ZDBhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxNzE3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTBkNTJiZTM4YjVlN2EyMmE5MmFiNDEwNjg1NzZjN2I2ZjExYmUwNGViMzUxMzI2Y2Y5OWIwMzZjYWZmNTc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EQvDJsMk1sRMUryNvJECNN0csmnUapKDegBqtv6_ua8)
> 
> ### Kotatsu version
> 7.6.1
> 
> ### Android version
> Android 13
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

my bad, because its look like clone from TopTruyenViet but i think i was wrong, maybe its structure has been changed so its not the same as other websites like NetTruyen, TopTruyenViet, so i will fix it later :p

**Comment by azsasr** [comment]
> > ### Source information
> > DocTruyen3Q
> > ### Steps to reproduce
> > Thank devs for fast add my new source request in #1108, but it have some problem.
> > 
> > 1. Open source Doctruyen3q
> > 2. See error.
> >    ![image](https://private-user-images.githubusercontent.com/162137914/371873762-6b61bcd7-77db-4f46-85de-08e900e6d0a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MzA1NzksIm5iZiI6MTcyNzYzMDI3OSwicGF0aCI6Ii8xNjIxMzc5MTQvMzcxODczNzYyLTZiNjFiY2Q3LTc3ZGItNGY0Ni04NWRlLTA4ZTkwMGU2ZDBhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxNzE3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTBkNTJiZTM4YjVlN2EyMmE5MmFiNDEwNjg1NzZjN2I2ZjExYmUwNGViMzUxMzI2Y2Y5OWIwMzZjYWZmNTc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EQvDJsMk1sRMUryNvJECNN0csmnUapKDegBqtv6_ua8)
> > 
> > ### Kotatsu version
> > 7.6.1
> > ### Android version
> > Android 13
> > ### Other details
> > _No response_
> > ### Acknowledgements
> > 
> > * [x]   I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> 
> my bad, because its look like clone from TopTruyenViet but i think i was wrong, maybe its structure has been changed so its not the same as other websites like NetTruyen, TopTruyenViet, so i will fix it later :p

Thank you so much

**Comment by dragonx943** [comment]
@davvarrr DocTruyen3Q and TopTruyen.pro have the same structure but not the same structure with wpcomicsparser or nettruyen so they cant access and crawl data for reading so it shows error when i try to read from these sources

**Comment by dragonx943** [comment]
> @dragonx943 bác ơi thấy đã có commit hỗ trợ toptruyen với dọctruyen3q rồi mà cài bản mới vẫn chưa thấy source đó đâu nhỉ?

nguồn chưa fix nên vẫn chưa đọc được, còn tìm ở đâu thì vào cài đặt -> nguồn đọc -> tiếng Việt và tự thêm nó vào là có

**Comment by dragonx943** [comment]
> ### Source information
> DocTruyen3Q
> 
> ### Steps to reproduce
> Thank devs for fast add my new source request in #1108, but it have some problem.
> 
> 1. Open source Doctruyen3q
> 2. See error.
>    ![image](https://private-user-images.githubusercontent.com/162137914/371873762-6b61bcd7-77db-4f46-85de-08e900e6d0a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODY1NDksIm5iZiI6MTcyOTY4NjI0OSwicGF0aCI6Ii8xNjIxMzc5MTQvMzcxODczNzYyLTZiNjFiY2Q3LTc3ZGItNGY0Ni04NWRlLTA4ZTkwMGU2ZDBhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxMjI0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTllMzQwZDJlNzFhNzliMzRkNTA4MzY4ODhmZmIyODE1ZDk5YzI3MTI3ZDVlNjMyMTZlMDgyMWFkZTA3OTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PonAGYbjBG6phFR9tqQSQESNAmFZC-rnOuit8SE0S4E)
> 
> ### Kotatsu version
> 7.6.1
> 
> ### Android version
> Android 13
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

tuần này đang bận chạy deadline, bác chịu khó chờ thêm 1-2 tuần nữa là có :p
![image](https://github.com/user-attachments/assets/23dda4e4-c3f1-4f28-95e4-36ba42aa090c)

**Comment by dragonx943** [comment]
> ### Source information
> DocTruyen3Q
> 
> ### Steps to reproduce
> Thank devs for fast add my new source request in #1108, but it have some problem.
> 
> 1. Open source Doctruyen3q
> 2. See error.
>    ![image](https://private-user-images.githubusercontent.com/162137914/371873762-6b61bcd7-77db-4f46-85de-08e900e6d0a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODYzNjksIm5iZiI6MTcyOTc4NjA2OSwicGF0aCI6Ii8xNjIxMzc5MTQvMzcxODczNzYyLTZiNjFiY2Q3LTc3ZGItNGY0Ni04NWRlLTA4ZTkwMGU2ZDBhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxNjA3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmE0MmQ2ZjEwNmFiNWVjMzRlMTBlNjJkNWVjOTZkYzdhZTMwNzBkOGExMzRkOTIyNmY1ZDY0ODFjZmIyYTRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5rbsOxnU0NKJiKXxoAW2Ir_qiB_XWqrxEh8P_Dhwim0)
> 
> ### Kotatsu version
> 7.6.1
> 
> ### Android version
> Android 13
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

Done https://github.com/KotatsuApp/kotatsu-parsers/pull/1187
