### ISSUE TITLE
[Source request] Manga18

### ISSUE THREAD

**Issue by Drangonfly30** [KotatsuApp/kotatsu-parsers#113]
### Source name

Manga18.club

### Source link

https://manga18.club/

### Language

English + others

### Other details

Thanks for adding manhwa18.net. But it has slow updates. So I'm giving another source. Please add this too if possible. Also thanks in advance.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by AntarCrypto** [comment]
please add it it's better than manhwa18

**Comment by AntarCrypto** [comment]
is there any other way to use this website?I really want this website to be added so that I can download manga.
