### ISSUE TITLE
BumCheo

### ISSUE THREAD

**Issue by nguyenhoanthienit** [KotatsuApp/kotatsu-parsers#1135]
### Source name

BumCheo

### Source link

https://bumcheo.vn/

### Language

Vietnamese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by dragonx943** [comment]
> ### Source name
> BumCheo
> 
> ### Source link
> https://bumcheo.vn/
> 
> ### Language
> Vietnamese
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have checked that the source does not already exist on the app.
> * [x]  I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

nope, nó còn chẳng phải là nguồn đọc nữa mà nó thành mạng xã hội vi en luôn cmnr 💀
