### ISSUE TITLE
Connect not found or removed

### ISSUE THREAD

**Issue by HoNamDuong** [KotatsuApp/kotatsu-parsers#1138]
## Source information

LxManga

### Steps to reproduce

`return doc.select("div.text-center img.lazy").map { img ->`
to
`return doc.select("div.text-center img.lazy-image").map { img ->`

`override val configKeyDomain = ConfigKey.Domain("lxmanga.click")`
to
`override val configKeyDomain = ConfigKey.Domain("lxmanga.ink")`

### Kotatsu version

Latest version

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by dragonx943** [comment]
> ## Source information
> LxManga
> 
> ### Steps to reproduce
> `return doc.select("div.text-center img.lazy").map { img ->` to `return doc.select("div.text-center img.lazy-image").map { img ->`
> 
> `override val configKeyDomain = ConfigKey.Domain("lxmanga.click")` to `override val configKeyDomain = ConfigKey.Domain("lxmanga.ink")`
> 
> ### Kotatsu version
> Latest version
> 
> ### Android version
> _No response_
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

https://github.com/KotatsuApp/kotatsu-parsers/pull/1146
