### ISSUE TITLE
An error occurred TuMangaOnline

### ISSUE THREAD

**Issue by INFZeroT** [KotatsuApp/kotatsu-parsers#1162]
### Source information

TuMangaOnline

### Steps to reproduce

1.Opens the source
2.Opens any manga
3.Sends error 530
![9dcf7e76-83b8-4da9-ac21-09847a23fe7f](https://github.com/user-attachments/assets/1289af14-0c8a-4ffc-b640-a52e6c34d5b6)
![dfa2cf3f-9e50-473b-a745-7d2ca707aa7a](https://github.com/user-attachments/assets/b1532a6b-7cd0-4eac-9d80-2ec9fb700218)

### Kotatsu version

7.6.4

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by dragonx943** [comment]
> ### Source information
> TuMangaOnline
> 
> ### Steps to reproduce
> 1.Opens the source 2.Opens any manga 3.Sends error 530 ![9dcf7e76-83b8-4da9-ac21-09847a23fe7f](https://private-user-images.githubusercontent.com/107084505/376047988-1289af14-0c8a-4ffc-b640-a52e6c34d5b6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MjYyNDcsIm5iZiI6MTcyODkyNTk0NywicGF0aCI6Ii8xMDcwODQ1MDUvMzc2MDQ3OTg4LTEyODlhZjE0LTBjOGEtNGZmYy1iNjQwLWE1MmU2YzM0ZDViNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxNzEyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzY4MTNjYzVlYzVkMmZlMjExZmFlZWZmZGMwMjM1ZmU5MDI2N2RmZWQ0NTBlZGM4ZTM2MzM2NTM0NWNkOTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wh1RecpBpNYzf3_6z__QuIs_09m9V_g01pDAade7Yj8) ![dfa2cf3f-9e50-473b-a745-7d2ca707aa7a](https://private-user-images.githubusercontent.com/107084505/376047992-b1532a6b-7cd0-4eac-9d80-2ec9fb700218.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MjYyNDcsIm5iZiI6MTcyODkyNTk0NywicGF0aCI6Ii8xMDcwODQ1MDUvMzc2MDQ3OTkyLWIxNTMyYTZiLTdjZDAtNGVhYy05ZDgwLTJlYzlmYjcwMDIxOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxNzEyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWZiNzQ5MTk1ZTJiNTc2YTgxNDVkMjUyMDc2NWNlOWMyZDBmMWY5NjZiNzMyY2Y2ODlhNjg1ZmFlNzdiOTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.o97PtOPb13kf_6NofG2ktYEsqo88QA3bNl9nwt5Ig54)
> 
> ### Kotatsu version
> 7.6.4
> 
> ### Android version
> 12
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

still good, maybe need to check ur network!

![image](https://github.com/user-attachments/assets/9c67a8db-262c-49ab-9efc-0599ed3abf33)
![image](https://github.com/user-attachments/assets/dfd09872-4436-4dcb-9355-79a20d98d07a)

**Comment by INFZeroT** [comment]
Changing the domain to zonatmo.com, Fixed the Problem
