### ISSUE TITLE
The Manhwa18 site isn't loading.

### ISSUE THREAD

**Issue by RiZEX8** [KotatsuApp/kotatsu-parsers#117]
### Source information

Manhwa18.net

### Steps to reproduce

other sites r loading but this one isn't...

### Kotatsu version

4.0.4

### Android version

12

### Other details

![Screenshot_2022-11-26-06-34-59-35_a5af3585a93e2016f6667aaf7e1e2f32](https://user-images.githubusercontent.com/119087027/204066880-4413cbfe-c4ac-4ebf-83bb-83884535c9e7.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by VietAnh14** [comment]
Hi, is this happen to all manga or only this manga. Can you try to enable dns over https in Settings > Content and try again?
![IMG_20221126_112955.jpg](https://user-images.githubusercontent.com/37103340/204072289-9df3a420-8856-44b2-a055-53b3d5b8ac61.jpg)

**Comment by RiZEX8** [comment]
> Hi, is this happen to all manga or only this manga. Can you try to enable dns over https in Settings > Content and try again?
> ![IMG_20221126_112955.jpg](https://user-images.githubusercontent.com/37103340/204072289-9df3a420-8856-44b2-a055-53b3d5b8ac61.jpg)

hmm... its working now... ❤️

**Comment by davvarrr** [comment]
Manhwa18 working need to close issue
