### ISSUE TITLE
[ Source Request ] XXManhwa

### ISSUE THREAD

**Issue by tuanbmt4152** [KotatsuApp/kotatsu-parsers#1171]
### Source name

XXManhwa

### Source link

https://xxmanhwas.org/

### Language

Vietnamese-Vi

### Other details

Thanks for reading the article

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by dragonx943** [comment]
> ### Source name
> XXManhwa
> 
> ### Source link
> https://xxmanhwas.org/
> 
> ### Language
> Vietnamese-Vi
> 
> ### Other details
> Thanks for reading the article
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have checked that the source does not already exist on the app.
> * [x]  I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

đi khám mắt là vừa tầm r bro 🐧 
![image](https://github.com/user-attachments/assets/d8cb3d1c-88ec-4c03-866d-99d42ffb819a)

**Comment by tuanbmt4152** [comment]
hahaha

> > ### Source name
> > XXManhwa
> > ### Source link
> > https://xxmanhwas.org/
> > ### Language
> > Vietnamese-Vi
> > ### Other details
> > Thanks for reading the article
> > ### Acknowledgements
> > 
> > * [x]   I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> > * [x]   I have checked that the source does not already exist on the app.
> > * [x]   I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.
> 
> @tuanbmt4152 đi khám mắt là vừa tầm r bro 🐧
> 
> ![image](https://private-user-images.githubusercontent.com/131387159/377515654-d8cb3d1c-88ec-4c03-866d-99d42ffb819a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxODA5MDgsIm5iZiI6MTcyOTE4MDYwOCwicGF0aCI6Ii8xMzEzODcxNTkvMzc3NTE1NjU0LWQ4Y2IzZDFjLTg4ZWMtNGMwMy04NjZkLTk5ZDQyZmZiODE5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QxNTU2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNGMxM2YxNGNjNjllNTk4YjIyYmIwZTlmZDJiN2FmY2ZjMjRiMmZlOGE4ZGYxM2MzYTRkMTMwNzBhNTdiN2QzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tsg7kuwB1JpmciwzepEivAHGj0RgoDWebKiCU2h7IOI)

haha =))

**Comment by dragonx943** [comment]
> ### Source name
> XXManhwa
> 
> ### Source link
> https://xxmanhwas.org/
> 
> ### Language
> Vietnamese-Vi
> 
> ### Other details
> Thanks for reading the article
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have checked that the source does not already exist on the app.
> * [x]  I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

@tuanbmt4152 làm sao để mở khóa các chương bị private? pay to read?

**Comment by tuanbmt4152** [comment]
> > ### Source name
> > XXManhwa
> > ### Source link
> > https://xxmanhwas.org/
> > ### Language
> > Vietnamese-Vi
> > ### Other details
> > Thanks for reading the article
> > ### Acknowledgements
> > 
> > * [x]   I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> > * [x]   I have checked that the source does not already exist on the app.
> > * [x]   I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.
> 
> @tuanbmt4152 làm sao để mở khóa các chương bị private? pay to read?
chuyển tiền cho khứa ad trang đó và khứa đó mở khóa tài khoản  lên Vip , sơ cấp , trung cấp , cao cấp , riêng tư =))
tùy mức giá

**Comment by dragonx943** [comment]
> > > ### Source name
> > > XXManhwa
> > > ### Source link
> > > https://xxmanhwas.org/
> > > ### Language
> > > Vietnamese-Vi
> > > ### Other details
> > > Thanks for reading the article
> > > ### Acknowledgements
> > > 
> > > * [x]    I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> > > * [x]    I have checked that the source does not already exist on the app.
> > > * [x]    I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.
> > 
> > 
> > @tuanbmt4152 làm sao để mở khóa các chương bị private? pay to read?
> > chuyển tiền cho khứa ad trang đó và khứa đó mở khóa tài khoản  lên Vip , sơ cấp , trung cấp , cao cấp , riêng tư =))
> > tùy mức giá

vậy là tôi k có trình để làm nguồn này r, kêu người khác đi 🐧

**Comment by dragonx943** [comment]
Đang tiến hành...
