### ISSUE TITLE
[ Source Request ] Sayhentai

### ISSUE THREAD

**Issue by tuanbmt4152** [KotatsuApp/kotatsu-parsers#1172]
### Source name

Sayhentai

### Source link

https://sayhentai.one/

### Language

Vietnamese-Vi

### Other details

Thanks for reading the article

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by dragonx943** [comment]
> ### Source name
> Sayhentai
> 
> ### Source link
> https://sayhentai.one/
> 
> ### Language
> Vietnamese-Vi
> 
> ### Other details
> Thanks for reading the article
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have checked that the source does not already exist on the app.
> * [x]  I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

lười x3.14 :p

**Comment by dragonx943** [comment]
> ### Source name
> Sayhentai
> 
> ### Source link
> https://sayhentai.one/
> 
> ### Language
> Vietnamese-Vi
> 
> ### Other details
> Thanks for reading the article
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have checked that the source does not already exist on the app.
> * [x]  I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

đoán là a bạn này có vấn đề về đôi mắt 🐧 
![image](https://github.com/user-attachments/assets/92d5e6f7-31b5-464f-bc9f-9cbee7011e87)

**Comment by tuanbmt4152** [comment]
> > ### Source name
> > Sayhentai
> > ### Source link
> > https://sayhentai.one/
> > ### Language
> > Vietnamese-Vi
> > ### Other details
> > Thanks for reading the article
> > ### Acknowledgements
> > 
> > * [x]   I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> > * [x]   I have checked that the source does not already exist on the app.
> > * [x]   I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.
> 
> đoán là a bạn này có vấn đề về đôi mắt 🐧 ![image](https://private-user-images.githubusercontent.com/131387159/377095093-92d5e6f7-31b5-464f-bc9f-9cbee7011e87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTM1ODksIm5iZiI6MTcyOTA5MzI4OSwicGF0aCI6Ii8xMzEzODcxNTkvMzc3MDk1MDkzLTkyZDVlNmY3LTMxYjUtNDY0Zi1iYzlmLTljYmVlNzAxMWU4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxNTQxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzA5NTJkZjA4ZDM1NjNmYjQ3Mjc3NTBmOGJmZmNlNDVjNWJiMWM5NjQ0NzkzNTc4NTIxZTY4NjYzMTVhOTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.miKak2VW3M2zDAWkqzLYzpmUyctesfgelg7NF36FrL8)

sao trong máy tôi trong mục tiếng việt và không thấy nguồn này nhỉ , dù đã cập nhật

**Comment by dragonx943** [comment]
> > > ### Source name
> > > Sayhentai
> > > ### Source link
> > > https://sayhentai.one/
> > > ### Language
> > > Vietnamese-Vi
> > > ### Other details
> > > Thanks for reading the article
> > > ### Acknowledgements
> > > 
> > > * [x]    I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> > > * [x]    I have checked that the source does not already exist on the app.
> > > * [x]    I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.
> > 
> > 
> > đoán là a bạn này có vấn đề về đôi mắt 🐧 ![image](https://private-user-images.githubusercontent.com/131387159/377095093-92d5e6f7-31b5-464f-bc9f-9cbee7011e87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTM1ODksIm5iZiI6MTcyOTA5MzI4OSwicGF0aCI6Ii8xMzEzODcxNTkvMzc3MDk1MDkzLTkyZDVlNmY3LTMxYjUtNDY0Zi1iYzlmLTljYmVlNzAxMWU4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxNTQxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzA5NTJkZjA4ZDM1NjNmYjQ3Mjc3NTBmOGJmZmNlNDVjNWJiMWM5NjQ0NzkzNTc4NTIxZTY4NjYzMTVhOTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.miKak2VW3M2zDAWkqzLYzpmUyctesfgelg7NF36FrL8)
> 
> sao trong máy tôi trong mục tiếng việt và không thấy nguồn này nhỉ , dù đã cập nhật

kiểm tra phiên bản xem 🐧 
![image](https://github.com/user-attachments/assets/579b0b3f-c2f4-4ebb-9e95-432f6e8e8d63)

**Comment by tuanbmt4152** [comment]
> > > > ### Source name
> > > > Sayhentai
> > > > ### Source link
> > > > https://sayhentai.one/
> > > > ### Language
> > > > Vietnamese-Vi
> > > > ### Other details
> > > > Thanks for reading the article
> > > > ### Acknowledgements
> > > > 
> > > > * [x]     I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> > > > * [x]     I have checked that the source does not already exist on the app.
> > > > * [x]     I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.
> > > 
> > > 
> > > đoán là a bạn này có vấn đề về đôi mắt 🐧 ![image](https://private-user-images.githubusercontent.com/131387159/377095093-92d5e6f7-31b5-464f-bc9f-9cbee7011e87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTM1ODksIm5iZiI6MTcyOTA5MzI4OSwicGF0aCI6Ii8xMzEzODcxNTkvMzc3MDk1MDkzLTkyZDVlNmY3LTMxYjUtNDY0Zi1iYzlmLTljYmVlNzAxMWU4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxNTQxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzA5NTJkZjA4ZDM1NjNmYjQ3Mjc3NTBmOGJmZmNlNDVjNWJiMWM5NjQ0NzkzNTc4NTIxZTY4NjYzMTVhOTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.miKak2VW3M2zDAWkqzLYzpmUyctesfgelg7NF36FrL8)
> > 
> > 
> > sao trong máy tôi trong mục tiếng việt và không thấy nguồn này nhỉ , dù đã cập nhật
> 
> kiểm tra phiên bản xem 🐧 ![image](https://private-user-images.githubusercontent.com/131387159/377134575-579b0b3f-c2f4-4ebb-9e95-432f6e8e8d63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDgzMzgsIm5iZiI6MTcyOTE0ODAzOCwicGF0aCI6Ii8xMzEzODcxNTkvMzc3MTM0NTc1LTU3OWIwYjNmLWMyZjQtNGViYi05ZTk1LTQzMmY2ZThlOGQ2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QwNjUzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTAzZjQ3NmJjNGQxMzY0OWY5YzljZDNiZmE1OGNiMjM5Nzg0Y2Q3MGI1MjY0YTc2MjQ5M2E4NzdkMjcxYzgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dr96T6o7mSeJ1BVYSaRnLvC0whHeUyxCIZWyciFvGVI)

Tải bản mới nhất trên web là 7.6.4 =))
Còn bản 7.7-a1 thì tôi chịu không biết nó ở đâu =))

**Comment by dragonx943** [comment]
> > > > > ### Source name
> > > > > Sayhentai
> > > > > ### Source link
> > > > > https://sayhentai.one/
> > > > > ### Language
> > > > > Vietnamese-Vi
> > > > > ### Other details
> > > > > Thanks for reading the article
> > > > > ### Acknowledgements
> > > > > 
> > > > > * [x]      I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> > > > > * [x]      I have checked that the source does not already exist on the app.
> > > > > * [x]      I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.
> > > > 
> > > > 
> > > > đoán là a bạn này có vấn đề về đôi mắt 🐧 ![image](https://private-user-images.githubusercontent.com/131387159/377095093-92d5e6f7-31b5-464f-bc9f-9cbee7011e87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTM1ODksIm5iZiI6MTcyOTA5MzI4OSwicGF0aCI6Ii8xMzEzODcxNTkvMzc3MDk1MDkzLTkyZDVlNmY3LTMxYjUtNDY0Zi1iYzlmLTljYmVlNzAxMWU4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxNTQxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzA5NTJkZjA4ZDM1NjNmYjQ3Mjc3NTBmOGJmZmNlNDVjNWJiMWM5NjQ0NzkzNTc4NTIxZTY4NjYzMTVhOTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.miKak2VW3M2zDAWkqzLYzpmUyctesfgelg7NF36FrL8)
> > > 
> > > 
> > > sao trong máy tôi trong mục tiếng việt và không thấy nguồn này nhỉ , dù đã cập nhật
> > 
> > 
> > kiểm tra phiên bản xem 🐧 ![image](https://private-user-images.githubusercontent.com/131387159/377134575-579b0b3f-c2f4-4ebb-9e95-432f6e8e8d63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDgzMzgsIm5iZiI6MTcyOTE0ODAzOCwicGF0aCI6Ii8xMzEzODcxNTkvMzc3MTM0NTc1LTU3OWIwYjNmLWMyZjQtNGViYi05ZTk1LTQzMmY2ZThlOGQ2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QwNjUzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTAzZjQ3NmJjNGQxMzY0OWY5YzljZDNiZmE1OGNiMjM5Nzg0Y2Q3MGI1MjY0YTc2MjQ5M2E4NzdkMjcxYzgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dr96T6o7mSeJ1BVYSaRnLvC0whHeUyxCIZWyciFvGVI)
> 
> Tải bản mới nhất trên web là 7.6.4 =)) Còn bản 7.7-a1 thì tôi chịu không biết nó ở đâu =))

chỉ có dev mới có 7.7-a1, giờ là 7.7-a2 🐧

**Comment by dragonx943** [comment]
> ### Source name
> Sayhentai
> 
> ### Source link
> https://sayhentai.one/
> 
> ### Language
> Vietnamese-Vi
> 
> ### Other details
> Thanks for reading the article
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have checked that the source does not already exist on the app.
> * [x]  I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

Done https://github.com/KotatsuApp/kotatsu-parsers/pull/1174
