### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by BigBagelBoss** [KotatsuApp/kotatsu-parsers#1188]
### Source information

OmegaScans

### Steps to reproduce

1. Open OmegaScans source
2. Try to open any of their titles

### Kotatsu version

7.6.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by MariusAlbrecht** [comment]
also happens for ReaperComics

**Comment by Koitharu** [comment]
Fixed in 4c5ed57958759d8d0eb2afce18839d3f73411c6e
