### ISSUE TITLE
Manga District has no available chapters in app

### ISSUE THREAD

**Issue by powerfulparadox** [KotatsuApp/kotatsu-parsers#119]
### Source information

Manga District

### Steps to reproduce

1. Explore Manga District
2. Select any manga
3. No available chapters

### Kotatsu version

4.0.4

### Android version

Android 12

### Other details

All mangas from Manga District (mangadistrict.com) are listed as having no available chapters, despite chapters being available and readable on their website.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
Need to close this works now

**Comment by davvarrr** [comment]
@ztimms73
