### ISSUE TITLE
Chapter numbering in the App is reversed for the Source

### ISSUE THREAD

**Issue by NguyenVoAnhKiet** [KotatsuApp/kotatsu-parsers#1190]
### Brief summary

**Source** 
nhattruyenvn.com
![Screenshot_2024-10-15-15-43-39-122_org koitharu kotatsu](https://github.com/user-attachments/assets/37a3516f-7bda-45fe-9d9d-8e536e883fa2)

### Kotatsu version

7.6.4

### Android version

14

### Device

Redmi k50 

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by dragonx943** [comment]
> ### Brief summary
> **Source** nhattruyenvn.com ![Screenshot_2024-10-15-15-43-39-122_org koitharu kotatsu](https://private-user-images.githubusercontent.com/116576642/376532819-37a3516f-7bda-45fe-9d9d-8e536e883fa2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMTM3NDQsIm5iZiI6MTczMDExMzQ0NCwicGF0aCI6Ii8xMTY1NzY2NDIvMzc2NTMyODE5LTM3YTM1MTZmLTdiZGEtNDVmZS05ZDlkLThlNTM2ZTg4M2ZhMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQxMTA0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjYyYTk2NjE0ZWJjNDgxYmRiMmFmMjcyZDQwY2EzYTRhNDM3Nzg0ZDU0NGZlZjllNjdjMzJlMTQzOGI4NzI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.edx0DG4qd2yWdiCubRUVaA9yeVa7cpbpbeN7WU1pics)
> 
> ### Steps to reproduce
> _No response_
> 
> ### Kotatsu version
> 7.6.4
> 
> ### Android version
> 14
> 
> ### Device
> Redmi k50
> 
> ### Acknowledgements
> * [x]  This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
> * [x]  This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

Sẽ fix sớm !

**Comment by dragonx943** [comment]
> > This is not an issue with a specific manga source. Otherwise, you have to open an issue in the parsers repository.

yep, this is

**Comment by dragonx943** [comment]
> ### Brief summary
> **Source** nhattruyenvn.com ![Screenshot_2024-10-15-15-43-39-122_org koitharu kotatsu](https://private-user-images.githubusercontent.com/116576642/376532819-37a3516f-7bda-45fe-9d9d-8e536e883fa2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMzAzMjEsIm5iZiI6MTczMDIzMDAyMSwicGF0aCI6Ii8xMTY1NzY2NDIvMzc2NTMyODE5LTM3YTM1MTZmLTdiZGEtNDVmZS05ZDlkLThlNTM2ZTg4M2ZhMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxOTI3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGZkYjRiM2RkZDgzMzJkNzdkZGUyYTE0YjRhNTIxNzE2MTQ4MzExMzQ4ZmRhZjZiMWM4ZWJmMWRiNDAwOTkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-GonrGPz-PdtRQf1J9dwnsDQx54ptOO_hjKEWInr-nU)
> 
> ### Steps to reproduce
> _No response_
> 
> ### Kotatsu version
> 7.6.4
> 
> ### Android version
> 14
> 
> ### Device
> Redmi k50
> 
> ### Acknowledgements
> * [x]  This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
> * [x]  This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

Done https://github.com/KotatsuApp/kotatsu-parsers/pull/1199
