### ISSUE TITLE
"No value for slug" error on vortexscans source – Unable to view manga chapters

### ISSUE THREAD

**Issue by Adiversion** [KotatsuApp/kotatsu-parsers#1209]
### Source information

vortexscans.org

### Steps to reproduce

1. Open the manga source "vortexscans" within the app.
2. Select any manga title from the list.
3. The manga title appears, but when I click on it, the error message "no value for slug" is displayed, and no chapters are shown.
4. However, I can access the same manga title and chapters directly on the website (vortexscans.org).

Attached Image
![WhatsApp Image 2024-11-04 at 11 36 44 AM](https://github.com/user-attachments/assets/4fda05f4-e6a8-43b8-8a28-e64c42059bb4)

### Kotatsu version

7.6.6

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by dragonx943** [comment]
> ### Source information
> vortexscans.org
> 
> ### Steps to reproduce
> 1. Open the manga source "vortexscans" within the app.
> 2. Select any manga title from the list.
> 3. The manga title appears, but when I click on it, the error message "no value for slug" is displayed, and no chapters are shown.
> 4. However, I can access the same manga title and chapters directly on the website (vortexscans.org).
> 
> Attached Image ![WhatsApp Image 2024-11-04 at 11 36 44 AM](https://private-user-images.githubusercontent.com/99112612/382655975-4fda05f4-e6a8-43b8-8a28-e64c42059bb4.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDI5NDAsIm5iZiI6MTczMDcwMjY0MCwicGF0aCI6Ii85OTExMjYxMi8zODI2NTU5NzUtNGZkYTA1ZjQtZTZhOC00M2I4LThhMjgtZTY0YzQyMDU5YmI0LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwNjQ0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODE0ZDczMWNkMjg0MDM4NDViYWU2NWYyNWJkZDcwYWNiNzc1NzgxMDk5Yzc0ZDc4NWQ5ZjIwMjBkMGQzMjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EC42FUfQ0AvdjgyP5XX6LaFKPbs4pqsmrVL6QNw_YzY)
> 
> ### Kotatsu version
> 7.6.6
> 
> ### Android version
> Android 14
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

Duplicate #1207
