### ISSUE TITLE
Can you add new filters in VortexScans sources?

### ISSUE THREAD

**Issue by Zakatax** [KotatsuApp/kotatsu-parsers#1210]
### Describe your suggested feature

Can you add other filters to sort the works in addition to the one already present? 
Type:
-Sort by updated
-Sort by name
-Sort by add 
These are the most fundamental ones. Thanks for your availability 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by dragonx943** [comment]
🐧
