### ISSUE TITLE
"The chapter is missing" error on everything from AsuraComic

### ISSUE THREAD

**Issue by Tel-Magician** [KotatsuApp/kotatsu-parsers#1222]
### Source information

AsuraComic

### Steps to reproduce

Step 1: just open any saved item from AsuraComic
Step 2 the The read/chapter buttom is replaces with the text "The chapter is missing", clicking the button will display the same message on the botom of the screen.

Used Ominiscient Reader's Viewpoint as a reffrence in the picture but its on all items from AsuraComic
![image_2024-11-11_191451253](https://github.com/user-attachments/assets/0825ef22-ffae-4bcb-9802-2dc32f117dd5)

### Kotatsu version

7.6.7

### Android version

Android 14

### Other details

There is a very temporary fix, by migrating the AsuraComic item to the same AsuraComic item you can read your items again and everything seems to be fine, but the same problem hapens within a day and there is no warning of when this happens so you cant know if the problem is currently present, while the problem is present the feed doesnt give you updates and its tedious to migrate all the items every day.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by dragonx943** [comment]
> ### Source information
> AsuraComic
> 
> ### Steps to reproduce
> Step 1: just open any saved item from AsuraComic Step 2 the The read/chapter buttom is replaces with the text "The chapter is missing", clicking the button will display the same message on the botom of the screen.
> 
> Used Ominiscient Reader's Viewpoint as a reffrence in the picture but its on all items from AsuraComic ![image_2024-11-11_191451253](https://private-user-images.githubusercontent.com/154839889/385023149-0825ef22-ffae-4bcb-9802-2dc32f117dd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODAwNTEsIm5iZiI6MTczMTQ3OTc1MSwicGF0aCI6Ii8xNTQ4Mzk4ODkvMzg1MDIzMTQ5LTA4MjVlZjIyLWZmYWUtNGJjYi05ODAyLTJkYzMyZjExN2RkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QwNjM1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTVmNjA5M2JhZGYwODIwNWJjZWE5NTg0MjRhZTE1MTE0MzA1MmYwM2Y3ZGYxZDQyZTRmM2U2MDc0YjkyY2E2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mEUZInRRVMxgy9FZEyAD9M8sSQ_iJ5-xgYsnu-M73Lc)
> 
> ### Kotatsu version
> 7.6.7
> 
> ### Android version
> Android 14
> 
> ### Other details
> There is a very temporary fix, by migrating the AsuraComic item to the same AsuraComic item you can read your items again and everything seems to be fine, but the same problem hapens within a day and there is no warning of when this happens so you cant know if the problem is currently present, while the problem is present the feed doesnt give you updates and its tedious to migrate all the items every day.
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

@Tel-Magician backup ur data and re-install kotatsu app (and of course, restore ur data after re-install it) OR u can try [Kotatsu Nightly](https://github.com/KotatsuApp/Kotatsu-nightly)

![image](https://github.com/user-attachments/assets/8f18e027-61cc-4f47-8f63-e0e201c1926a)
