### ISSUE TITLE
Problems at the source 

### ISSUE THREAD

**Issue by CintiaM1907** [KotatsuApp/kotatsu-parsers#1225]
### Source information

https://cerise.leitorweb.com/

### Steps to reproduce

org.koitharu.kotatsu.parsers.exception.ParseException: Cannot find username at https://cerise.leitorweb.com/
	at org.koitharu.kotatsu.parsers.util.MangaParserEnvKt.parseFailed(SourceFile:18)
	at org.koitharu.kotatsu.parsers.site.madara.MadaraParser.getUsername$suspendImpl(SourceFile:134)
	at org.koitharu.kotatsu.parsers.site.madara.MadaraParser$getUsername$1.invokeSuspend(Unknown Source:11)

t kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:109)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:122)

### Kotatsu version

7.6 7

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by CintiaM1907** [comment]
![Screenshot_20241113-023821](https://github.com/user-attachments/assets/6633d659-4074-49f6-a3dd-b6e4835c7e82)
Website is working perfectly

**Comment by dragonx943** [comment]
> ### Source information
> https://cerise.leitorweb.com/
> 
> ### Steps to reproduce
> org.koitharu.kotatsu.parsers.exception.ParseException: Cannot find username at https://cerise.leitorweb.com/ at org.koitharu.kotatsu.parsers.util.MangaParserEnvKt.parseFailed(SourceFile:18) at org.koitharu.kotatsu.parsers.site.madara.MadaraParser.getUsername$suspendImpl(SourceFile:134) at org.koitharu.kotatsu.parsers.site.madara.MadaraParser$getUsername$1.invokeSuspend(Unknown Source:11)
> 
> t kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9) at kotlinx.coroutines.DispatchedTask.run(SourceFile:109) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:122)
> 
> ### Kotatsu version
> 7.6 7
> 
> ### Android version
> Android 13
> 
> ### Other details
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

Duplicated https://github.com/KotatsuApp/kotatsu-parsers/issues/1224
