### ISSUE TITLE
마나토끼(manatoki)

### ISSUE THREAD

**Issue by AndyH0ng** [KotatsuApp/kotatsu-parsers#123]
### Source name

Manatoki

### Source link

https://manatoki166.net/

### Language

Korean

### Other details

It's the biggest manga hosting site in 🇰🇷 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
You could close this isssu because the requested domain is dead
