### ISSUE TITLE
Asura Scans showing content not found or removed 

### ISSUE THREAD

**Issue by Pop123p** [KotatsuApp/kotatsu-parsers#1236]
### Source information

Asura Scans

### Steps to reproduce

1. Open Asura Scans
2. Open any manga 
3. Click on chapter 
4. It shows content not found or removed 

### Kotatsu version

7.6.7

### Android version

Android 14

### Other details

![Screenshot_2024-11-19-07-26-00-14_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/user-attachments/assets/e03087b3-a74c-4808-a9c8-8ff5f33c2a9e)
![Screenshot_2024-11-19-07-26-03-45_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/user-attachments/assets/753aa314-8ee9-4752-8bd9-a600b726aadf)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by dragonx943** [comment]
Fixed

**Comment by doggerxd** [comment]
Not fixed.
Still the same thing
