### ISSUE TITLE
Asurascans not working 

### ISSUE THREAD

**Issue by Shadow573** [KotatsuApp/kotatsu-parsers#1238]
### Source information

Asurascans

### Steps to reproduce

Was working fine yesterday 

Later in the evening it stopped work8ng where content not found was shown.
![Screenshot_20241119_072106_Kotatsu](https://github.com/user-attachments/assets/e2f9d536-85ca-45dd-9535-dd9fae44dbf7)

### Kotatsu version

7.6.7

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by dragonx943** [comment]
> ### Source information
> Asurascans
> 
> ### Steps to reproduce
> Was working fine yesterday
> 
> Later in the evening it stopped work8ng where content not found was shown. ![Screenshot_20241119_072106_Kotatsu](https://private-user-images.githubusercontent.com/69486973/387670951-e2f9d536-85ca-45dd-9535-dd9fae44dbf7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMjMwODMsIm5iZiI6MTczMjAyMjc4MywicGF0aCI6Ii82OTQ4Njk3My8zODc2NzA5NTEtZTJmOWQ1MzYtODVjYS00NWRkLTk1MzUtZGQ5ZmFlNDRkYmY3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDEzMjYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMThmOTNmMWJhYzY0YWQ1OTZiOWYyYmI5YzQ4ZGYzMTcyYTJmZDg2NTE0NmZlN2U0MjVlNWM1YzVmMDdhZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8wrE8JayOXiw2fKoGY6TeuE4hgzAAhjz9bHReYT2q9Y)
> 
> ### Kotatsu version
> 7.6.7
> 
> ### Android version
> Android 13
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

Duplicated #1236
