### ISSUE TITLE
Error cannot find "list-info"

### ISSUE THREAD

**Issue by ItsSunny87** [KotatsuApp/kotatsu-parsers#1239]
### Source information

Likemanga

### Steps to reproduce

Error occurs when trying to open a manga from the source already favorited. 

### Kotatsu version

7.6.7

### Android version

14

### Other details

This is the exact full error code. 

org.koitharu.kotatsu.parsers.exception.ParseException: Cannot find ".list-info li.othername h2" at https://likemanga.in/
	at org.koitharu.kotatsu.parsers.util.JsoupUtils.selectFirstOrThrow(SourceFile:34)
	at org.koitharu.kotatsu.parsers.site.likemanga.en.LikeManga.getDetails$suspendImpl(SourceFile:226)
	at org.koitharu.kotatsu.parsers.site.likemanga.LikeMangaParser$getDetails$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:109)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:122)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by dragonx943** [comment]
> ### Source information
> Likemanga
> 
> ### Steps to reproduce
> Error occurs when trying to open a manga from the source already favorited.
> 
> ### Kotatsu version
> 7.6.7
> 
> ### Android version
> 14
> 
> ### Other details
> This is the exact full error code.
> 
> org.koitharu.kotatsu.parsers.exception.ParseException: Cannot find ".list-info li.othername h2" at https://likemanga.in/ at org.koitharu.kotatsu.parsers.util.JsoupUtils.selectFirstOrThrow(SourceFile:34) at org.koitharu.kotatsu.parsers.site.likemanga.en.LikeManga.getDetails$suspendImpl(SourceFile:226) at org.koitharu.kotatsu.parsers.site.likemanga.LikeMangaParser$getDetails$1.invokeSuspend(Unknown Source:12) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9) at kotlinx.coroutines.DispatchedTask.run(SourceFile:109) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:122)
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

change source domain to likemanga.ink
