### ISSUE TITLE
[MangaArabic] Website is down or domain changed

### ISSUE THREAD

**Issue by sola2002** [KotatsuApp/kotatsu-parsers#1249]
### Source information

MangaArabic 

### Steps to reproduce

1- Doesn't work at app
2- It appears as non-existent even though it is in the browser Google 

### Kotatsu version

1-7.7

### Android version

Android 11

### Other details

most of the sources of arabic it's doesn't work even though Available in Google browser 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by sola2002** [comment]
When does the repair end?

**Comment by Koitharu** [comment]
Looks like website is down or domain has been changed. Does anyone know the new domain?

**Comment by dragonx943** [comment]
> Looks like website is down or domain has been changed. Does anyone know the new domain?

suspended page 🐧 
![image](https://github.com/user-attachments/assets/7b64545a-2054-4ada-b0c0-70958ebd5aee)

**Comment by dragonx943** [comment]
> ### Source information
> MangaArabic
> 
> ### Steps to reproduce
> 1- Doesn't work at app 2- It appears as non-existent even though it is in the browser Google
> 
> ### Kotatsu version
> 1-7.7
> 
> ### Android version
> Android 11
> 
> ### Other details
> most of the sources of arabic it's doesn't work even though Available in Google browser
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

Done https://github.com/KotatsuApp/kotatsu-parsers/pull/1254
