### ISSUE TITLE
They changed the structure of the site

### ISSUE THREAD

**Issue by Furygo33** [KotatsuApp/kotatsu-parsers#1250]
### Source information

MerlinScans 

### Steps to reproduce

I enter the source, it asks for verification, I do it but it gives an error that way too, I say open in browser, it gives an error there too 
![Screenshot_2024-11-21-16-37-04-097_org koitharu kotatsu](https://github.com/user-attachments/assets/e6c7d56e-57d0-4219-9b98-f8f1dbde72d8)
![Screenshot_2024-11-21-16-37-24-886_org koitharu kotatsu](https://github.com/user-attachments/assets/a7908315-e320-4fca-98c3-edb7f27d27f6)

### Kotatsu version

Kotatsu 7.7-beta1

### Android version

Android 13 (redmi note 8/ 2021)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
I cannot fix it: this website is not available for me
![изображение](https://github.com/user-attachments/assets/392ca6c6-3559-4a09-9e36-93b0dd169580)

**Comment by Furygo33** [comment]
![Screenshot_2024-11-23-22-01-40-836_com android chrome](https://github.com/user-attachments/assets/54422b35-f8fc-4e7e-a800-4727a6706b82)
The site opens for me but it is very very slow. Is the problem caused by the site?

**Comment by Furygo33** [comment]
The site is opening properly now, I don't understand what is causing the problem.
