### ISSUE TITLE
Cannot Find Root (ninemanga.com)

### ISSUE THREAD

**Issue by lorddoddydog** [KotatsuApp/kotatsu-parsers#1253]
### Source information

Ninemanga.com

### Steps to reproduce

https://github.com/user-attachments/assets/4329232c-5a17-4b27-b9a7-d0b7dbaef934

### Kotatsu version

7.7 b1 (stable also i try)

### Android version

Android 14

### Other details

![Screenshot_20241122-034452](https://github.com/user-attachments/assets/0901cf91-a03f-4093-a586-3a9e17bc667f)
![Screenshot_20241122-033918](https://github.com/user-attachments/assets/701892ae-b72b-4fa9-bcf8-b7867af3d25a)

https://github.com/user-attachments/assets/e91b13ce-1e72-4b26-a926-ebdf13bbba33

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by dragonx943** [comment]
Just have problem with thumbnail image, not index page
Duplicated https://github.com/KotatsuApp/kotatsu-parsers/issues/1248
