### ISSUE TITLE
All chapters open banners

### ISSUE THREAD

**Issue by matiteus** [KotatsuApp/kotatsu-parsers#1257]
### Source information

AsuraComic

### Steps to reproduce

Just open any asura comic manga, there are the same 4 banners in every chapter

### Kotatsu version

7.7-beta2

### Android version

Android 13

### Other details

![Screenshot_20241123_182547_Kotatsu](https://github.com/user-attachments/assets/c49651f0-d403-4b08-9c6a-70400da2d17e)
![Screenshot_20241123_182534_Kotatsu](https://github.com/user-attachments/assets/ffd579c5-ca8c-4b2d-bc8d-b0ee977cbdaa)
![Screenshot_20241123_182529_Kotatsu](https://github.com/user-attachments/assets/586842bf-ba9f-479e-b474-b3bf677d262a)
![Screenshot_20241123_182524_Kotatsu](https://github.com/user-attachments/assets/6bd5ef8e-7d21-4d69-b0f1-678e3052544a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Dorukaga15** [comment]
Did you check the site?

**Comment by matiteus** [comment]
The site works fine, I've been reading from there since then.

**Comment by Zoetatua** [comment]
i can verify that i am having the exact same issue

**Comment by musdx** [comment]
I also have same issue just about to make a report but saw this
