### ISSUE TITLE
Kotatsu

### ISSUE THREAD

**Issue by Jansen634** [KotatsuApp/kotatsu-parsers#1264]
### Source information

Mangadex

### Kotatsu version

"7.6"

### Android version

Android 14

### Other details

Bug

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by dragonx943** [comment]
> ### Source information
> Mangadex
> 
> ### Steps to reproduce
> _No response_
> 
> ### Kotatsu version
> "7.6"
> 
> ### Android version
> Android 14
> 
> ### Other details
> Bug
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

no info = no support
and 7.6 is old Kotatsu version, pls update it :p
