### ISSUE TITLE
MangaTigre

### ISSUE THREAD

**Issue by LeeanPR95** [KotatsuApp/kotatsu-parsers#127]
### Source name

MangaTigre

### Source link

https://www.mangatigre.net

### Language

Spanish

### Other details

Complete web source, with updated manga and a wide variety of filters.
Sorry for my bad eng

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
source dead
