### ISSUE TITLE
No entry shown on mangahaTachi

### ISSUE THREAD

**Issue by roflsunriz** [KotatsuApp/kotatsu-parsers#128]
### Brief summary

no manga will shown on Search>remote source>mangahaTachi

### Steps to reproduce

1.go Search
2.go mangahaTachi under remote sources
3.nothing

### Kotatsu version

4.0.6

### Android version

13

### Device

Google Pixel 6a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Change domain from `mangahatachi.com` to `hachimanga.com` in source settings

**Comment by roflsunriz** [comment]
ah, ok. sorry for bothering you.
