### ISSUE TITLE
403 access denied

### ISSUE THREAD

**Issue by A7vi-1** [KotatsuApp/kotatsu-parsers#1295]
### Source information

Like-manga.net

### Steps to reproduce

It's working in browser fine but when I use the app it gives me access denied and i talked to support They told me that the site has updated its parsing protection  

### Kotatsu version

7.7.1

### Android version

Emui 12.0.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by dragonx943** [comment]
> ### Source information
> Like-manga.net
> 
> ### Steps to reproduce
> It's working in browser fine but when I use the app it gives me access denied and i talked to support They told me that the site has updated its parsing protection
> 
> ### Kotatsu version
> 7.7.1
> 
> ### Android version
> Emui 12.0.0
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

use any VPNs / Proxy or simple: Download 1.1.1.1 and use it = Fixed 👌 
![image](https://github.com/user-attachments/assets/e0b8c739-8127-4876-b773-7603afd34177)
