### ISSUE TITLE
captcha cache

### ISSUE THREAD

**Issue by Dicko46** [KotatsuApp/kotatsu-parsers#1314]
### Describe your suggested feature

Is it possible to save the captcha cache for each time you complete a captcha, because it is very annoying if every time you exit the application and log back in you are asked for a captcha which will also interfere with checking updates on the manga when the application is running in the background? 

### Other details

more like an extension on mihon which is not much no need to do recaptcha 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Kisbivaly** [comment]
Hi so i think you get something wrong captchas is basicaly creating cookies the app already saves the cookies the only way you need to redo captchas that the site/parser you use has a very fast expiration rate in this case it woukd be good if you could share this site/parser the other option is that youre phone has a setting that clears yore chace

**Comment by dragonx943** [comment]
> ### Describe your suggested feature
> Is it possible to save the captcha cache for each time you complete a captcha, because it is very annoying if every time you exit the application and log back in you are asked for a captcha which will also interfere with checking updates on the manga when the application is running in the background?
> 
> ### Other details
> more like an extension on mihon which is not much no need to do recaptcha
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

Kotatsu currently uses [Android System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=vi) to save your cookies, browse and use it when u solved a captcha and maintain it throughout the usage process (and its only valid for a short time, not permanent or long term)
