### ISSUE TITLE
imhentai.xxx [English]

### ISSUE THREAD

**Issue by Safuez** [KotatsuApp/kotatsu-parsers#132]
### Source name

MReader, IMHentai

### Source link

https://imhentai.xxx/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
I removed mreader.co because it is already present under the name mangageko.com
