### ISSUE TITLE
lectortmo

### ISSUE THREAD

**Issue by MakuSensei** [KotatsuApp/kotatsu-parsers#140]
### Source name

Tumangaonline

### Source link

https://lectortmo.com/

### Language

Spanish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
The issue may be to close the source is already present:  https://github.com/KotatsuApp/kotatsu-parsers/blob/506f6f7d30d09b2dade0574fbd306a56b47fefb2/src/main/kotlin/org/koitharu/kotatsu/parsers/site/es/TuMangaOnlineParser.kt#L23
