### ISSUE TITLE
Manga District & Hentai4free

### ISSUE THREAD

**Issue by killerlearner** [KotatsuApp/kotatsu-parsers#157]
### Source information

Manga District, Hentai4free

### Steps to reproduce

Just open any manga and you will see no chapters 

### Kotatsu version

4.4.1

### Android version

Android 13

### Other details

![Screenshot_20230224-220004_Kotatsu](https://user-images.githubusercontent.com/67904798/221234139-11667c8c-4e21-441d-8c7b-a4dcabea2381.png)
![Screenshot_20230224-215721_Kotatsu](https://user-images.githubusercontent.com/67904798/221234150-3c8c4837-2491-4109-9cdf-8139819e2e94.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by A369-source** [comment]
How to solve this problem
