### ISSUE TITLE
Tempest fansub has updated their domain again.

### ISSUE THREAD

**Issue by kyoyacchi** [KotatsuApp/kotatsu-parsers#175]
### Source information

Tempestfansub 

### Steps to reproduce

1. Try to read any manga from Tempest fansub source.
2. It does load manga but repetitively loads same manga as you scroll down

### Kotatsu version

5.1.4

### Android version

Android 11 

### Other details

https://manga.tempestfansub.com/anasayfa/

This is the new domain. 
(Ana sayfa/anasayfa means home/home page)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
issues can be close the domain name was changed
