### ISSUE TITLE
Unable to parse TLS packet header

### ISSUE THREAD

**Issue by lusepro** [KotatsuApp/kotatsu-parsers#176]
### Source information

manhwa18

### Steps to reproduce

1. Try to open manga in a web browser to ensure it is available on its source 
3. Make sure you are using the latest version of Kotatsu 
4. If it is available, send an error report to the developers.

### Kotatsu version

5.1.4

### Android version

android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
the source works correctly, if you still encounter an error please provide more details.
