### ISSUE TITLE
Known problems

### ISSUE THREAD

**Issue by davvarrr** [KotatsuApp/kotatsu-parsers#198]

**Comment by Death415** [comment]
![Screenshot_2023-10-28-22-59-30-50_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/KotatsuApp/kotatsu-parsers/assets/61976889/1727ba88-ca6d-43b1-a10e-ad76bdbb869e)
It was working a little while ago and now suddenly it's like this ?!
(My version 6.2.5)
https://goldragon.me/

**Comment by Koitharu** [comment]
I'll look at it

**Comment by Koitharu** [comment]
I have tried to resolve first issue with "redirection because of no javascript" that actually is a protection against parsing, but looks like this is not so easy to bypass it...
