### ISSUE TITLE
Make Nhentai theme like madara theme

### ISSUE THREAD

**Issue by OshekharO** [KotatsuApp/kotatsu-parsers#20]
### Describe your suggested feature

Well there are many sites which are using Nhentai template so please convert it into dynamic template like madara template. As I already have mentioned for another specific theme #10 and have mentioned 5 to 6 sites using that theme.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/nv95/Kotatsu/issues/new/choose).
- [X] I have updated the app to version **[3.3](https://github.com/nv95/Kotatsu/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ztimms73** [comment]
> Nhentai template

From this place in more detail. Can you provide a list of sites that use the "NHentai" theme?
