### ISSUE TITLE
Check failed JapScan

### ISSUE THREAD

**Issue by pixelroll** [KotatsuApp/kotatsu-parsers#200]
### Source information

JapScan

### Steps to reproduce

try to play a chapter, the message "check failed" appears.

### Kotatsu version

5.3.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
I added a fix to this pr #197 , now I just have to wait for it to be accepted.
