### ISSUE TITLE
source's

### ISSUE THREAD

**Issue by Chahinpirate** [KotatsuApp/kotatsu-parsers#204]
### Source information

Please add more source's

### Steps to reproduce

Hello i talked with admin in telegram he told me to create issue to add more source's 
Azora manga
Mangaswat
Teamx
Arabtoons +18
And thank you 

### Kotatsu version

5.3.3

### Android version

Android 12

### Other details

Just asking how are u team 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
they're all there: 
https://github.com/KotatsuApp/kotatsu-parsers/blob/400a90464e205195c01b173002dea1a5011e1f99/src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/ar/Azoranov.kt
https://github.com/KotatsuApp/kotatsu-parsers/blob/400a90464e205195c01b173002dea1a5011e1f99/src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/ar/SwaTeam.kt
https://github.com/KotatsuApp/kotatsu-parsers/blob/400a90464e205195c01b173002dea1a5011e1f99/src/main/kotlin/org/koitharu/kotatsu/parsers/site/ar/TeamXNovel.kt
https://github.com/KotatsuApp/kotatsu-parsers/blob/400a90464e205195c01b173002dea1a5011e1f99/src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/ar/ArabToons.kt
