### ISSUE TITLE
[AinzScans] New Website Request

### ISSUE THREAD

**Issue by MIRVOUS** [KotatsuApp/kotatsu-parsers#209]
### Source name

AinzScans

### Source link

https://ainzscans.site

### Language

Indonesian

### Other details

![Screenshot_2023-07-10-12-21-10-268_com opera browser](https://github.com/KotatsuApp/kotatsu-parsers/assets/45929526/9b76f359-cb8d-47da-aa46-e423485c7f22)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by Oneloutre** [comment]
Seems to be WordpressMangaStream, just seeing its interface.

**Comment by davvarrr** [comment]
It has been added to the pr #208

**Comment by Oneloutre** [comment]
Yeah no problem
It's because it's a really widely used theme on WordPress 
So there is a template developed to make the dev reaaaallllyyyyy fast (a few lines) so, since it's far fastier and easier than your website, it has been added before
