### ISSUE TITLE
JapScan Cannot decode page list

### ISSUE THREAD

**Issue by pixelroll** [KotatsuApp/kotatsu-parsers#211]
### Source information

JapScan

### Steps to reproduce

Read a chapter

### Kotatsu version

5.3.4

### Android version

Android 12

### Other details

![Uploading Screenshot_2023-07-17-08-59-17-275_org.koitharu.kotatsu.jpg…]()

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Oneloutre** [comment]
I already discussed about this issue with a dev, it should be corrected during the week if everything goes right

**Comment by Koitharu** [comment]
It seems to be a bit challenging...

**Comment by Oneloutre** [comment]
Uh okay 😂😂😂 But yeah anyway I switched my source for now

**Comment by pixelroll** [comment]
> Uh okay 😂😂😂 But yeah anyway I switched my source for now

Is there a migration option or do you have to do everything manually?  please

**Comment by Oneloutre** [comment]
Nah there isn't now. I switched from tachi a few days ago so I did it manually since I just had a few titles to moove :/

**Comment by bastien-poudou** [comment]
I've noticed Japscan added a donation banner on their site, is it possible that it mess up the parsing in some way ?

**Comment by Oneloutre** [comment]
Nope @bastien-poudou the donation goal banner IS here since few years and the source is broken since a few days

**Comment by Koitharu** [comment]
Pages urls are encoded and the encoding algorithm was changed. I didn't manage to figure out how it works now

**Comment by Koitharu** [comment]
Broken again( 
Such a terrible source...
