### ISSUE TITLE
[Asura Scans] Occasional "Content not found or removed"

### ISSUE THREAD

**Issue by ZBE69** [KotatsuApp/kotatsu-parsers#213]
### Brief summary

I'm not sure whether to label this as a source issue or a bug with Kotatsu, so forgive me if I made a mistake. Essentially, after some time (a week or few days), some *favourite* mangas give the "content not found or removed" error. Opening the manga link in the web-browser confirms that the URL is invalid: 404, page not found. This is common with [Asura Scans](https://www.asurascans.com), though I have observed the same issue with [Flame Scans](https://flamescans.org/).

The manga however isn't actually deleted/removed from the source. Searching for the manga again works so I imagine the cause is due to a change in the URL, hence why I opened the issue here instead of the [parser repository](https://github.com/KotatsuApp/kotatsu-parsers).

I understand that fixing this issue may warrant a refactor of the internals. As an alternative, would it be possible to tell/show what the last read chapter was instead of outright displaying the error? That way I can migrate to the new entry without losing progress.

### Steps to reproduce

1. Add the Asura Scans source.
2. Add any/all manga(s) to favourites.
3. Wait for a few days.
4. Open the favourite manga(s).

### Kotatsu version

5.3.4

### Android version

12

### Device

OnePlus 8T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ZBE69** [comment]
I've looked into it some more. Apparently the numeric prefix changes: [Latest](https://asura.gg/manga/0223090894-the-s-classes-that-i-raised) vs [Saved](https://asura.gg/manga/8978812094-the-s-classes-that-i-raised). The parser is otherwise working fine. I can search mangas and read mangas.

**Comment by ZBE69** [comment]
Are there any updates?

**Comment by Koitharu** [comment]
I have some ideas on how to solve such issues comprehensive however it needs some time, stay tuned)

**Comment by Koitharu** [comment]
I hope [this](https://github.com/KotatsuApp/Kotatsu/commit/97de27dfb32de81e9d609c705e072a7dea90c868) should helps

**Comment by ZBE69** [comment]
> I hope [this](https://github.com/KotatsuApp/Kotatsu/commit/97de27dfb32de81e9d609c705e072a7dea90c868) should helps

Thank you very much. I can confirm the commit successfully recovers the manga.

The last viewed chapter, however, isn't recovered. Clicking "Continue" causes the "The chapter is missing" error to pop up. I see Kotatsu stores the chapter ID so I imagine fixing this new issue would require a overhaul. Let me know if I should close this issue if it's too complicated to address.

**Comment by Koitharu** [comment]
Thank you for this tip, probably [fixed](https://github.com/KotatsuApp/Kotatsu/commit/2949fdd2c6c87ea38d02cf32ee7e8d9c9459c39d)

**Comment by ZBE69** [comment]
🎉🥳🎉

The history issue is indeed fixed with the aforementioned commit! Thank you again.

There is still a minor bug in recovering the history. Essentially, the recovered chapter is sometimes ahead of the actual last read chapter since [the commit assumes that the total chapter count remains unchanged](https://github.com/KotatsuApp/Kotatsu/blob/2949fdd2c6c87ea38d02cf32ee7e8d9c9459c39d/app/src/main/kotlin/org/koitharu/kotatsu/history/data/HistoryRepository.kt#L188C4-L188C29).

Consider the following scenario:
- There were 100 chapters.
- The last read chapter was 98.
- Chapters 101 - 104 came out and the history broke.

Now here the recovered chapter would be 0.98 (previous percentage) * 104 = 102.

I personally don't mind since this won't cause any issues in practice since the deviation would be very minor and can easily be corrected manually. Once again, thank you very much for the quick fix and prompt responses!

PS: I have attached [repro.zip](https://github.com/KotatsuApp/kotatsu-parsers/files/12239603/repro.zip) which contains a minimal set of manga that highlight the issue, in case you want to reproduce it. There are also some issues with the continue button restarting from chapter 1 but I consider them to be minor.

**Comment by Koitharu** [comment]
Yes, I know about this. The other way is to store the current chapter number instead of id (or in addition to id)
