### ISSUE TITLE
[Bug] Komikcast

### ISSUE THREAD

**Issue by MIRVOUS** [KotatsuApp/kotatsu-parsers#221]
### Source information

Komikcast

### Steps to reproduce

1. Kotatsu -> Browse
2. Komikcast -> pick any manga
3. Open chapter
4. All chapter name are the same
![Screenshot_2023-07-24-06-58-00-401_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/45929526/efc3ef2f-27ed-44fe-bd82-fa901395d9f2)

### Kotatsu version

5.3.8

### Android version

12

### Other details

Just it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
Need to close fixed on this commit 415da81
