### ISSUE TITLE
FrScan status=400

### ISSUE THREAD

**Issue by pixelroll** [KotatsuApp/kotatsu-parsers#231]
### Source information

FrScan

### Steps to reproduce

try to browse or read content from this source

### Kotatsu version

5.3.10

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
It's already been fixed, just wait for an update from kotatsu, in the meantime change role domain from .com to .cc
