### ISSUE TITLE
BirdToon 

### ISSUE THREAD

**Issue by kitsu2** [KotatsuApp/kotatsu-parsers#233]
### Source name

BirdToon 

### Source link

https://birdtoon.net/

### Language

Indonesia 

### Other details

Nsfw 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
the source is already added, we just have to wait for the pr to pass and kotatsu to be updated.
