### ISSUE TITLE
[Source Request] Manga Reader

### ISSUE THREAD

**Issue by Yuunop** [KotatsuApp/kotatsu-parsers#234]
### Source name

MangaReader

### Source link

https://mangareader.to/

### Language

Multi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by KraXen72** [comment]
bump!
