### ISSUE TITLE
TuMangaOnline

### ISSUE THREAD

**Issue by donaldh01** [KotatsuApp/kotatsu-parsers#236]
### Source information

TuMangaOnline

### Steps to reproduce

1. Open the Sources section and select "TuMangaOnline". 
2. open any manga 
3. and "java.security.cert.CertPathValidatorExcep tion: Trust anchor for certification path not found."" appears
![1692502072019](https://github.com/KotatsuApp/kotatsu-parsers/assets/117052315/38571ed7-12d3-4ea3-bf37-a34292cf76b4)

### Kotatsu version

5.3.10

### Android version

12

### Other details

I don't know if this influences anything but sometimes TMO uses other pages to show their mangas such as 
1. anitirion
2. recetasdelupita
"https://anitirion.com/news/5432b447cc4b5bab7c7f08d5f93ba675/cascade" o"https://recetasdelupita.com/news/43bfc6384175ecee5f075f8308906838/cascade"

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
Enabling igoner SSL errors in the settings for now solves the problem.

**Comment by donaldh01** [comment]
Done, The problem is still ongoing.
![1](https://github.com/KotatsuApp/kotatsu-parsers/assets/117052315/85003cea-cbd6-4bcc-89a3-3990cc0dcac2)

**Comment by davvarrr** [comment]
I don't know if it makes a difference but on 6.0 it works, you had a manga name or it doesn't work even with the ignore SSL error parameter activated. 
PS did you restart the App after activating the parameter?

**Comment by donaldh01** [comment]
Happens with all TMO mangas.
Yes, restart the app after making the changes

**Comment by donaldh01** [comment]
Do you recommend that I download v6.0?

**Comment by davvarrr** [comment]
If you want but 6.0 is in alpha so make a backup before the update

**Comment by donaldh01** [comment]
The v6.0 is the new version!, I didn't know it, I downloaded it on Fdroid and this version I downloaded.

**Comment by donaldh01** [comment]
I'm going to download it, let's see if the problem is solved.

**Comment by donaldh01** [comment]
It worked! thank you!
