### ISSUE TITLE
TuMangaOnline (TMO) RegExp error & Cert Validator error

### ISSUE THREAD

**Issue by QupLucca** [KotatsuApp/kotatsu-parsers#237]
### Source information

TuMangaOnline

### Steps to reproduce

When you try to read a +18 doujinshi a _Syntax error in regexp pattern near index 29 \{uniqid:'(.+)',cascade:(.+)}_ message alert is displayed
But when you try to read a non +18 manga, a `java.security.cert.CertPathValidatorException` is displayed
> See **Other details** for screenshots

### Kotatsu version

5.3.10

### Android version

Android 13

### Other details

![Screenshot_20230820-181734_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/132182849/d05be9af-e450-4e21-be77-01c261c791fc)
![IMG-20230819-WA0000](https://github.com/KotatsuApp/kotatsu-parsers/assets/132182849/8125e505-1943-4102-8979-4fff9a75a0c0)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
its fixed on 6.0 see -> #236 and #230
please do your research before publishing a bug report.
