### ISSUE TITLE
Uneble to reach source or its content

### ISSUE THREAD

**Issue by Nang7763** [KotatsuApp/kotatsu-parsers#244]
### Source information

Bentomanga.com

### Steps to reproduce

1. Open the "catpcha required" notification

Alternatively: open the source from the explore page

### Kotatsu version

6.0

### Android version

Android 10 GO

### Other details

From the notification, this appear:
![Screenshot_20230903-114333](https://github.com/KotatsuApp/kotatsu-parsers/assets/112281419/4c3e060e-82af-4a6d-8953-50d5cb3dc952)

From the explore page:
![Screenshot_20230903-114809](https://github.com/KotatsuApp/kotatsu-parsers/assets/112281419/c5613621-1ef4-47ea-ae51-13378fe3942c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
the source works, but sometimes there's a problem for me in the source settings I empty the cookies and relaunch the app and it works again.
