### ISSUE TITLE
ArabsHentai (Sourcerequest)

### ISSUE THREAD

**Issue by ghost** [KotatsuApp/kotatsu-parsers#249]
### Source name

ArabsHentai

### Source link

https://arabshentai.com

### Language

Arabic

### Other details

nsfw +18 yes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
all chapters are protected except for a link shortener, so it won't be possible to add it.
and i didn't go through with it, but if it's a download and not an online reader, it doesn't seem possible either.

**Comment by yemenihandsome** [comment]
> all chapters are protected except for a link shortener, so it won't be possible to add it.
> and i didn't go through with it, but if it's a download and not an online reader, it doesn't seem possible either. 

It is a continental application, but there are new chapters closed only every week, a new chapter comes down and closes, and the chapter for the previous week opens

**Comment by davvarrr** [comment]
This doesn't change the fact that if the chapters are last a shorten of links we won't be able to do anything.

**Comment by yemenihandsome** [comment]
Ok

**Comment by davvarrr** [comment]
source dead
