### ISSUE TITLE
Galaxy Action : Source request)

### ISSUE THREAD

**Issue by yemenihandsome** [KotatsuApp/kotatsu-parsers#254]
### Source name

Galaxy Action

### Source link

https://galaxyaction.site/

### Language

Arabic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Please do a research, the source is already in the pr
