### ISSUE TITLE
Ler mangá

### ISSUE THREAD

**Issue by SrCrono** [KotatsuApp/kotatsu-parsers#263]
### Source name

Ler mangá

### Source link

https://lermanga.org

### Language

Brazilian Portuguese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
added : https://github.com/KotatsuApp/kotatsu-parsers/commit/d8c32047d04c92f5a37cd6ef2a1475b78489da0c
