### ISSUE TITLE
how to learn node run

### ISSUE THREAD

**Issue by riship001** [KotatsuApp/kotatsu-parsers#275]
### Source information

run node

### Steps to reproduce

crypto run node 

### Kotatsu version

run node

### Android version

13

### Other details

tell me

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
node?

**Comment by ztimms73** [comment]
from the terminal I think, like cmd, PowerShell, bash or something else, then move to the path, where your `.js` file is located and type `node file.js`
