### ISSUE TITLE
One Piece Ex

### ISSUE THREAD

**Issue by SrCrono** [KotatsuApp/kotatsu-parsers#281]
### Source name

One Piece Ex

### Source link

https://onepieceex.net

### Language

Brazilian Portuguese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
added : https://github.com/KotatsuApp/kotatsu-parsers/commit/f5f2854f369bcb111baed3d70bb0240f1010ebe1
