### ISSUE TITLE
[Komikcast] Wrong navigation

### ISSUE THREAD

**Issue by MIRVOUS** [KotatsuApp/kotatsu-parsers#284]
### Source information

Komikcast

### Steps to reproduce

1. Explore -> komikcast
2. Sorting Order -> updated
3. 
![Screenshot_2023-10-09-15-44-21-129_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/45929526/5d511d87-ca8a-4cd6-bbe3-565881c85c50)

### Kotatsu version

6.1.6

### Android version

12

### Other details

It not an updated manga list
Please see the video below :

https://github.com/KotatsuApp/kotatsu-parsers/assets/45929526/4d22cc08-5c14-45fa-bdc6-a90642c2b7cd

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by MIRVOUS** [comment]
It happened again in v6.5

**Comment by davvarrr** [comment]
@MIRVOUS the source had changed the structure again it was fixed

**Comment by MIRVOUS** [comment]
This happened again in kotatsu version 9.1.1

I can't re-open the issues
