### ISSUE TITLE
Add the 32-bit color feature to Kotatsu.

### ISSUE THREAD

**Issue by Nebulavargas** [KotatsuApp/kotatsu-parsers#285]
### Describe your suggested feature

This setting decodes images in ARGB888 format to allow the reader to display more colors.
![cf351cfe0d7fe6352e2969b8296908eb](https://github.com/KotatsuApp/kotatsu-parsers/assets/146843923/6b87ba28-96e3-41e7-b2d8-0705225e2be6)
![AdobeRGBComparison](https://github.com/KotatsuApp/kotatsu-parsers/assets/146843923/55cccbc5-b9c7-4df3-a240-4048f840ed34)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
Added on 6.2
