### ISSUE TITLE
ParserTemplate for Madtheme

### ISSUE THREAD

**Issue by OshekharO** [KotatsuApp/kotatsu-parsers#29]
### Describe your suggested feature

Hii can you please make MangaParser for this theme https://toonily.me just like you made for madara theme.

### Other details

I can provide around 7 to 10 websites using same theme.

You may get some idea from: [MadTheme.kt](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/9e8cef623bb8607e0ad0005bfe9e6a0c0f093a06/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madtheme/MadTheme.kt) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/KotatsuApp/Kotatsu/issues/new/choose).
- [X] I have updated the app to version **[3.3.1](https://github.com/KotatsuApp/Kotatsu/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by davvarrr** [comment]
need to close issue the source its added : https://github.com/KotatsuApp/kotatsu-parsers/blob/6058221fecfe7343a8bf604a6976aeb3b3326809/src/main/kotlin/org/koitharu/kotatsu/parsers/site/madtheme/en/ToonilyMe.kt#L13
