### ISSUE TITLE
Tr Webtoon 

### ISSUE THREAD

**Issue by kitsuneashily** [KotatsuApp/kotatsu-parsers#291]
### Source name

Tr Webtoon

### Source link

https://trwebtoon.com/#

### Language

Turkish 

### Other details

18+/NSFW: YES 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Add with this commit https://github.com/KotatsuApp/kotatsu-parsers/commit/5e4dd82b8d5ceb371956bd7d20970112a7bb6840
