### ISSUE TITLE
[Site Request] comick

### ISSUE THREAD

**Issue by OshekharO** [KotatsuApp/kotatsu-parsers#30]
### Source name

comick

### Source link

https://comick.fun

### Language

Various

### Other details

comick is a website which has many new manga and has a big library.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have updated the app to version **[3.3.1](https://github.com/KotatsuApp/Kotatsu/releases/latest)**.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by ztimms73** [comment]
https://github.com/KotatsuApp/kotatsu-parsers/blob/master/src/main/kotlin/org/koitharu/kotatsu/parsers/site/ComickFunParser.kt
