### ISSUE TITLE
Galaxy Manga 

### ISSUE THREAD

**Issue by Jaj29** [KotatsuApp/kotatsu-parsers#303]
### Source name

Galaxy Manga 

### Source link

https://flixscans.com/webtoons/home

### Language

Arabic 

### Other details

It's not the same as Galaxy Manga Action it's for shoujo and it's sign is purple coloured 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Duplicate of #253
