### ISSUE TITLE
Yaoiflix: The order of the chapters is mixed up

### ISSUE THREAD

**Issue by hanabiyona** [KotatsuApp/kotatsu-parsers#309]
### Source information

Yaoiflix 

### Steps to reproduce

1. Add Yaoiflix source
2. Open any series in the source
3. it will be seen that the order of all the chapters of the series is mixed

### Kotatsu version

6.2

### Android version

Android 10

### Other details

The chapter order of all the series in the source is completely mixed up. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
fix with se commit : #76af0b0
