### ISSUE TITLE
MangaPark (English)

### ISSUE THREAD

**Issue by kyoyacchi** [KotatsuApp/kotatsu-parsers#312]
### Source name

MangaPark

### Source link

https://mangapark.net/

### Language

English

### Other details

18+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Added : https://github.com/KotatsuApp/kotatsu-parsers/commit/496b3388ee13323821bc11ee0f7c4be82f6b97c1
