### ISSUE TITLE
DoujinDesu source issue

### ISSUE THREAD

**Issue by kasfil** [KotatsuApp/kotatsu-parsers#314]
### Source information

DoujinDesu

### Steps to reproduce

1. add doujindesu [id] source
2. browse from doujindesu

### Kotatsu version

6.1.6

### Android version

13

### Other details

![Screenshot_2023-10-18-00-55-38-705_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/46927505/86a78e16-f34f-47df-bf60-daa08dcb42b5)
![Screenshot_2023-10-18-00-52-49-293_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/46927505/ba582465-c55c-4bb6-8466-7d402229b7e5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
On my side, it works fine, try to update the app and clear cookies from the source.

**Comment by kasfil** [comment]
Sorry for the mess, everything went very smoothly after removing the cookies. And thank you for the quick response.
I will close this issue.
