### ISSUE TITLE
Azora Nov is kinda slow

### ISSUE THREAD

**Issue by Jaj29** [KotatsuApp/kotatsu-parsers#316]
### Source information

Azora Nov

### Steps to reproduce

Everytime i open the source on the app ot sends me this message and  slowly works after many loadings
![Screenshot_2023-10-17-20-56-45-72_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/KotatsuApp/kotatsu-parsers/assets/144594100/9bf58c4a-c7a0-4942-b221-34e707db2066)
![Screenshot_2023-10-17-20-56-01-52_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/KotatsuApp/kotatsu-parsers/assets/144594100/420ec788-94b3-4eab-991a-df956e9c76ee)

### Kotatsu version

6.2

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
the source works, but the limitations are quoted on the source server, so nothing can be done on the app.
