### ISSUE TITLE
KingOfShojo :(Source request)

### ISSUE THREAD

**Issue by yemenihandsome** [KotatsuApp/kotatsu-parsers#318]
### Source name

KingOfShojo

### Source link

https://kingofshojo.com

### Language

Arabic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
The site is not working do you have any information?

**Comment by yemenihandsome** [comment]
> The site is not working do you have any information?

لThey have purchased OzulScans Al Arabi so far. They have activated the link instead of OzulShijo. It will arrive in the next few days.

**Comment by yemenihandsome** [comment]
@davvarrr He's working at the moment.

**Comment by davvarrr** [comment]
add with this commit : [#32afa26](https://github.com/KotatsuApp/kotatsu-parsers/commit/32afa26be5726edf6d1ff095035fb336af351cbf)
