### ISSUE TITLE
MangaLife

### ISSUE THREAD

**Issue by SrCrono** [KotatsuApp/kotatsu-parsers#322]
### Source name

MangaLife

### Source link

https://www.manga4life.com/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Already present : https://github.com/KotatsuApp/kotatsu-parsers/blob/87032a6835787d37dea37ca5a520a2a278aceab3/src/main/kotlin/org/koitharu/kotatsu/parsers/site/nepnep/en/Manga4Life.kt#L7
Please search carefully before posting a request
