### ISSUE TITLE
Mangakakalot.tv

### ISSUE THREAD

**Issue by SrCrono** [KotatsuApp/kotatsu-parsers#324]
### Source name

Mangakakalot.tv (unoriginal)

### Source link

https://ww6.mangakakalot.tv/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Add with this commit : [#23cc86e](https://github.com/KotatsuApp/kotatsu-parsers/commit/23cc86e429d37c217af0eb53345f76f8376e6774)
