### ISSUE TITLE
Mangá Nanquim

### ISSUE THREAD

**Issue by SrCrono** [KotatsuApp/kotatsu-parsers#330]
### Source name

Mangá Nanquim

### Source link

https://mangananquim.com

### Language

Brazilian Portuguese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Added with this commit https://github.com/KotatsuApp/kotatsu-parsers/commit/bdb7fbc03981d5a6dd63ddbc3d885f26bf79d8ed
