### ISSUE TITLE
[SoulScans] Can't load more

### ISSUE THREAD

**Issue by MIRVOUS** [KotatsuApp/kotatsu-parsers#333]
### Source information

SoulScans 

### Steps to reproduce

1. Explore -> SoulScans
2. "Updated" (setting order)
3. Manga can't load more
 
![Screenshot_2023-10-26-10-43-00-733_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/45929526/e4dcb4a7-736e-4709-9e5b-4e2fe7d332c7)

### Kotatsu version

6.2.3 

### Android version

Android 12

### Other details

Note :
After updated to new version many(maybe all) 'sources' have similar problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
It works for me  
![Uploading Screenshot_20231026-080113.png…]()

**Comment by davvarrr** [comment]
Fixed on 6.2.4
