### ISSUE TITLE
[MgKomik] Bug

### ISSUE THREAD

**Issue by MIRVOUS** [KotatsuApp/kotatsu-parsers#335]
### Source information

MgKomik 

### Steps to reproduce

1. Explore -> MgKomik 
2. Captcha required (solve)
![Screenshot_2023-10-26-13-19-52-049_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/45929526/688ae76c-49a8-40eb-9076-ff07eb590db7)
3. You have been blocked
![Screenshot_2023-10-26-13-19-57-695_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/45929526/fbf9b782-4b93-4593-916f-0496f2d804ce)

### Kotatsu version

6.2.3 

### Android version

Android 12

### Other details

I opened the website using Browser.
And it doesn't need Captcha.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
fix on https://github.com/KotatsuApp/kotatsu-parsers/commit/97a8bb1ca7c77e434d13ba4250022b9ca9ba5229
