### ISSUE TITLE
SlimeRead (Portuguese Source)

### ISSUE THREAD

**Issue by deividgabrielpeira** [KotatsuApp/kotatsu-parsers#337]
### Source name

SlimeRead

### Source link

https://slimeread.com/

### Language

Brazilian Portuguese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Duplicate of https://github.com/KotatsuApp/kotatsu-parsers/issues/326
