### ISSUE TITLE
Mundo hentai

### ISSUE THREAD

**Issue by ALSHSK** [KotatsuApp/kotatsu-parsers#339]
### Source name

Mundohentai 

### Source link

https://mundohentaioficial.com

### Language

Portuguese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Added on : https://github.com/KotatsuApp/kotatsu-parsers/commit/a5219ceb6c8e228db99748e97a8634b1ba55e6d1
