### ISSUE TITLE
Manhwas Men 

### ISSUE THREAD

**Issue by ALSHSK** [KotatsuApp/kotatsu-parsers#341]
### Source name

Manhwas Men

### Source link

https://manhwas.men

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Add with this commit https://github.com/KotatsuApp/kotatsu-parsers/commit/5e4dd82b8d5ceb371956bd7d20970112a7bb6840#diff-708b0b4ef98e923dd04daa9b6c98786566482729be5b4292b982fb318708a94e
