### ISSUE TITLE
Elevenscanlator

### ISSUE THREAD

**Issue by ALSHSK** [KotatsuApp/kotatsu-parsers#343]
### Source name

Elevenscanlator

### Source link

https://elevenscanlator.blogspot.com

### Language

Portuguese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by deividgabrielpeira** [comment]
Close The issues: #413
