### ISSUE TITLE
Hikari scan new domain

### ISSUE THREAD

**Issue by Tomo-kun** [KotatsuApp/kotatsu-parsers#345]
### Source information

Hikari scan

### Steps to reproduce

Open the hikariscan extension

### Kotatsu version

6.2.4

### Android version

Android 13

### Other details

https://hikariscan.org/

Hikariscan changed domains to avoid dmca

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
added on https://github.com/KotatsuApp/kotatsu-parsers/commit/508647eb5a3d1db5d1f2fbfb60dde539749996a5
