### ISSUE TITLE
crystalscan (Portuguese Source)

### ISSUE THREAD

**Issue by deividgabrielpeira** [KotatsuApp/kotatsu-parsers#348]
### Source name

crystalscan

### Source link

https://crystalscan.net/

### Language

Brazilian Portuguese 

### Other details

Madara Thema

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Add with this commit : https://github.com/KotatsuApp/kotatsu-parsers/commit/66d47bf579674dc0e75353641874624f8f91c20e
