### ISSUE TITLE
Unable to view manga from comick

### ISSUE THREAD

**Issue by Anupam-Ashish-Minz** [KotatsuApp/kotatsu-parsers#350]
### Source information

ComicK

### Steps to reproduce

Open any manga from Comick source.
No chapters are visible or can be continued. 

![image](https://github.com/KotatsuApp/kotatsu-parsers/assets/46285489/a3cbea2f-36a6-413c-968b-7b07e77d749c)

### Kotatsu version

6.2.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Update your app

**Comment by EncryptedCicada** [comment]
This issue is still present in Kotatsu v6.2.4
