### ISSUE TITLE
MangaSee search issues

### ISSUE THREAD

**Issue by rhynec** [KotatsuApp/kotatsu-parsers#352]
### Source information

MangaSee

### Steps to reproduce

1. Open search in the MangaSee menu
2. Look up any manga with a space in the middle
3. Search will fail (one word searches do work)

### Kotatsu version

v6.2.4

### Android version

Android 14

### Other details

Additionally, you are only able to look for the "official" name assigned to the manga in the website (the one in the URL). For example, searching for "Attack" will not bring up "Attack on Titan", but searching for "Shingeki" will pull it up as "Shingeki no Kyojin". On the website, you are able to search for both the English and Japanese (typically labelled alternative) title.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
fixed with this commit https://github.com/KotatsuApp/kotatsu-parsers/commit/e9d473711d8ad277d22a401a7d694c777eaf2ba8
