### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by Clearoad** [KotatsuApp/kotatsu-parsers#356]
### Source information

NeoxScans

### Steps to reproduce

1.try to connect with this origin or the manga coming from it.
2.wait a few seconds.
3.you will get network error as response

### Kotatsu version

6.2.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
the source works, but their server is unstable and may not respond. And having an ip in Brazil helps for this source.
![a](https://github.com/KotatsuApp/kotatsu-parsers/assets/70220050/1194154f-42ce-4892-a6fc-5981006e3f9d)
