### ISSUE TITLE
Adding sorting via a language

### ISSUE THREAD

**Issue by davvarrr** [KotatsuApp/kotatsu-parsers#357]
### Describe your suggested feature

I think that adding sorting via a language would be relevant. I've made a prototype by adding "tags" in the recently added parser ( https://github.com/KotatsuApp/kotatsu-parsers/commit/e788cff04a41d4d0f496e2ff64a397e621ea73fc ) , but ideally we'd need a separate section to better manage this sorting.
This kind of addition could be applied to others like manga dex, which would be a big plus for searching for manga translated into the desired language.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Do you mean adding new section "language" to filter?
Like "Sort order", "Language" and "Genres" (aka tags), right?

**Comment by davvarrr** [comment]
yes, in this style, to be able to manage languages independently.

**Comment by davvarrr** [comment]
@Koitharu I don't know if you're planning to add this feature, but in the same vein, you could also add statu share sorting.
all sources on the mangareader template are compatible with a sort of this kind, so after adding this one, we'll be able to make a lot of sources compatible at once

**Comment by Koitharu** [comment]
@davvarrr how do you think, is it worth to add possibility to select multiple languages or just one? (I mean multiple like tags or single like sort order in current implementation).

And also I didn`t catch what do you mean by
> add statu share sorting

**Comment by davvarrr** [comment]
Few people and few sites do multilingual sorting (I only know mengadex at the moment), so if there's only a single-language selection, it's not a problem.

**Comment by davvarrr** [comment]
For "add statu share sorting" its : Sorting by ongonig , canceled , paused and finished

**Comment by davvarrr** [comment]
I've added an example on madara if that helps. : https://github.com/KotatsuApp/kotatsu-parsers/blob/6f73ff23e874759a8c955ab06f39cf207a26492b/src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/MadaraParser.kt#L174C2-L174C2

**Comment by Koitharu** [comment]
@davvarrr can you please take a look on #387 ?

**Comment by davvarrr** [comment]
Thanks for the addition ;)
I'll just need an example for languages and status so I can better understand how to implement them on compatible sources :)

**Comment by Koitharu** [comment]
@davvarrr I plan to make a new release, can I merge branch `filter` into `master`?

**Comment by davvarrr** [comment]
And had you planned the language filter in a little while to know if I could add it on weekends?

**Comment by Koitharu** [comment]
Yes, language filter will be implemented soon, and it would be nice to have at least one source with it before

**Comment by davvarrr** [comment]
You had the parser Gallet adults which has a prototype of language filter but the best is to test on mangadex it is quite simple to set up.

**Comment by davvarrr** [comment]
@Koitharu I changed "originalLanguage" share "availableTranslatedLanguage" which is more relevant for a manga search. 
Thanks for the examples, I'll look at them later this week or this weekend and add them to the sources that support it.
