### ISSUE TITLE
Olympus Scanlation ( Espanhol and Portuguese Source)

### ISSUE THREAD

**Issue by deividgabrielpeira** [KotatsuApp/kotatsu-parsers#358]
### Source name

Olympus Scanlation

### Source link

https://olympusv2.gg/

### Language

Espanhol and Portuguese

### Other details

This site has 2 languages: Portuguese and Spanish, in which case you would have to make an identification or tags.

https://prnt.sc/nYFjo8kQznoL

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
#823
