### ISSUE TITLE
Japscan

### ISSUE THREAD

**Issue by Gabinou22s** [KotatsuApp/kotatsu-parsers#359]
### Source name

Japscan 

### Source link

https://www.japscan.lol/

### Language

French

### Other details

Plus complet en manga

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
We did not add this source because of the difficulty in maintaining it (it was already present before and every 2 days the source will no longer work because the admin changes its code).
https://github.com/KotatsuApp/kotatsu-parsers/issues/39
