### ISSUE TITLE
Kakusei Project (Portuguese Source)

### ISSUE THREAD

**Issue by deividgabrielpeira** [KotatsuApp/kotatsu-parsers#362]
### Source name

Kakusei Project

### Source link

http://kakuseiproject.com.br/

### Language

Brazilian Portuguese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
the source demanded is already present  : https://github.com/KotatsuApp/kotatsu-parsers/blob/5e4dd82b8d5ceb371956bd7d20970112a7bb6840/src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/pt/KakuseiProject.kt#L7
