### ISSUE TITLE
no value for genres

### ISSUE THREAD

**Issue by CyberDenner** [KotatsuApp/kotatsu-parsers#366]
### Source information

ComicK

### Steps to reproduce

Go and choose any manga from Comick

![print](https://github.com/KotatsuApp/kotatsu-parsers/assets/146398551/29c8ad5c-e201-4149-9176-8bcad096b134)

### Kotatsu version

6.2.4

### Android version

Android 13

### Other details

Every manga displays the message "no value for genres"

I can read mangas normally through the browser.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Update your app
