### ISSUE TITLE
Sources didn't work when I tried to do "captcha"

### ISSUE THREAD

**Issue by Death415** [KotatsuApp/kotatsu-parsers#367]
### Source information

Mangalek.net and Mangaleku

### Steps to reproduce

![Screenshot_2023-11-09-01-56-36-12_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/KotatsuApp/kotatsu-parsers/assets/61976889/aa7f88ab-1c00-488c-b4a2-4e6d382a9898)
![IMG_20231109_020306](https://github.com/KotatsuApp/kotatsu-parsers/assets/61976889/703fc94c-5fe8-4310-ba07-4ec2cd09b3e6)
![IMG_20231109_020317](https://github.com/KotatsuApp/kotatsu-parsers/assets/61976889/ed980f1b-066d-43a7-b8c6-110783c0730c)
Every time I try to finish it, it comes back and asks me to do it again (loop)

### Kotatsu version

6.2.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
the 2 sources work well and the captchas pass.
Try clearing the source cookies and retrying a captcha.

**Comment by blackcatad** [comment]
create a backup and delete the data of kotatsu and then restore from backup
it will work
