### ISSUE TITLE
VexManga : Source url changed

### ISSUE THREAD

**Issue by yemenihandsome** [KotatsuApp/kotatsu-parsers#370]
### Source name

VexManga

### Source link

https://vexmanga.com

### Language

Arabic

### Other details

The old link no longer works, the source link has been changed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by ztimms73** [comment]
just change url in source settings

**Comment by davvarrr** [comment]
the url was changed with this commit https://github.com/KotatsuApp/kotatsu-parsers/commit/d3afdad95baa55a5f610dca28427898c862fe6c7
