### ISSUE TITLE
Luna Scans

### ISSUE THREAD

**Issue by amberglowy** [KotatsuApp/kotatsu-parsers#373]
### Source name

Luna Scans 

### Source link

https://lunascans.fun/

### Language

Turkish

### Other details

18+/Nsfw: yes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
add with this commit https://github.com/KotatsuApp/kotatsu-parsers/commit/d3afdad95baa55a5f610dca28427898c862fe6c7
