### ISSUE TITLE
G Manga

### ISSUE THREAD

**Issue by blackcatad** [KotatsuApp/kotatsu-parsers#376]
### Source name

G Manga

### Source link

https://gmanga.org/

### Language

arabic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Duplicate of #247
