### ISSUE TITLE
Tr Webtoon: Add "update" option to the source

### ISSUE THREAD

**Issue by Anokyai** [KotatsuApp/kotatsu-parsers#382]
### Describe your suggested feature

The Tr Webtoon source has only "name" and "popular" options. Can you add an "update" option to the source like in other sources. 

Tr Webtoon:
![IMG_20231115_211342](https://github.com/KotatsuApp/kotatsu-parsers/assets/146554683/f7d7fd17-311e-4b4b-856c-06c7db632b2e)

Other Sources: 
![IMG_20231115_211401](https://github.com/KotatsuApp/kotatsu-parsers/assets/146554683/425e0d9c-296d-4d69-a9ad-f6f7606618f6)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
it was added with this commit https://github.com/KotatsuApp/kotatsu-parsers/commit/98f5d115b30cd428bb9c67e9cfff945159cb6036, but doesn't work with tags or a search that will put a view on the most viewed.
