### ISSUE TITLE
Unable to sort mangas by popularity 

### ISSUE THREAD

**Issue by Mtkmanjaro** [KotatsuApp/kotatsu-parsers#389]
### Source information

Nhentai.net

### Steps to reproduce

Open nhentai try to change the sort mode, the only option available is update, the same happen if you select a specific tag example (milf)  this is weird because two days ago both options were available, update and popularity but the popularity suddenly disappeared 

![Screenshot_2023-11-18-19-44-50-317_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/64289536/7eb93d38-e3ad-46ae-a4f6-787504554236)

### Kotatsu version

6.3.0

### Android version

12

### Other details

I did additional testing and go to nhentai in the web browser, all sort modes are working well so I think this is app side issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
the popular section only worked if you chose a tag, the source doesn't offer a popular list without an option (tag, search) as for the default search, the app updated me, so there too, it doesn't choose popular.

I can put it back if you want, but please be assured that it will only work after you've chosen a tag.

**Comment by kyoyacchi** [comment]
Does it work tho?

**Comment by davvarrr** [comment]
It's been added with this commit https://github.com/KotatsuApp/kotatsu-parsers/commit/410c73a74f2226f8003d962bedf441ecfa6b16b8 ,  but keep in mind that without a filter (tag or search) the popularity order does nothing and returns the most recent list.
