### ISSUE TITLE
Webtoons.com

### ISSUE THREAD

**Issue by Fuzzythegoatq** [KotatsuApp/kotatsu-parsers#395]
### Source name

Webtoon/Translate Webtoon

### Source link

https://m.webtoons.com/en/   https://translate.webtoons.com/

### Language

English

### Other details

Best Source For Comics And Manhwa Everywhere!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by Rabcor** [comment]
Yeah second this, was trying to find some stuff from this on LineWebtoon, then I discovered it wasn't actually the same (I mean it is the same, just not quite the same content)

**Comment by davvarrr** [comment]
https://github.com/KotatsuApp/kotatsu-parsers/blob/dceedf019a5df8db3e00a10c342a0e1792f06d07/src/main/kotlin/org/koitharu/kotatsu/parsers/site/all/WebtoonsParser.kt#L61
