### ISSUE TITLE
komiktap 

### ISSUE THREAD

**Issue by ghost** [KotatsuApp/kotatsu-parsers#40]
### Source name

komiktap 

### Source link

http://194.233.66.232/

### Language

Indonesian

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by alpqm** [comment]
https://komiktap.me

**Comment by alpqm** [comment]
https://komiktap.in

**Comment by alpqm** [comment]
@Koitharu Will this be added

**Comment by alpqm** [comment]
> @Koitharu Will this be added 🙏

And sorry to be tagged

**Comment by Koitharu** [comment]
These domains are redirect to the ip address(

**Comment by alpqm** [comment]
> Domain ini dialihkan ke alamat ip (

Is it not possible to add via ip address

**Comment by Koitharu** [comment]
Yes, but no, because of issues with SSL

**Comment by alpqm** [comment]
> Ya, tapi tidak, karena ada masalah dengan SSL

Add manhwaid extension bro

**Comment by alpqm** [comment]
> > Ya, tapi tidak, karena ada masalah dengan SSL
> 
> Tambahkan ekstensi manhwaid gan



> Ya, tapi tidak, karena ada masalah dengan SSL

Is it possible that mangasusu can't be added

**Comment by alpqm** [comment]
> Yes, but no, because of issues with SSL

Can the owner of the Komiktap website request the extension to be removed ?

**Comment by alpqm** [comment]
> Yes, but no, because of issues with SSL

are you still working on it

**Comment by alpqm** [comment]
> These domains are redirecting to the ip address(

can't add it yet?

**Comment by alpqm** [comment]
> Yes, but no, because of issues with SSL

when was the extension added?

**Comment by alpqm** [comment]
> > Yes, but no, because of issues with SSL
> 
> when was the extension added?

are you busy
