### ISSUE TITLE
Iris scanlator português 

### ISSUE THREAD

**Issue by deividgabrielpeira** [KotatsuApp/kotatsu-parsers#403]
### Source name

irisScanlator

### Source link

https://irisscanlator.com.br/

### Language

Português 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
added : https://github.com/KotatsuApp/kotatsu-parsers/commit/97338f31c576ae527aab19c0d8eb8d1c96cee9bf
