### ISSUE TITLE
FlixScans.org

### ISSUE THREAD

**Issue by yemenihandsome** [KotatsuApp/kotatsu-parsers#411]
### Source information

FlixScans.org

### Steps to reproduce

The source is in English, not Arabic. We hope to correct it

### Kotatsu version

i.4

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
fixed on https://github.com/KotatsuApp/kotatsu-parsers/commit/4d02dc0d12e61052ca8315bcb50aef61e229d97a
