### ISSUE TITLE
Franxx Mangas

### ISSUE THREAD

**Issue by deividgabrielpeira** [KotatsuApp/kotatsu-parsers#415]
### Source name

Franxx Mangas

### Source link

https://franxxmangas.net/

### Language

português 

### Other details

Thema: ZeistMangaParser

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Already present  https://github.com/KotatsuApp/kotatsu-parsers/blob/42ecf8a958f00563ce05f2b89b019f50e081d32a/src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/pt/FranxxMangas.kt#L11
