### ISSUE TITLE
Heck Scans Portugues

### ISSUE THREAD

**Issue by deividgabrielpeira** [KotatsuApp/kotatsu-parsers#416]
### Source name

Heck Scans

### Source link

https://heckscans.blogspot.com/

### Language

português 

### Other details

thema: ZeistMangaParser

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
added : https://github.com/KotatsuApp/kotatsu-parsers/commit/0208f5be97e52c526129350dd81e738532cde3ea
