### ISSUE TITLE
Jiangzaitoon: Chapters are not displayed.

### ISSUE THREAD

**Issue by mokhwayona** [KotatsuApp/kotatsu-parsers#417]
### Source information

Jiangzaitoon (Turkish)

### Steps to reproduce

1.Open the manga you want to read in the source.
2. Not showing any chapters from the manga.
3. it says; An error has occurred.

### Kotatsu version

6.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
Fixed with this commit : https://github.com/KotatsuApp/kotatsu-parsers/commit/eeafb3c6fd4fe5565435145e7efaa4447f376ae1
