### ISSUE TITLE
Olaoe

### ISSUE THREAD

**Issue by yemenihandsome** [KotatsuApp/kotatsu-parsers#427]
### Source name

Olaoe

### Source link

https://olaoe.cyou/

### Language

Arabic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
added https://github.com/KotatsuApp/kotatsu-parsers/commit/edc07b5dbd64526edd6cac194cbc23e3a85243dc
