### ISSUE TITLE
New Sourcs: ScanIta

### ISSUE THREAD

**Issue by o0Abaddon0o** [KotatsuApp/kotatsu-parsers#430]
### Source name

ScanIta

### Source link

https://scanita.org

### Language

Italian

### Other details

Manga source

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
added on https://github.com/KotatsuApp/kotatsu-parsers/compare/904e0719ebac...b2f0eaccc41d
