### ISSUE TITLE
Lunar Scan

### ISSUE THREAD

**Issue by Carlota-gif** [KotatsuApp/kotatsu-parsers#435]
### Source name

Lunar Scan

### Source link

https://lunarscan.com.br/

### Language

Brazilian Portuguese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Added https://github.com/KotatsuApp/kotatsu-parsers/commit/704f589b6d8cf8797b5241efeb954e1d1a80b941
