### ISSUE TITLE
Phoenix Scans (Italian Source)

### ISSUE THREAD

**Issue by HondaTooru97** [KotatsuApp/kotatsu-parsers#437]
### Source name

Phoenix Scans

### Source link

https://www.phoenixscans.com/

### Language

Italian

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
added on https://github.com/KotatsuApp/kotatsu-parsers/commit/6dc0e12fb0631bd90a1a7781dfaf6a365814cc0b
