### ISSUE TITLE
Sussy Scan - português 

### ISSUE THREAD

**Issue by deividgabrielpeira** [KotatsuApp/kotatsu-parsers#444]
### Source name

SussyScan

### Source link

https://sussyscan.com/

### Language

Português 

### Other details

Madara thema 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
added : https://github.com/KotatsuApp/kotatsu-parsers/commit/6ad08f13d43296c2d653922ddfa9d2a857ff02bb
