### ISSUE TITLE
New Source:  Elarc Toon

### ISSUE THREAD

**Issue by ChaosReader007** [KotatsuApp/kotatsu-parsers#450]
### Source name

Elarc Toon

### Source link

https://elarctoon.com/

### Language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
https://github.com/KotatsuApp/kotatsu-parsers/blob/8b9c76fca5afd9c7eec6871429412e96ed264aac/src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/en/Elarcpage.kt#L10
