### ISSUE TITLE
Mode scan

### ISSUE THREAD

**Issue by Mynameluis** [KotatsuApp/kotatsu-parsers#451]
### Source name

Mode Scan 

### Source link

https://modescanlator.com/

### Language

PT BR

### Other details

18+// NO

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Duplicate of #308
