### ISSUE TITLE
Tao sect

### ISSUE THREAD

**Issue by Mynameluis** [KotatsuApp/kotatsu-parsers#452]
### Source name

Tao sect português Brazil 

### Source link

https://taosect.com/

### Language

Português Brazil 

### Other details

18+// YES

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Duplicate of #289
