### ISSUE TITLE
Manhwas.net

### ISSUE THREAD

**Issue by isaacpsx** [KotatsuApp/kotatsu-parsers#459]
### Source name

Manhwas.net

### Source link

https://manhwas.net/

### Language

spanish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Duplicate of #344

**Comment by isaacpsx** [comment]
Sorry about that i Hope that my other sources are compatibles
