### ISSUE TITLE
Issue with ScanIta.org

### ISSUE THREAD

**Issue by alan-ford** [KotatsuApp/kotatsu-parsers#463]
### Source information

ScanIta.org

### Steps to reproduce

1. Tap on ScanIta.org
2. Search for any manga and see the error "Search is not supported by this manga source"
3. Open any manga and it will only display the last 20 chapters

### Kotatsu version

6.6.2

### Android version

Android 7.1.2

### Other details

The extension does not support searching and shows only the last 20 chapters of each manga.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
Fixed in https://github.com/KotatsuApp/kotatsu-parsers/commit/11c1eafa0dd815e8e7df148db71639903e2fb542#diff-5603b4f36d03ab8552302bfda068cb13e8837343dd24cd3c1e409c2ca6a14bd1
