### ISSUE TITLE
Mangá Hentai - Portugues (+18)

### ISSUE THREAD

**Issue by deividgabrielpeira** [KotatsuApp/kotatsu-parsers#473]
### Source name

Mangá Hentai 

### Source link

https://mundohentaioficial.com/category/manga-hentai/

### Language

português 

### Other details

+18

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
https://github.com/KotatsuApp/kotatsu-parsers/blob/52e4e6b80223eb6b1dc7eff8afda35b38bf6a128/src/main/kotlin/org/koitharu/kotatsu/parsers/site/gattsu/pt/MundoHentaiOficial.kt#L19
