### ISSUE TITLE
MangaOwl Changed Their Domain

### ISSUE THREAD

**Issue by AetheralMeowstic** [KotatsuApp/kotatsu-parsers#48]
### Source name

MangaOwl

### Source link

https://mangaowl.to/manga

### Language

English

### Other details

MangaOwl changed their domain recently, so please update MangaOwl in the app to reflect it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by ztimms73** [comment]
This is unoriginal MangaOwl.
https://www.reddit.com/r/manga/comments/vhqzep/manga_owl_has_been_shut_down_permanently/ and check issue #39
