### ISSUE TITLE
Norte Rose Scan - Portugues

### ISSUE THREAD

**Issue by deividgabrielpeira** [KotatsuApp/kotatsu-parsers#483]
### Source name

Norte Rose Scan

### Source link

https://norterose.com.br/

### Language

Portugues

### Other details

madara thema

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by ztimms73** [comment]
![image](https://github.com/KotatsuApp/kotatsu-parsers/assets/61558546/e15b439a-aaac-4bd5-87f6-615e31f0fd33)
huh

**Comment by deividgabrielpeira** [comment]
> ![image](https://private-user-images.githubusercontent.com/61558546/296617167-e15b439a-aaac-4bd5-87f6-615e31f0fd33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNzEyMDMsIm5iZiI6MTcwNTI3MDkwMywicGF0aCI6Ii82MTU1ODU0Ni8yOTY2MTcxNjctZTE1YjQzOWEtYWFhYy00YmQ1LTg3ZjYtNjE1ZTMxZjBmZDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDIyMjE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNTc2YjE2YmI5MDdkZjRiYWU0MGViN2YwNGIwNTNkMDM2NDRmODdmMGFiYWY1YzYwYWJmODEyZWFmODEwOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y-aTlBPtC_gsyaFeOTdh6hlTCjpJBEhfI6V3lwor4mA) huh

Note: vpn required :-:, they're still blocking it.
