### ISSUE TITLE
 Trust anchor for certification path not found

### ISSUE THREAD

**Issue by AnibalDams** [KotatsuApp/kotatsu-parsers#486]
### Source information

Tumangaonline

### Steps to reproduce

1. Open the app
2. Search a manga using the Spanish source "Tumangaonline"
3. Open the manga
4. Finally, open a chapter of that manga

### Kotatsu version

6.6.3

### Android version

Android 8.1 go edition

### Other details

I've tried with other sources like comick and ninemanga and this problem doesn't happen

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
https://github.com/KotatsuApp/kotatsu-parsers/issues/236
