### ISSUE TITLE
Mangago

### ISSUE THREAD

**Issue by Delmarcop52** [KotatsuApp/kotatsu-parsers#488]
### Source name

Mangago

### Source link

https://www.mangago.me

### Language

English 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Duplicate of #205

**Comment by lilmushoo** [comment]
Source doesn't show up for me

**Comment by mai2367** [comment]
can't find the source!
