### ISSUE TITLE
Yes mangás

### ISSUE THREAD

**Issue by Orionv1** [KotatsuApp/kotatsu-parsers#49]
### Source name

yesmangas

### Source link

https://yesmangas1.com/

### Language

Portuguese

### Other details

Fast and complete manga/manhwas extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Source Dead
