### ISSUE TITLE
Mangakakalot crashing

### ISSUE THREAD

**Issue by Imiasama** [KotatsuApp/kotatsu-parsers#490]
### Source information

Mangakakalot.com

### Steps to reproduce

1.choose any manga
2. Press find similar button
3. Mangakakalot shows that the search failed
![Screenshot_20240116_170405_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/153512314/1bbf0069-bc11-4b56-9508-6a89cd11b540)

### Kotatsu version

6.6.3

### Android version

Android 12

### Other details

This only happens with this source I have other sources that seem to work perfectly fine. A similar issue also happens when I try to search for manga in the source itself, for some entries the search shows that it failed while some entries show results just fine.
![Screenshot_20240116_170526_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/153512314/7ac46825-71f9-41c4-b2ea-6d8a5a1e2093)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by AColtZz** [comment]
Running into the same issue still, seems to occur only when having multiple words.
One word searches do work for "Mangakakalot.com"

Android 14.0
Samsung Galaxy S21+
Kotatsu version 6.6.6
