### ISSUE TITLE
Missing multiple comics

### ISSUE THREAD

**Issue by Rabcor** [KotatsuApp/kotatsu-parsers#506]
### Source information

ReadComicsOnline

### Steps to reproduce

1. Search for comic: [Suicide Squad (2011) ](https://readcomiconline.li/Comic/Suicide-Squad)
2. Fail to find it.
3. Cry

### Kotatsu version

6.6.2

### Android version

Android 14 (GrapheneOS)

### Other details

Even if you just go on the site and search for Suicide Squad, you will find about twice as many results as you would see in kotatsu so there's definitely something quite wrong here.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Pempo01** [comment]
This! Please adress this! Comic readers really don't have other good options!

**Comment by davvarrr** [comment]
You're looking for manga from "readcomiconline.li" on a source whose url is "readcomicsonline.ru". 
No wonder you can't find them.

**Comment by Rabcor** [comment]
> You're looking for manga from "readcomiconline.li" on a source whose url is "readcomicsonline.ru". No wonder you can't find them.

Then maybe the app should specify that instead of just saying it's readcomicsonline and leaving it at that?
