### ISSUE TITLE
NHentai.com - Cannot find first chapter

### ISSUE THREAD

**Issue by aminoginji** [KotatsuApp/kotatsu-parsers#511]
### Source information

NHentai.net

### Steps to reproduce

1. Open NHentai.net
2. Click any title
3. click read
4. Error - Cannot Find first chapter

If you expand the title you can select the chapter or hit read and it will work

### Kotatsu version

6.6.5

### Android version

Android 10

### Other details

![image](https://github.com/KotatsuApp/kotatsu-parsers/assets/1223153/3c8a71c3-d6e5-44d4-8c79-bfb6242dd4b0)
![image](https://github.com/KotatsuApp/kotatsu-parsers/assets/1223153/b1c72aab-f00f-450a-aa6b-24628da2e628)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
The source works, update your app.
