### ISSUE TITLE
Problem with chapter order in MangaLib parser

### ISSUE THREAD

**Issue by Madaraki-chan** [KotatsuApp/kotatsu-parsers#514]
### Source information

MangaLib

### Steps to reproduce

1. Use the parser to open any title (e.g. https://mangalib.me/houseki-no-kuni ).
2. Try to download it.
3. Chapters whose numbers have decimal digits (e.g. 28.5, 36.5, 44.5) will be labeled by the app itself as chapter 0, which will cause them to appear before all other chapters when downloaded, breaking the sequence. 

### Kotatsu version

6.6.5

### Android version

9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Fixed in a8f9423307965dccc75f7046af8c8e3e10ba0e76
