### ISSUE TITLE
Chapter names not showing up in Reset Scans

### ISSUE THREAD

**Issue by VektorOO7** [KotatsuApp/kotatsu-parsers#518]
### Source information

ResetScans

### Steps to reproduce

If you open any manga, manhwa or manhua when you look at the chapters list the name of the chapter is missing (I found this bug with the manhua "Library Of Heaven's Path" but I checked a few others and they had the same issue).

### Kotatsu version

6.6.6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
![image](https://github.com/user-attachments/assets/f48c24b6-8151-458e-8594-9baf434d217d)
