### ISSUE TITLE
Manhastro extension bug

### ISSUE THREAD

**Issue by fallowzp** [KotatsuApp/kotatsu-parsers#526]
Uploading WhatsApp Video 2024-02-09 at 15.44.19.mp4…

### Source information

Manhastro

### Steps to reproduce

All mangas and manhwas in the "Manhastro" extension have a bug, their chapters are only 5 pages long, can you fix it for me?

### Kotatsu version

6.6.8

### Android version

 android 13

### Other details

All mangas and manhwas in the "Manhastro" extension have a bug, their chapters are only 5 pages long, can you fix it for me?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Irineu333** [comment]
I don't know if it's the same bug, but it's skipping chapter pages in version 6.1-b.

https://github.com/KotatsuApp/kotatsu-parsers/assets/45833588/1a5229ee-03ab-4ddb-a554-d719ac147064

**Comment by fallowzp** [comment]
Uploading WhatsApp Video 2024-02-09 at 15.44.19.mp4…

**Comment by fallowzp** [comment]
> I don't know if it's the same bug, but it's skipping chapter pages in version 6.1-b.
> 
>  screen-20240209-123807.mp4

Todos os mangas e manhwas do Manhastro estao com os capitulos bugados, tendo apenas 5 paginas em cada capitulo.

**Comment by fallowzp** [comment]
> Não conheço a estruturado do projeto, clonei aqui e o Manhastro usa o MadaraParser. Parece ser um parser genérico usado em outras fontes.

Eu gravei um video mostrando o bug, mas não consigo enviar aqui.

**Comment by fallowzp** [comment]
O Manhastro bloqueou o app Kotatsu, por isso está assim, resolviso.

**Comment by Irineu333** [comment]
@fallowzp Então não tem o que fazer?

**Comment by Irineu333** [comment]
Realmente, não importa quantas vezes eu rode, sempre são 5 páginas.

![image](https://github.com/KotatsuApp/kotatsu-parsers/assets/45833588/3e8c30fa-5318-414c-bb2f-00a713c012ad)

**Comment by Irineu333** [comment]
Parece que o manhastro não carrega todas as páginas do capitulo inicialmente, ele vai carregando conforme você escrola, por isso o kotatsu parser não consegue pegar.

**Comment by fallowzp** [comment]
> Parece que o manhastro não carrega todas as páginas do capitulo inicialmente, ele vai carregando conforme você escrola, por isso o kotatsu parser não consegue pegar. 

Um mod do discord do Kotatsu me disse que essa extensão bloqueou eles, por isso está carregando apenas 5 páginas. E disse também para procurar outra extensão.

**Comment by fallowzp** [comment]
> @fallowzp Então não tem o que fazer?

Não tem o que fazer.

**Comment by Irineu333** [comment]
Triste, a Mangás Chan me bloqueou. As demais opções sempre estão alguns capítulos atrás.

**Comment by fallowzp** [comment]
> Triste, a Mangás Chan me bloqueou. As demais opções sempre estão alguns capítulos atrás.

Não sei o que aconteceu com o Mangás Chan, era o que eu mais usava no Tachiyomi, depois migrei pro Kotatsu, comecei usar o Mangas Chan no Kotatsu e ele parou de funcionar, fui pro Manhastro, parou de pegar também, agora tô usando qualquer um.
