### ISSUE TITLE
MangaNoon

### ISSUE THREAD

**Issue by yemenihandsome** [KotatsuApp/kotatsu-parsers#528]
### Source name

ManjaNoon

### Source link

https://manjanoon.net/

### Language

Arabic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
https://github.com/KotatsuApp/kotatsu-parsers/blob/52e4e6b80223eb6b1dc7eff8afda35b38bf6a128/src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/en/Manjanoon.kt#L10
