### ISSUE TITLE
Jiangzaitoon: Chapters are not appear.

### ISSUE THREAD

**Issue by ghost** [KotatsuApp/kotatsu-parsers#532]
### Source information

Jiangzaitoon (Turkish)

### Steps to reproduce

1.Open Jiangzaitoon
2. Open any manga
3. it says no chapters

The source changed their domain. When I update the domain, chapters don't appear.

New domain: https://jiangzaitoon.info/

### Kotatsu version
6.6.8

### Android version

Android 10 

### Other details

![IMG_20240203_195250](https://github.com/KotatsuApp/kotatsu-parsers/assets/146840629/b5fe4883-81b2-46a2-aac1-9595ea87490c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by nomaxsnx** [comment]
Even though I changed the URL in the settings, with a new domain the site has changed its theme, so the extension isn't working.

**Comment by kyoyacchi** [comment]
@ghost what is your native language?

**Comment by ayamelina** [comment]
> Even though I changed the URL in the settings, with a new domain the site has changed its theme, so the extension isn't working.

Same issue.

**Comment by davvarrr** [comment]
Fixed on https://github.com/KotatsuApp/kotatsu-parsers/commit/11c1eafa0dd815e8e7df148db71639903e2fb542
