### ISSUE TITLE
Source request Leercapitulo

### ISSUE THREAD

**Issue by Nomlez** [KotatsuApp/kotatsu-parsers#539]
### Source name

Leercapitulo

### Source link

https://www.leercapitulo.com/

### Language

Spanish

### Other details

Nswf = Yes/No

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Duplicate of [#456](https://github.com/KotatsuApp/kotatsu-parsers/issues/456)
