### ISSUE TITLE
TempleScan Captcha wont work

### ISSUE THREAD

**Issue by Pleasefix2** [KotatsuApp/kotatsu-parsers#541]
### Source information

TempleScan

### Steps to reproduce

1. Go to explore
2. Click on TempleScan
3. Click button to solve captcha
4. Click check mark

### Kotatsu version

6.6.8

### Android version

Android 14

### Other details

I'm not even sure if this is can issue you can fix or an issue with their site, but when I loaded the site on my browser the captcha worked 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
the source works, if you have any concerns with it don't hesitate to reopen the issues and give more details or image.
