### ISSUE TITLE
Captcha not working

### ISSUE THREAD

**Issue by Excitemax** [KotatsuApp/kotatsu-parsers#545]
### Source information

Mangageko

### Steps to reproduce

When mangageko require a captcha procedure as shown in notification to enable user to browse.

Step 1: click  browse
Step 2: click mangageko
It says captcha required
Step 3: press the button for the captcha, it took you to check a box
Step 4: check the box, somehow it loads, then umcheck the box. 
Repeat step 4

### Kotatsu version

6.6.8

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
The source works, no more infinite captcha.
Just in case, in the next update you'll be able to change the UserAgent manually for this source.
