### ISSUE TITLE
Captcha required stuck (infinite looping)

### ISSUE THREAD

**Issue by harakun24** [KotatsuApp/kotatsu-parsers#546]
### Source information

MangaGeko

### Steps to reproduce

1. Click explore
2. Click the source
3. Source error CAPTCHA require
4. Click solve
5. Cloudflare ask to check i am not robot
6. Click the checkbox
7. Redirect (loading)
8. Back to step 5 (infinite loop)

### Kotatsu version

6.6.8

### Android version

11

### Other details

So the source use cloudflare and need to check i am not a robot. But if i click it just refresh to check i am not a robot. However when i use web browser to the source it only need once to check i am not robot.
![Screenshot_20240205-172622](https://github.com/KotatsuApp/kotatsu-parsers/assets/50375988/6c75683b-654b-43fa-a488-2df905b056bd)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by duvjones** [comment]
I have been in countering this bug with webtoons.xyz and nhentai.net
Version 6.7.5
Android 13 (Lineage OS 20)

**Comment by davvarrr** [comment]
The source works, no more infinite captcha.
Just in case, in the next update you'll be able to change the UserAgent manually for this source.
