### ISSUE TITLE
FlixScans does not work

### ISSUE THREAD

**Issue by ghost** [KotatsuApp/kotatsu-parsers#547]
### Source information

FlixScan.com

### Steps to reproduce

Access to the source is not available
![Screenshot_٢٠٢٤٠٢٠٥-١٨٠٤٣١_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/144265316/34c2d63f-3ff6-4710-975a-76e4a9382201)

### Kotatsu version

6.7

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
#899
