### ISSUE TITLE
Getting the error "Server Side error (503)"

### ISSUE THREAD

**Issue by Salinda001** [KotatsuApp/kotatsu-parsers#589]
### Source information

DragonTea

I'm getting the same error in every manga I tried to read from dragontea.ink. It says server side error but the website is working fine. I have attached the screenshots below.

![Screenshot_2024-02-25-20-31-11-470-edit_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/130073141/5c1917ee-55af-4e57-8387-fd6eb6a88f27)
![Screenshot_2024-02-25-20-32-00-151-edit_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/130073141/bb4853f7-0727-4b9e-ab83-c4285cd73b66)

### Kotatsu version

6.7.3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
The source is working, update your application.
