### ISSUE TITLE
Chapter only show first 50 pages on Baozimh

### ISSUE THREAD

**Issue by czqdavid** [KotatsuApp/kotatsu-parsers#591]
### Source information

Baozimh

### Steps to reproduce

1. Open 航海王 on Baozimh, first mange in the third line.
2. Open the first chapter
3. It only shows first 50 pages.

Wrong url issue in webview for manga from search
1. Search 航海王
2. Open 航海王, the first one in the result
3. Open the webview
4. 'Get net::ERR_ACCESS_DENIED error and url is file:///comic/hanghaiwang-weitianrongyilang

### Kotatsu version

6.7.3

### Android version

Android 10

### Other details

Incomplete chapter issue only exists for chapters with more than 50 pages. When opening a chapter with more than 50 pages in the webview, webview only shows 50 pages. At the bottom, there's a arrow down symbol. After clicking the arrow down, the webview will show next 50 pages. If it's the end of the chapter, the symbol will be arrow right which directs to the next chapter.
![Screenshot_2024-02-26-13-34-04-096_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/24565488/8db1ff14-f67d-4bcf-ab93-b90d985e8639)
![Screenshot_2024-02-26-13-35-18-944_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/24565488/e0704c00-a11d-4e37-bbc9-be94a8f29f43)
As for wrong url in webview issue, it only occurs when open a manga from the search result. If manga is read directly instead of from the search, webview is correct.
![Screenshot_2024-02-26-13-35-55-079_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/24565488/143f29ee-411f-45b2-901b-db1b75b4120d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by czqdavid** [comment]
it still doesn't work for manga more than 100 pages. It only shows first 100 pages. It seems that it only clicks arrow down once. Then it'll not work for chapters more than 100 pages. Need to click arrow down until the arrow right appears at the right bottom which links to the next chapter.

**Comment by czqdavid** [comment]
@Koitharu @NagaYZ  I think i don't have the right to reopen this issue. should i create a new issue instead?

**Comment by NagaYZ** [comment]
no need i fixed it in my current pr

**Comment by czqdavid** [comment]
Thanks a lot. it works now
