### ISSUE TITLE
Can't load AsuraScans

### ISSUE THREAD

**Issue by lanceteo** [KotatsuApp/kotatsu-parsers#594]
### Source information

AsuraScans

### Steps to reproduce

1. Go to Explore 2. Look for AsuraScans in Manga sources 3. Click into AsuraScans

### Kotatsu version

6.7.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
now its works
