### ISSUE TITLE
StellarSaber

### ISSUE THREAD

**Issue by esaoud** [KotatsuApp/kotatsu-parsers#598]
### Source information

StellarSaber

### Steps to reproduce

The domain of the source has been changed to "StellarSaber.pro"

### Kotatsu version

6.7.4

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
the source already has its own domain name.
https://github.com/KotatsuApp/kotatsu-parsers/blob/cd468df9ad828c4bbb5444321c0f6b2c6521dffc/src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/ar/StellarSaber.kt#L10
