### ISSUE TITLE
Asurascans broken

### ISSUE THREAD

**Issue by KnightmareMoon1944** [KotatsuApp/kotatsu-parsers#599]
### Source information

AsuraScans

### Steps to reproduce

All titles in my favorites from asurascans now show no chapters, and opening the source shows no available titles.

### Kotatsu version

6.7.4

### Android version

Android 14

### Other details

![Screenshot_20240228_151049_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/158500296/10cbd1d8-b7fe-4e52-89f2-794e9b59cb3d)
![Screenshot_20240228_151033_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/158500296/58145602-9f06-4cac-a741-7182ad336768)

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by NagaYZ** [comment]
Because the website is down for maintenance, they are switching servers.

**Comment by davvarrr** [comment]
now its works
