### ISSUE TITLE
Epsilonscan IS broken

### ISSUE THREAD

**Issue by xavimaa** [KotatsuApp/kotatsu-parsers#602]
### Source information

EpsilonScan

### Steps to reproduce

Hello, when I want to use the epsilonscan source nothing is found.  When I want to open this source with the browser integrated into kotatsu I also get an error.  I would like to take advantage of this report to thank you for the work you do on the application and in particular the management of sources with cloudflare.

![image](https://github.com/KotatsuApp/kotatsu-parsers/assets/82511742/e31370a6-1786-44f6-9359-7374363f31ab)

### Kotatsu version

6.7.4

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by TheFlomax** [comment]
Me too on Kotatsu 6.8.3 with Android 13.
It seems that EpsilonScan, has made changes to the code of its site, which has broken the source.
