### ISSUE TITLE
S2manga error

### ISSUE THREAD

**Issue by Pleasefix2** [KotatsuApp/kotatsu-parsers#605]
### Source information

S2Manga

### Steps to reproduce

1. Open app
2. Click on s2manga source
3. Manga show up

### Kotatsu version

6.7.4

### Android version

Android 14

### Other details

When opening the source, I get "an error occurred" message. It was not like this yesterday.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
The source works, update your app, if the problem returns, give us a manga as an example.
