### ISSUE TITLE
The nhentai source cannot search the id to find comics.

### ISSUE THREAD

**Issue by maxshiro** [KotatsuApp/kotatsu-parsers#610]
### Source information

nhentai

### Steps to reproduce

Click browse, click nhentai source, click search, and enter id. You can't find comics, as shown in the figure.
![Screenshot_20240306_123528_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/20143941/80510f0b-fbc6-4e00-91be-13cf159d85f8)

### Kotatsu version

6.7.4

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by kyoyacchi** [comment]
I have already open a issue about this 
https://github.com/KotatsuApp/kotatsu-parsers/issues/419
