### ISSUE TITLE
Solve captcha loop

### ISSUE THREAD

**Issue by KazurK** [KotatsuApp/kotatsu-parsers#633]
### Source information

Nhentai

### Steps to reproduce

1.Click explore
2.Click the source
3.Source error CAPTCHA require
4.Click solve
5.Cloudflare ask to check i am not robot
6.Click the checkbox
7.Redirect
8.Back to step 5 (infinite loop)

### Kotatsu version

6.7.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by KazurK** [comment]
Note: solving the captcha outside of the app does work

**Comment by duvjones** [comment]
excuse me, what do you mean by that?

**Comment by Biablabla7v7** [comment]
Llevo intentando en la app de Kotatsu solucionar ese error en la fuente de TOM es muy agobiante.

**Comment by KazurK** [comment]
> excuse me, what do you mean by that?

If you go to the website you can pass the captcha and continue to use the website

But you cannot pass the captcha through the kotatsu app

Sorry if i was being confusing in my previous note

**Comment by Koitharu** [comment]
Update app to 6.8
