### ISSUE TITLE
Manga-lek cloudflare 

### ISSUE THREAD

**Issue by rashid19961** [KotatsuApp/kotatsu-parsers#635]
### Source information

Manga-lek

### Steps to reproduce

1. Open extension manga-lek
2. You need to change url to the new url manga-lek.net (old one was outdated for a bit)
3. Try to open any manhwa
4. Complete cloudflare
5. You get failure and infinite looping

### Kotatsu version

6.7.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Update app to 6.8
