### ISSUE TITLE
Capacha broken

### ISSUE THREAD

**Issue by elies1996** [KotatsuApp/kotatsu-parsers#636]
### Source information

most sources if not all for example bentoscan or it is settled

### Steps to reproduce

the page always asks me for a capacha verification its mill asks me to press a button then its mill for a fraction of a second it tells me that the verification was not successful then its reward``

### Kotatsu version

6.7.5

### Android version

14

### Other details

The problem looks like the bentoscan problem but I think it comes from cloudflare

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Jaetan-Salvetat** [comment]
I have the same issue with all french sources (i'm on Android 14 with version 6.7.4)

**Comment by elies1996** [comment]
Yes on all sources that require a capacha and even bentoscan which had been resolved at one time

**Comment by elies1996** [comment]
The problem is not resolved I made a mistake on the sorry button

**Comment by Koitharu** [comment]
Update app to 6.8
