### ISSUE TITLE
Capacha 

### ISSUE THREAD

**Issue by elies1996** [KotatsuApp/kotatsu-parsers#638]
### Source information

All French sources that use a capacha and probably all sources that use a capacha cloudflare 

### Steps to reproduce

Choose any source that uses capacha or at least cloudflare capacha.
And do the capacha verification 

### Kotatsu version

6.7.5

### Android version

14

### Other details

Sorry the problem is not resolved I made a mistake on the button 
But it will allow me to redo the ticket properly 

There is also Jaetan-Salvetat who has the same problem as me who commented in the previous ticket 

I have the same issue with all french sources (i'm on Android 14 with version 6.7.4)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Update app to 6.8
