### ISSUE TITLE
Captcha loop

### ISSUE THREAD

**Issue by FariBeki** [KotatsuApp/kotatsu-parsers#639]
### Source information

Mangaschan 

### Steps to reproduce

Não conecta na fonte, fica só em análise no captcha

### Kotatsu version

6.7.5

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by elies1996** [comment]
Doublon

**Comment by Koitharu** [comment]
Update app to 6.8
