### ISSUE TITLE
Onegascans isn't working while their website is fine

### ISSUE THREAD

**Issue by Vucter** [KotatsuApp/kotatsu-parsers#641]
### Source information

Omegascans

### Steps to reproduce

1.Open the source and it's said there's nothing found

### Kotatsu version

6.7.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by NagaYZ** [comment]
site was on maintenance and got updated, so some of the website structures have changed, I'm gonna wait until they're done to update it.

**Comment by MCcoolman** [comment]
Not working for me, how can I fix it?

**Comment by NagaYZ** [comment]
What version are you on ? Because it is working for me on the current latest version v7.0-beta2.

**Comment by MCcoolman** [comment]
V6.8.3

**Comment by NagaYZ** [comment]
Yea you need to update
