### ISSUE TITLE
Manga Galaxy does not work.

### ISSUE THREAD

**Issue by MyKareee** [KotatsuApp/kotatsu-parsers#648]
### Source information

Manga Galaxy

### Steps to reproduce

1. Open the source (Manga Galaxy) and it's said: An Error Occurred

### Kotatsu version

6.8

### Android version

Android 13

### Other details

1. I also double check the link of the website and it is correct.
2. I also check manually if the website is working fine in the browser.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by MyKareee** [comment]
Hello, i want to ask @Koitharu @AwkwardPeak7 ...

Should i wait for a few more hours after the fix? cause I just checked a few minutes ago.. It still has the same error

Current version: 6.8.3

**Comment by AwkwardPeak7** [comment]
@MyKareee wait for next update of the app

**Comment by MyKareee** [comment]
Ah sorry, Now i understand how the fix work and the process.

Thank you
