### ISSUE TITLE
Captcha in some sources not working and/or not solving

### ISSUE THREAD

**Issue by JustPointingErrors** [KotatsuApp/kotatsu-parsers#651]
### Source information

nhentai.net, Manhwalover.com, Manhwa-raw.com, ManhwaZ, MangaLeveling, ManhwasMen

### Steps to reproduce

After every update some sources (like NHentai.net, Manhwalover.com, Manhwa-raw.com, ManhwaZ, MangaLeveling, ManhwasMen) ask to redo the captcha, but after the latest update these captchas keep failing or won't open, although I didn't use the app for like a week after the latest update so there's a change it is unrelated. Point being, the captchas on these sources keep failing in the app

### Kotatsu version

6.7.5

### Android version

Android 12

### Other details

It seems all these pages use the same type of captcha.

Also, I already tried to clear the cache, history, and uninstall and reinstall the app to no avail.

Also also, thank you for your work on this app, truly really great app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Update to 6.8
