### ISSUE TITLE
source problem

### ISSUE THREAD

**Issue by oussama827** [KotatsuApp/kotatsu-parsers#659]
### Source information

swatmanhua

### Steps to reproduce

new chapters are not updated on the site, yes on the site but on the kotatsu app no
![Screenshot Browser](https://github.com/KotatsuApp/kotatsu-parsers/assets/142851037/d39a71e5-49ff-4c6a-a5c1-cd7036aea68a)
![Screenshot Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/142851037/ea2e37ec-a409-44b2-9bfa-f08dfe1961d3)

### Kotatsu version

6.8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by NagaYZ** [comment]
It's not really a bug, the problem is on their side, only their homepage contains the most recent chapter, while kotatsu pulls the information from this page https://swatmanhua.com/manga , where as you can see, it hasn't been updated yet and what's more, their sorting doesn't even work correctly.
