### ISSUE TITLE
Sometimes captcha verification bug

### ISSUE THREAD

**Issue by elies1996** [KotatsuApp/kotatsu-parsers#661]
### Source information

All French sources and some English (not to say all because I use very few English sources) like Bento manga raijin scan

### Steps to reproduce

Fill out a captcha 

### Kotatsu version

6.8.1

### Android version

14

### Other details

Sometimes when I receive a captcha the application opens the browser to the requested manga page.

https://github.com/KotatsuApp/kotatsu-parsers/assets/13474629/957c227b-0414-40bf-91c9-da744fd551cc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
I don't have a problem with French sources, just update your app.
