### ISSUE TITLE
Merlin scans nothing found problem

### ISSUE THREAD

**Issue by Furygo33** [KotatsuApp/kotatsu-parsers#665]
### Source information

MerlinScans

### Steps to reproduce

![Screenshot_20240326-212441_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/165090564/138b9803-6ddb-4288-9a42-39f49bf08552)
I am entering the source and I would be glad if you could help me this way.  

### Kotatsu version

6.8.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
#567
