### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by Furygo33** [KotatsuApp/kotatsu-parsers#666]
### Source information

Mangaokutr

### Steps to reproduce

![Screenshot_20240326-212415_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/165090564/dc6e493a-941d-4f8a-81cd-9b6c42a88152)
There is a server error in the source 

### Kotatsu version

6.8.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
[#666](https://github.com/KotatsuApp/kotatsu-parsers/issues/666)
