### ISSUE TITLE
ComicExtra search engine not working

### ISSUE THREAD

**Issue by Tarant00** [KotatsuApp/kotatsu-parsers#667]
### Source information

ComicExtra

### Kotatsu version

6.8.1

### Android version

9.0

### Other details

When I try to search comics on the ComicExtra extension, it does not work.

I checked the url in those cases and it goes: https://comicextra.org/comic-search?key="insert search here"

But when i search directly on the website, the url should be: https://comicextra.org/search?keyword="insert search here"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by giannisanni** [comment]
I have the same issue
