### ISSUE TITLE
Random Scan

### ISSUE THREAD

**Issue by godestroyer666** [KotatsuApp/kotatsu-parsers#679]
### Source information

Random Scans

### Steps to reproduce

1. Domain
2. website structure

### Kotatsu version

6.8.3

### Android version

Android 13

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
https://github.com/KotatsuApp/kotatsu-parsers/issues/871
