### ISSUE TITLE
مانجا نوون (Arabic)

### ISSUE THREAD

**Issue by IslamAbdel** [KotatsuApp/kotatsu-parsers#68]
### Source name

مانجا نوون

### Source link

https://manganoon.com/

### Language

Arabic

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Issues need to close because site no website mangas
