### ISSUE TITLE
Luratoon

### ISSUE THREAD

**Issue by godestroyer666** [KotatsuApp/kotatsu-parsers#680]
### Source name

Luratoon

### Source link

https://luratoon.com/

### Language

Portuguese

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
https://github.com/KotatsuApp/kotatsu-parsers/blob/466ca0f0e987acf2ee11bcabf335668ccdde996f/src/main/kotlin/org/koitharu/kotatsu/parsers/site/pt/LuratoonScansParser.kt#L25
