### ISSUE TITLE
The sites I try to open has changed the structure, and the parser has stopped working

### ISSUE THREAD

**Issue by K2binks** [KotatsuApp/kotatsu-parsers#686]
### Source information

The source name is Phenixscans(French)

### Steps to reproduce

When I go to the website of Phenixscan on Google and try to open it on kotatsu it doesn't work
[Screenshot_2024-04-11-20-06-42.zip](https://github.com/KotatsuApp/kotatsu-parsers/files/14950868/Screenshot_2024-04-11-20-06-42.zip)

### Kotatsu version

6.8.3

### Android version

5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
The source works, update your app
