### ISSUE TITLE
Working issue

### ISSUE THREAD

**Issue by itz-ats-sama** [KotatsuApp/kotatsu-parsers#694]
### Source information

OmegaScans

### Steps to reproduce

It is not opening. 
![Screenshot_20240415_102022_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/167066195/5a43f547-9219-439a-a579-46991f89512b)

### Kotatsu version

6.8.3

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by NagaYZ** [comment]
duplicate of #687

**Comment by itz-ats-sama** [comment]
Hello,
OmegaScans is still not opening.

**Comment by NagaYZ** [comment]
Wait for the next release

**Comment by itz-ats-sama** [comment]
Okay, thanks.

Also, if possible...please add vyvymangaz.net source.

**Comment by itz-ats-sama** [comment]
Sorrry, vyvymanga.net...not the previous ones I sent.
