### ISSUE TITLE
A

### ISSUE THREAD

**Issue by On1as** [KotatsuApp/kotatsu-parsers#695]
### Source name

arabshentai.com

### Source link

https://arabshentai.com/

### Language

Arabic 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Duplicate of [#249](https://github.com/KotatsuApp/kotatsu-parsers/issues/249)
