### ISSUE TITLE
reaper scans captcha loop

### ISSUE THREAD

**Issue by blackwing12344** [KotatsuApp/kotatsu-parsers#699]
### Source information

reaper scans

### Steps to reproduce

1. Notif that reaper scans fails after feed reload 
2. Click on notif
3. Try captcha 
4. Fail and loop

### Kotatsu version

6.8.3

### Android version

android 13

### Other details

Tried using browser to solve it, and nothing 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Wowo80** [comment]
Happening to me as well
