### ISSUE TITLE
Troubles with Desu me

### ISSUE THREAD

**Issue by Vendetta2** [KotatsuApp/kotatsu-parsers#700]
### Source information

Desu me

### Steps to reproduce

This website don't work in Kazakhstan, new link-mirror
https://desu.win/

### Kotatsu version

6.8.3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
This domain is already specified as an alternative, you can change it in the application via source settings
