### ISSUE TITLE
Source qui s'ouvre pas directement mais s'ouvre dans le navigateur 

### ISSUE THREAD

**Issue by Adhelaiide** [KotatsuApp/kotatsu-parsers#702]
### Source information

Epsilonscan 

### Steps to reproduce

1- ouvrir l'extension epsilonscan 
2- il est écrit qu'il y a rien 
3- ouvrir le navigateur de kotatsu tout est ouvert 

### Kotatsu version

6.8.3

### Android version

Android 10

### Other details

![Screenshot_20240419-205020](https://github.com/KotatsuApp/kotatsu-parsers/assets/167572293/debd4c83-2087-4838-8f1d-e18d2b14cad5)
![Screenshot_20240419-205316](https://github.com/KotatsuApp/kotatsu-parsers/assets/167572293/f3f70135-4082-4470-8cc6-74554ca3d102)
![Screenshot_20240419-205331](https://github.com/KotatsuApp/kotatsu-parsers/assets/167572293/2a91df36-ac56-4337-8615-43429d57d96f)
![Screenshot_20240419-205408](https://github.com/KotatsuApp/kotatsu-parsers/assets/167572293/d3535406-3576-435e-bfb6-1b66e36d76eb)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Use English pls(
