### ISSUE TITLE
Please could you add this source visorolym.com

### ISSUE THREAD

**Issue by CapZeus30** [KotatsuApp/kotatsu-parsers#706]
### Source name

Olympus scan o visorolym

### Source link

https://visorolym.com/

### Language

Spanish 

### Other details

Does not require captcha
![Screenshot_20240421-134953](https://github.com/KotatsuApp/kotatsu-parsers/assets/166955068/2bafc4d2-40ca-4d82-9a6f-5c589b95d050)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
#823
