### ISSUE TITLE
Yugenmangas.lat

### ISSUE THREAD

**Issue by Balencnd** [KotatsuApp/kotatsu-parsers#717]
### Source link

Yugenmangas.lat

### Other details (reason for removal, etc)

Doesn't work because the new source is ikigaimangas

### Requirements

- [X] Proof of ownership of the website is sent to a Kotatsu [Discord server](https://discord.gg/NNJ5RgVBC5) or [Telegram community](https://t.me/kotatsuapp)
- [X] Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)

**Comment by 1222Kan** [comment]
Si por favor 🙏🙏sería genial si agregaran la nueva fuente Ikigai 🙏

**Comment by davvarrr** [comment]
Duplicate of #538
