### ISSUE TITLE
RandomScans(Lura toon) it is not showing anything in the extension

### ISSUE THREAD

**Issue by JosephShay** [KotatsuApp/kotatsu-parsers#725]
### Source information

RandomScans

### Steps to reproduce

![image](https://github.com/KotatsuApp/kotatsu-parsers/assets/48162671/514510db-560b-4a40-827b-7ddc9e346f24)

As seen in the image, no manga appears in the extension but in the webview everything is working normally without any problems.

### Kotatsu version

6.8.3

### Android version

11

### Other details

Everything on the scan website is working perfectly and the domain remains the same.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by MRhawk480** [comment]
this happened because they changed the structure of the site, only an application administrator can do something about it

**Comment by Dracozz0** [comment]
E do jeito que demora para mexerem nas extensões portuguesas..., queria tanto a luratoon funcionando
