### ISSUE TITLE
Some Arabic Websites #1

### ISSUE THREAD

**Issue by Amirbrnjallon** [KotatsuApp/kotatsu-parsers#726]
### Source name

Dilar

### Source link

https://dilar.tube/

### Language

Arabic

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Duplicate of https://github.com/KotatsuApp/kotatsu-parsers/issues/304

**Comment by OtakuArab** [comment]
> Duplicate of #304

and you 
https://www.mangatales.com/
