### ISSUE TITLE
Erro em páginas e capítulos de um Mangá 

### ISSUE THREAD

**Issue by xddwww** [KotatsuApp/kotatsu-parsers#729]
### Source information

Eh

### Kotatsu version

V7.0 B2

### Android version

Android 12 ou 13

### Other details

Não dá pra ver alguns capítulos e páginas do Manga Tonikaku Kawaii 
![Screenshot_20240504_223046_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/168944345/abaeb944-8f09-4269-bcbb-6a4b3b548a4e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
Without the name of the source we can't help you....
Don't hesitate to reopen the issue with new information.
