### ISSUE TITLE
Portuguese Fonts Urgent 

### ISSUE THREAD

**Issue by EvaldoCeBr** [KotatsuApp/kotatsu-parsers#739]
### Source name

Hiper Cool

### Source link

https://hiper.cool

### Language

Português

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by ztimms73** [comment]
Exists
https://github.com/KotatsuApp/kotatsu-parsers/blob/master/src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/pt/Hipercool.kt
