### ISSUE TITLE
Bug on portuguese extension 

### ISSUE THREAD

**Issue by Dracozz0** [KotatsuApp/kotatsu-parsers#743]
### Source information

Luratoon Scans

### Steps to reproduce

Even in the updated version, luratoon still looks like this. I commented on the update post, I don't know if the developer saw it
![IMG_20240508_225200](https://github.com/KotatsuApp/kotatsu-parsers/assets/168906459/05a3146e-98f2-4066-8812-cb3eb6c76ad2)
![IMG_20240508_225149](https://github.com/KotatsuApp/kotatsu-parsers/assets/168906459/7e32c94e-267e-423a-9a31-d699c15dce93)

### Kotatsu version

7.0-rc2

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
#871
