### ISSUE TITLE
CeriseScans link change and structure

### ISSUE THREAD

**Issue by herowolfG** [KotatsuApp/kotatsu-parsers#745]
### Source information

CeriseScans

### Steps to reproduce

there has been a change in the link to: https://cerisetoon.com

### Kotatsu version

6.8.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
[#718](https://github.com/KotatsuApp/kotatsu-parsers/issues/718)
