### ISSUE TITLE
Order of the chapters

### ISSUE THREAD

**Issue by T0oLittleT0oLate** [KotatsuApp/kotatsu-parsers#747]
### Source information

MangaPark

### Steps to reproduce

1. Open the manga
2. Open the chapters
3. All of the chapters are inverted, i need to read backwars to progress
![Screenshot_20240509_214808_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/169413179/cb93075e-93ce-445a-a24e-83d2577151fe)

### Kotatsu version

6.8.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
Already fixed, will be available in 7.0
