### ISSUE TITLE
Luratoon doesn't load the data

### ISSUE THREAD

**Issue by DollynDeveloper** [KotatsuApp/kotatsu-parsers#748]
### Source information

Luratoon Scan

### Steps to reproduce

![Screenshot_20240510-202907_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/72720834/d07cc0f2-ad9e-40de-a2e6-1e1d95853790)

### Kotatsu version

7.0-rc2

### Other details

The manga source doesn't load anything in the app. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
#871
