### ISSUE TITLE
Solicitud de fuente Mangas.in

### ISSUE THREAD

**Issue by 1222Kan** [KotatsuApp/kotatsu-parsers#750]
### Source name

Mangas.in

### Source link

https://mangas.in/

### Language

Español 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Duplicate of [#455](https://github.com/KotatsuApp/kotatsu-parsers/issues/455)
