### ISSUE TITLE
Luratoon Scan is not working 

### ISSUE THREAD

**Issue by DollynDeveloper** [KotatsuApp/kotatsu-parsers#754]
### Source information

Luratoon Scan

### Steps to reproduce

![Screenshot_20240512-134753_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/72720834/37a788f7-8838-44f4-a307-9f965d47b1dc)

### Kotatsu version

7.0

### Other details

After the update, the Luratoon manga source stopped working. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
#871
