### ISSUE TITLE
Problem with DemonSect font.

### ISSUE THREAD

**Issue by EvaldoCeBr** [KotatsuApp/kotatsu-parsers#755]
### Source information

DemonSect

### Steps to reproduce

![Screenshot_2024-05-12-16-56-14-647_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/169321265/b95f5fa0-87ef-4a74-8060-55668eaf2a7b)
![Screenshot_2024-05-12-16-57-29-403_com android chrome](https://github.com/KotatsuApp/kotatsu-parsers/assets/169321265/1d141123-1a1e-48e0-a90a-cbdab5a2d6d5)

To access the source you need to log in.  It is no longer loading in the app.

### Kotatsu version

7.0-rc3

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by EvaldoCeBr** [comment]
![Screenshot_2024-05-12-20-30-06-076_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/169321265/adc8202c-4f99-464f-8df8-1098ecaa36cc)

**Comment by Dracozz0** [comment]
I think it was because they made login mandatory, but I think the admin should be able to get through

**Comment by Josue18js** [comment]
E só logar no site da demon pelo browser do kotatsu que as páginas abrem normalmente, n é bug n

**Comment by Dracozz0** [comment]
> E só logar no site da demon pelo browser do kotatsu que as páginas abrem normalmente, n é bug n

Eu tentei fazer isso mas não deu certo, o seu entrou dboa?

**Comment by EvaldoCeBr** [comment]
> E só logar no site da demon pelo browser do kotatsu que as páginas abrem normalmente, n é bug n

Obg deu certo.
