### ISSUE TITLE
He should Updated 95% naked Arabic sources no longer work

### ISSUE THREAD

**Issue by OtakuArab** [KotatsuApp/kotatsu-parsers#757]
### Source information

Arabic Source

### Steps to reproduce

Accessing the sources does not work, it needs to be updated

### Kotatsu version

7.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
not informative ticket
