### ISSUE TITLE
Luratoon Scan change in site structure.

### ISSUE THREAD

**Issue by EvaldoCeBr** [KotatsuApp/kotatsu-parsers#764]
### Source information

Luratoon Scan

### Steps to reproduce

Even changing the user agent, the Luratoon extension does not show the content.
![Screenshot_2024-05-16-13-25-05-303_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/169321265/440ae0c3-457c-43bf-902d-30865dcd292f)

### Kotatsu version

7.0.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
#871
