### ISSUE TITLE
Capcha unable to be resolved

### ISSUE THREAD

**Issue by ShinB0y** [KotatsuApp/kotatsu-parsers#765]
### Source information

Multiple sources

### Kotatsu version

7.0.1

### Android version

14

### Other details

Most of my capcha redirects me to the manga site itself and it just stays there. After clicking close, it keep telling me to solve capcha. 

There are some others that keep looping me in the solve capcha checkbox 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
non informative ticket, no sources provided, closing
