### ISSUE TITLE
Capcha unable to be resolved

### ISSUE THREAD

**Issue by ShinB0y** [KotatsuApp/kotatsu-parsers#766]
### Source information

Multiple fkin sources

### Kotatsu version

7.0.1

### Android version

14

### Other details

Reopen cuz admin lazy to check further 

Most of my capcha redirects me to the manga site itself and it just stays there. After clicking close, it keep telling me to solve capcha.

There are some others that keep looping me in the solve capcha checkbox

![Screenshot_20240518_001350_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/65650775/f850692e-28e9-4581-8123-66d834e52329)
![Screenshot_20240518_001356_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/65650775/2cf78d0a-df5f-4c30-8439-c2f31b18aaa8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
In the last update the source works very well, in the next commit it will be renamed from IsekaiScan.to to ParagonScans.
