### ISSUE TITLE
Zinmanga not working.. 

### ISSUE THREAD

**Issue by RishaRea48** [KotatsuApp/kotatsu-parsers#767]
### Source information

Zinmanga

### Steps to reproduce

Zinmanga not working

### Kotatsu version

7.0.1

### Android version

Android 13

### Other details

Zinmanga source isn't working. 
When I click the source it said content remove or not found and when I open it in web browser I got an error.. 
![Screenshot_20240518_130537_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/170189437/97b62a08-ee26-496f-bd96-af2245ba80df)
![Screenshot_20240518_130747_org koitharu kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/170189437/33efd3d0-6ea7-43d0-8fcd-7cadeb75be8f)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
fix on [0bcac0c639952b615b3a27db74fc0811a85a73be](https://github.com/KotatsuApp/kotatsu-parsers/commit/7433fb8fa0cbaf628daba02adc6d78d0ce7e3e7c)

**Comment by RishaRea48** [comment]
I'm sorry about this but what does it mean..?? Tried clicking it and it shows me a bunch of codes..

**Comment by davvarrr** [comment]
Just wait for the next app update ;)

**Comment by RishaRea48** [comment]
Oh so that's what it is. Thank you for replying! Will wait for the next update.
