### ISSUE TITLE
Source request

### ISSUE THREAD

**Issue by CuongBa956** [KotatsuApp/kotatsu-parsers#77]
### Source name

Hentaivn

### Source link

https://hentaivn.la/

### Language

Vietnamese

### Other details

one of the most famous hentai web with vietnamese.  I hope it comes out soon

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Need to close this sourcre its added -> https://github.com/KotatsuApp/kotatsu-parsers/blob/065263a9bde209fd312159515b70a67d97655d83/src/main/kotlin/org/koitharu/kotatsu/parsers/site/vi/HentaiVNParser.kt#L19
