### ISSUE TITLE
Captcha issues on Mangaschan.net

### ISSUE THREAD

**Issue by CyberDenner** [KotatsuApp/kotatsu-parsers#770]
### Source information

MangasChan

### Steps to reproduce

1. Open MangasChan source
2. Click to solve the CAPTCHA

### Kotatsu version

7.0

### Android version

Android 14

### Other details

When I try to solve the captcha it appears as if WAF has blocked me (and this happens both using mobile and wireless data), but I can access the website normally **without any problems using Google Chrome or Brave browser.**

![photo_2024-05-20_12-49-45](https://github.com/KotatsuApp/kotatsu-parsers/assets/146398551/69b11557-f542-45b2-867d-2b621649e1cd)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by EvaldoCeBr** [comment]
I use it too and it asks for CAPTCHA, but when I put it in I can open it normally in Katatsu.![Screenshot_2024-05-20-13-31-46-021_org.koitharu.kotatsu.jpg](https://github.com/KotatsuApp/kotatsu-parsers/assets/169321265/25fab537-18f2-47ce-a979-4ec44e79ab07)

**Comment by EvaldoCeBr** [comment]
Mangaschan is no longer updating the works!

**Comment by davvarrr** [comment]
Dead source
