### ISSUE TITLE
Add a new source named " Central Novel"

### ISSUE THREAD

**Issue by OVisitanteh** [KotatsuApp/kotatsu-parsers#778]
### Source name

Central Novel

### Source link

https://centralnovel.com/

### Language

Português Brasil 

### Other details

There are few sources that have Novels in Brazilian Portuguese, especially now that manga and anime websites are dropping here. I ask you to help by adding this extension;)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by OVisitanteh** [comment]
*Correction since I wrote it through the translator I meant that manga and anime websites are being hunted down and taken down here in Brazil, so it's difficult to find the works. There are no legal ways to obtain the works because there are no publishers who bring these works here. It's just the fans who work hard and translate from fan to fan. It would be a great help to add these sources and a few more that remain.

**Comment by NagaYZ** [comment]
Novels aren't supported
