### ISSUE TITLE
Klz9 : Chapters not found

### ISSUE THREAD

**Issue by 774-3san** [KotatsuApp/kotatsu-parsers#784]
### Source information

Klz9

### Steps to reproduce

The source opens normally and the manga appears on the home page. But when opening a manga a message appears that says "There is no chapter in this manga"

### Kotatsu version

7.1.1

### Android version

Android 13

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by NagaYZ** [comment]
fixed in #797
