### ISSUE TITLE
[Source Request] Komikcast

### ISSUE THREAD

**Issue by Mr48690** [KotatsuApp/kotatsu-parsers#79]
### Source name

Komik Cast

### Source link

https://komikcast.me/

### Language

Indonesia

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by ztimms73** [comment]
Mirror: komikcast.site

**Comment by alpqm** [comment]
> Mirror: komikcast.site

when will this be added

**Comment by kolinrno** [comment]
> > Mirror: komikcast.site
> 
> when will this be added

menunggu juga

**Comment by MIRVOUS** [comment]
The website link is changed from 'komikcast.me' to 'komikcast.site'

**Comment by MIRVOUS** [comment]
komikcast.io
(Website changed their url)
