### ISSUE TITLE
CeriseScans change in site structure. 

### ISSUE THREAD

**Issue by Josue18js** [KotatsuApp/kotatsu-parsers#791]
### Source information

CeriseScans 

### Steps to reproduce

Even changing the user agent, the CeriseScans extension does not show the content.
![Screenshot_20240526_143810_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/92787197/cd60122d-dea1-4025-8db4-97b17b8b2f5e)

### Kotatsu version

7.1.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
[#718](https://github.com/KotatsuApp/kotatsu-parsers/issues/718)
