### ISSUE TITLE
TruyenQQ change their site structure 

### ISSUE THREAD

**Issue by Vucter** [KotatsuApp/kotatsu-parsers#793]
### Source information

TruyenQQ

### Steps to reproduce

They change their CAPTCHA

### Kotatsu version

7.1.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Vucter** [comment]
The only workaround is to open their website with the in-app browser and then close the in-app browser.

**Comment by davvarrr** [comment]
Source dead.

**Comment by Vucter** [comment]
they just change it to truyenqqviet.com

**Comment by davvarrr** [comment]
![image](https://github.com/KotatsuApp/kotatsu-parsers/assets/70220050/8b45b127-6383-4dbd-b987-3fa50a3d7dcb)

it should learn to be clearer... thanks for the info, it'll be updated in the next commit.
