### ISSUE TITLE
Solicitud de fuente 

### ISSUE THREAD

**Issue by 1222Kan** [KotatsuApp/kotatsu-parsers#794]
### Source name

Traducciones Moonlight

### Source link

https://traduccionesmoonlight.com/

### Language

Español 

### Other details

Antes está fuente se encontraba en Kotatsu pero al parecer, ¿fue eliminada?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
https://github.com/KotatsuApp/kotatsu-parsers/blob/466ca0f0e987acf2ee11bcabf335668ccdde996f/src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/es/TraduccionesMoonlight.kt#L11

**Comment by SantoRyuk22** [comment]
There are some error or bug when try to access the scan and it is appearing this link
<https://traduccionesmoonlight.com/manga?order=update&page=1> that is not working, but the domain of it works well.
