### ISSUE TITLE
Manga Source Problems

### ISSUE THREAD

**Issue by DollynDeveloper** [KotatsuApp/kotatsu-parsers#814]
### Source information

Luratoon Scan

### Steps to reproduce

The font does not load any content, showing flaws in it. The error had theoretically already been corrected, but remains the same. 
![Screenshot_20240528-220117_Kotatsu](https://github.com/KotatsuApp/kotatsu-parsers/assets/72720834/01faa380-603d-47f3-8c23-8bd3bb7a886d)

### Kotatsu version

7.1.2

### Android version

10

### Other details

The web view as well as the site itself work normally. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
#871
