### ISSUE TITLE
Luratoon Scan (Portuguese Source) changed domain.

### ISSUE THREAD

**Issue by EvaldoCeBr** [KotatsuApp/kotatsu-parsers#821]
### Source information

Luratoon Scan

### Steps to reproduce

Luratoon Scan (Portuguese Source) changed domain.  You can no longer view the content.  I ask you to update the source.

![Screenshot_2024-06-01-11-53-27-585_app mihon debug](https://github.com/KotatsuApp/kotatsu-parsers/assets/169321265/877c37cc-a70a-4008-9d63-373f7f7206ec)
![Screenshot_2024-06-01-11-54-02-525_com android chrome](https://github.com/KotatsuApp/kotatsu-parsers/assets/169321265/fd0fd144-e19a-4fba-84c1-57b5e3312ff7)

### Kotatsu version

7.1.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by EvaldoCeBr** [comment]
Old domain: https://lura-toons.com/;  New Domain: https://luratoons.com/.

**Comment by EvaldoCeBr** [comment]
![Screenshot_2024-06-01-11-53-27-585_app mihon debug](https://github.com/KotatsuApp/kotatsu-parsers/assets/169321265/55101482-596b-4057-91c7-ac002f3bf588)
![Screenshot_2024-06-01-11-54-02-525_com android chrome](https://github.com/KotatsuApp/kotatsu-parsers/assets/169321265/31a6f124-d26a-4a81-b6a8-82bdc8e4f24d)
0l0

**Comment by davvarrr** [comment]
#871
