### ISSUE TITLE
captcha problem

### ISSUE THREAD

**Issue by diecko69** [KotatsuApp/kotatsu-parsers#830]
### Source information

Ainzscans

### Steps to reproduce

1.when opening the source it will ask for captcha verification
2.After a few minutes while reading/downloading the source will ask for captcha verification again and this will repeat endlessly

### Kotatsu version

7.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
With the new update it works, updated your application.
