### ISSUE TITLE
Update Source Truyenqq

### ISSUE THREAD

**Issue by bui-lang** [KotatsuApp/kotatsu-parsers#831]
### Source information

Truyenqq

### Kotatsu version

7.2

### Android version

Android 13

### Other details

truyenqqvn.com → truyenqqviet.com

![IMG_20240610_210844](https://github.com/KotatsuApp/kotatsu-parsers/assets/74956696/b9968236-f327-4a61-8357-7263d89be5df)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
[#793](https://github.com/KotatsuApp/kotatsu-parsers/issues/793)
