### ISSUE TITLE
Astrum Scans

### ISSUE THREAD

**Issue by Carlota-gif** [KotatsuApp/kotatsu-parsers#838]
### Source name

Astrum Scans

### Source link

https://astrumscans.xyz/

### Language

Brazilian Portuguese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
See #39

**Comment by Carlota-gif** [comment]
> Veja #39

sorry, I had not seen
