### ISSUE TITLE
problem with demonsect font on my old android phone

### ISSUE THREAD

**Issue by Josue18js** [KotatsuApp/kotatsu-parsers#839]
### Source information

demonSect

### Steps to reproduce

After completing the captcha this happens:
![Screenshot_2024-06-16-22-31-27](https://github.com/KotatsuApp/kotatsu-parsers/assets/92787197/31dc6d66-7429-4458-9c91-aac43fadd5d9)
The smartphone where this happened has Android 6.0.1, I tested it on my smartphone with Android 13 and it worked normally

### Kotatsu version

7.2

### Android version

6.0.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
#744
