### ISSUE TITLE
Some series not present/available, although available in browser

### ISSUE THREAD

**Issue by Zehra** [KotatsuApp/kotatsu-parsers#84]
### Source information

MangaDex

### Steps to reproduce

1. Visit series which is affected by issue. (Seems mainly oneshots and fanworks are affected.)
2. Wait for it to error.
3. Error appears: `Value [] at description of type org.json.JSONARRAY cannot be converted to JSONObject`

### Kotatsu version

3.4.16

### Android version

Android 9

### Other details

"Love in the Next Life" is a oneshot which demonstrates this issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Oh, we fixed that https://github.com/KotatsuApp/kotatsu-parsers/commit/e8b801684fd45405bec20f44e1b31eebff3e5bf4
But we are forgot to release version 3.x with fixed MangaDex, in 4.0-rc1 MangaDex works normal

**Comment by Koitharu** [comment]
Also available in 3.4.17

**Comment by Zehra** [comment]
Thanks, much appreciated and keep up the good work.
