### ISSUE TITLE
[Source Request - Portuguese Brazil] Golden Mangás 

### ISSUE THREAD

**Issue by ROBSU18** [KotatsuApp/kotatsu-parsers#86]
### Source name

Golden Mangás

### Source link

https://goldenmangas.top

### Language

Portuguese - Brazil

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
already here : https://github.com/KotatsuApp/kotatsu-parsers/blob/400a90464e205195c01b173002dea1a5011e1f99/src/main/kotlin/org/koitharu/kotatsu/parsers/site/pt/GoldenManga.kt#L18
