### ISSUE TITLE
New Tsuki Mangás 

### ISSUE THREAD

**Issue by Maddigow** [KotatsuApp/kotatsu-parsers#860]
### Source name

Tsuki Mangás 

### Source link

https://tsuki-mangas.com/

### Language

Português Brasil 

### Other details

their old website was taken down, this is the new one  

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Duplicate of #320
