### ISSUE TITLE
Add manga source (manga.detectiveconanar)

### ISSUE THREAD

**Issue by Bdran4** [KotatsuApp/kotatsu-parsers#868]
### Source name

manga detective conan ar

### Source link

https://manga.detectiveconanar.com/

### Language

Arabic

### Other details

Plz add it in the next update

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Duplicate of [#619](https://github.com/KotatsuApp/kotatsu-parsers/issues/619)
