### ISSUE TITLE
[Source Request - Portuguese Brazil] Mangá Host

### ISSUE THREAD

**Issue by ROBSU18** [KotatsuApp/kotatsu-parsers#87]
### Source name

Mangá Host

### Source link

https://mangahosted.com

### Language

Portuguese - Brazil

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Source Dead
