### ISSUE TITLE
CeriseScans structure change

### ISSUE THREAD

**Issue by herowolfG** [KotatsuApp/kotatsu-parsers#872]
### Source information

CeriseScans

### Steps to reproduce

the site structure has changed.

![cer](https://github.com/KotatsuApp/kotatsu-parsers/assets/169401902/4293f99b-5fcc-4e77-a1c2-846372b47336)

Site on.

![Imagem do WhatsApp de 2024-06-29 à(s) 20 07 06_d5fe8572](https://github.com/KotatsuApp/kotatsu-parsers/assets/169401902/ed77290c-fe02-49a1-9ca0-c8261d5eb4e2)

### Kotatsu version

7.2.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
[#718](https://github.com/KotatsuApp/kotatsu-parsers/issues/718)
