### ISSUE TITLE
hardcore leveling warrior error 

### ISSUE THREAD

**Issue by DerBreak** [KotatsuApp/kotatsu-parsers#876]
### Source information

NineManga

### Steps to reproduce

1.open the ninemanga domain
2.open hardcore leveling warrior
3.content not found or removed but the website is normal

### Kotatsu version

7.2.1

### Android version

10

### Other details

![Screenshot_2024-07-03-16-38-57-84](https://github.com/KotatsuApp/kotatsu-parsers/assets/174595671/41cb9c9c-ab94-4920-ba9b-be5fcb6f6265)
![Screenshot_2024-07-03-16-38-15-25](https://github.com/KotatsuApp/kotatsu-parsers/assets/174595671/62b46382-3d97-4b4b-a13d-792580c6ca5b)
![Screenshot_2024-07-03-16-38-27-53](https://github.com/KotatsuApp/kotatsu-parsers/assets/174595671/e3ef238f-1b9f-455a-84fa-e4c5555a723e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
it comes from the source and not from the app
