### ISSUE TITLE
[Source Request - Portuguese Brazil] Muito Mangá

### ISSUE THREAD

**Issue by ROBSU18** [KotatsuApp/kotatsu-parsers#89]
### Source name

Muito Mangá

### Source link

https://muitomanga.com

### Language

Portuguese - Brazil

### Other details

Manga aggregator site

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Issues need to close because site closed
