### ISSUE TITLE
Mangaworld doesn't work

### ISSUE THREAD

**Issue by KTMQrow** [KotatsuApp/kotatsu-parsers#902]
### Source information

MangaWorld

### Steps to reproduce

All chapters of all mangas only show the 1st Page. 

![Screenshot_20240714-232817](https://github.com/user-attachments/assets/6398ecbb-ee91-4ca4-bd3b-c0caabb44f9f)

### Kotatsu version

7.3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
Fixed on #883 Wait a update
