### ISSUE TITLE
MangaPark wrong domain

### ISSUE THREAD

**Issue by Tyfaspo** [KotatsuApp/kotatsu-parsers#905]
### Source information

MangaPark

### Steps to reproduce

1. Open mangapark source
2. Web resource is unavailable

### Kotatsu version

7.3

### Android version

Android 14

### Other details

Manually changing domain to mangapark.io fixes the issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Inkesk** [comment]
For me both mangapark.net and mangapark.io domains seems functional and there are no issue in their update time as well of manga's , would it be possible to request screenrecord of the issue.

**Comment by Tyfaspo** [comment]
https://github.com/user-attachments/assets/ee7dff72-e4fd-42c1-a29b-9ad360c22d12

Probably an ISP issue, since it doesn't work in the browser as well, unless I'm using mobile data. Case closed?

**Comment by Inkesk** [comment]
Try clearing your cache files and share the results . 

For easily accessing and deletion of cache file follow the steps below :
1. Press 3 dots.
2. Go to setting then data and privacy.
3. Locate cache pages and cache network these are 5th and 4th bottommost respectively .
4. Click on them and they should be deleted.
