### ISSUE TITLE
Most Vietnamese sources are down

### ISSUE THREAD

**Issue by hailee0710** [KotatsuApp/kotatsu-parsers#906]
### Source information

Truyenqq, TruyentranhLH, NetTruyen, NhattruyenPlus

### Steps to reproduce

1. Have Truyenqq, TruyentranhLH, NetTruyen, NhattruyenPlus in your source.
2. Search for a title, i.e. "Kingdom".
3. Observe the result screen.
Note: Accessing the site using the Show all button show error page.

### Kotatsu version

7.3

### Android version

10, 14

### Other details

![image](https://github.com/user-attachments/assets/3dcf546c-632c-4688-a3b0-a025f676cf83)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Karutovn** [comment]
> ### Source information
> 
> Truyenqq, TruyentranhLH, NetTruyen, NhattruyenPlus
> 
> ### Steps to reproduce
> 
> 1. Have Truyenqq, TruyentranhLH, NetTruyen, NhattruyenPlus in your source.
> 2. Search for a title, i.e. "Kingdom".
> 3. Observe the result screen.
> Note: Accessing the site using the Show all button show error page.
> 
> ### Kotatsu version
> 
> 7.3
> 
> ### Android version
> 
> 10, 14
> 
> ### Other details
> 
> ![image](https://github.com/user-attachments/assets/3dcf546c-632c-4688-a3b0-a025f676cf83)
> 
> 
> ### Acknowledgements
> 
> - [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

Nhattruyen and nettruyen is dead but truyenqq domain is changed (you can see on tachiyomi extension)
Some source should be added

**Comment by dragonx943** [comment]
Pull Request: https://github.com/KotatsuApp/kotatsu-parsers/pull/935
