### ISSUE TITLE
New source request: my reading manga 

### ISSUE THREAD

**Issue by Yui003** [KotatsuApp/kotatsu-parsers#907]
### Source name

My Reading Manga

### Source link

https://myreadingmanga.info/

### Language

Various languages

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
Duplicate of #446
