### ISSUE TITLE
Change of link

### ISSUE THREAD

**Issue by Adhelaiide** [KotatsuApp/kotatsu-parsers#908]
### Source information

Epsilonscan 

### Kotatsu version

7.3

### Android version

Android 10

### Other details

epsilonscan source link changed to epsilonscan.to
The new link : https://epsilonscan.to/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
Already fixed, we'll have to wait for the next app update.
