### ISSUE TITLE
(Source request) Prisma Hentai

### ISSUE THREAD

**Issue by Orionv1** [KotatsuApp/kotatsu-parsers#91]
### Source name

PrismaHentai

### Source link

https://prismahentai.com/

### Language

Portuguese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by Koitharu** [comment]
There seems to be very little content on this site
