### ISSUE TITLE
Pixhentai

### ISSUE THREAD

**Issue by diecko69** [KotatsuApp/kotatsu-parsers#911]
### Source name

Pixhentai

### Source link

pixhentai.com

### Language

indonesia

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
https://github.com/KotatsuApp/kotatsu-parsers/blob/1f7fe2aed3f12c2e35d297960784650015d9fcb9/src/main/kotlin/org/koitharu/kotatsu/parsers/site/id/PixHentai.kt#L18
