### ISSUE TITLE
komiktap

### ISSUE THREAD

**Issue by diecko69** [KotatsuApp/kotatsu-parsers#917]
### Source information

Komiktap

### Kotatsu version

7.3

### Android version

android 13

### Other details

domain changed to komiktap.info

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
Already fix, wait for the next update
https://github.com/KotatsuApp/kotatsu-parsers/blob/35bdc15aa9bede84317e7cd42773cec0cbf48c2b/src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/id/KomikTapParser.kt#L10
