### ISSUE TITLE
Solicitação de nova fonte 

### ISSUE THREAD

**Issue by Ithalog1** [KotatsuApp/kotatsu-parsers#921]
### Source name

Hq now

### Source link

https://www.hq-now.com/

### Language

Português-Br

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
[#381](https://github.com/KotatsuApp/kotatsu-parsers/issues/381)
