### ISSUE TITLE
Komikcast change domain

### ISSUE THREAD

**Issue by diecko69** [KotatsuApp/kotatsu-parsers#922]
### Source information

Komikcast

### Kotatsu version

7.3

### Android version

Android 13

### Other details

please change the domain komikcast.lol to komikcast.cz

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
Fixed , Wait next update
https://github.com/KotatsuApp/kotatsu-parsers/blob/cd9f65596b51025c6cea6d7a8291fb1aa0cd1dd8/src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/id/Komikcast.kt#L14
