### ISSUE TITLE
Mangaworld Bug only One Page for chapter, loop

### ISSUE THREAD

**Issue by Yoshinizar** [KotatsuApp/kotatsu-parsers#923]
### Source information

Mangaworld

### Steps to reproduce

Please anyone can fix Mangaworld, (italian manga extension) because have a infinite loop and i can not see manga, i try One piece and my Hero accademia, all chapter have only One page

https://github.com/user-attachments/assets/ada969ec-f96f-418e-895e-7f028ffa686a

https://github.com/user-attachments/assets/f6e7fc86-3a1d-4d01-9eb8-f25bb0edce0b

### Kotatsu version

7.3

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
Fixed on #883 Wait a update

**Comment by Yoshinizar** [comment]
> Fixed on #883 Wait a update

Wow very fast, thank you, Top 💪

**Comment by Yoshinizar** [comment]
> Fixed on #883 Wait a update

Sorry but not only One piece, manu manu other manga have this problemi in Mangaworld, this Is a screen

and others, so there is a bigger problem than the single manga

![Screenshot_2024-07-21-12-25-34-94_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/user-attachments/assets/27f474b5-5f8e-4c56-9195-c0f2551f63c6)
![Screenshot_2024-07-21-12-24-09-37_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/user-attachments/assets/28c9404b-1331-4c1b-afc1-50f726dac902)
![Screenshot_2024-07-21-12-23-57-27_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/user-attachments/assets/0520b637-7dda-4055-b82b-6fbb9c3b49e5)
![Screenshot_2024-07-21-12-24-26-35_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/user-attachments/assets/60db6767-cca5-4ae7-b6d1-f8464115fca5)
![Screenshot_2024-07-21-12-25-06-29_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/user-attachments/assets/1de41099-dd01-4162-8061-a5be847506b5)
![Screenshot_2024-07-21-12-25-22-02_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/user-attachments/assets/9098515f-baec-42e2-b170-5bfc2433d23d)
![Screenshot_2024-07-21-12-24-00-55_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/user-attachments/assets/2ba0b1aa-f516-45d8-b526-7715910656b6)
