### ISSUE TITLE
Luminous scans domain

### ISSUE THREAD

**Issue by Inkesk** [KotatsuApp/kotatsu-parsers#926]
### Source information

Luminous-scans.com

### Steps to reproduce

1. Open luminous scans
2. Nothing found 
3. Enter the domain i.em luminous-scans.com (changed from lumitoon.com)
4. Works properly

### Kotatsu version

7.3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
already changed, just wait for a new app update
