### ISSUE TITLE
Asura scans website restructure 

### ISSUE THREAD

**Issue by Twan04** [KotatsuApp/kotatsu-parsers#929]
### Source information

Asura scans

### Kotatsu version

Version 7.3

### Other details

Asurascams recently restructured their website (asuracomic.net) and it is now displaying nothing found in kotatsu

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ASHWAN69** [comment]
Asura scans still not working

**Comment by davvarrr** [comment]
Wait the next update app.

**Comment by ASHWAN69** [comment]
> Wait the next update app.

When will the update come

**Comment by mickbou25** [comment]
When can we expect the next update to be available ?
