### ISSUE TITLE
Please add mangatoon website source

### ISSUE THREAD

**Issue by AzahCain** [KotatsuApp/kotatsu-parsers#931]
### Source name

Mangatoon

### Source link

https://mangatoon.mobi

### Language

Bahasa Indonesia

### Other details

Please add mangatoon website source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
[#471](https://github.com/KotatsuApp/kotatsu-parsers/issues/471)
