### ISSUE TITLE
Asura scans not working 

### ISSUE THREAD

**Issue by ASHWAN69** [KotatsuApp/kotatsu-parsers#933]
### Source information

Asura scans 

### Steps to reproduce

![Screenshot_2024-07-24-13-52-03-38_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/user-attachments/assets/5dc62b3f-3269-4884-b533-ca23ccf51c6b)
When i open the source it show nothing found and I can't use it 

### Kotatsu version

7.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
#929
