### ISSUE TITLE
Asurascans not working 

### ISSUE THREAD

**Issue by ASHWAN69** [KotatsuApp/kotatsu-parsers#934]
### Source information

Asurascans 

### Steps to reproduce

![Screenshot_2024-07-24-21-09-29-88_572064f74bd5f9fa804b05334aa4f912](https://github.com/user-attachments/assets/41d85325-a3d3-4b97-bcb2-44fa2f396f8a)
Can you do what he said 

### Kotatsu version

7.3

### Android version

Android 14

### Other details

Tried everything still not working 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
#929
