### ISSUE TITLE
Asura scans changed their link structure

### ISSUE THREAD

**Issue by rusu-adrian** [KotatsuApp/kotatsu-parsers#937]
### Source information

AsuraScans

### Kotatsu version

7.3

### Android version

14, 13, any

### Other details

Asura scans recently changed their link structure and I think this is the cause of making the extension unfunctional. Below you can see an example of a new and old link.

New link:
https://asuracomic.net/series/martial-god-regressed-to-level-2-d75ad672

Old link:
https://asuracomic.net/manga/1908287720-insanely-talented-player/

You can see that they differ. Hope this helps.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
#929
