### ISSUE TITLE
New source grimelek

### ISSUE THREAD

**Issue by Mamisyi** [KotatsuApp/kotatsu-parsers#942]
### Source name

Grimelek

### Source link

Grimelek.com

### Language

Turkish

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
https://github.com/KotatsuApp/kotatsu-parsers/blob/7bcc624a74511914ac0750fa0b30a9bac81b2639/src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/tr/Grimelek.kt#L9
