### ISSUE TITLE
domain change

### ISSUE THREAD

**Issue by diecko69** [KotatsuApp/kotatsu-parsers#946]
### Source information

Doujindesu.cfd

### Kotatsu version

7.3

### Android version

Android 13

### Other details

change domain doujindesu.cfd to doujindesu.mobi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by dragonx943** [comment]
> ### Source information
> Doujindesu.cfd
> 
> ### Steps to reproduce
> _No response_
> 
> ### Kotatsu version
> 7.3
> 
> ### Android version
> Android 13
> 
> ### Other details
> change domain doujindesu.cfd to doujindesu.mobi
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

still good (without change domain), pls check your network connection.
![Screenshot_20240727-011941_Kotatsu](https://github.com/user-attachments/assets/7ca07329-824a-43db-85b1-223005f56895)

**Comment by davvarrr** [comment]
Already changed  
https://github.com/KotatsuApp/kotatsu-parsers/blob/53ca9c9677af59bb841310977a9011826454ab8c/src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/id/DoujinDesuRip.kt#L11
