### ISSUE TITLE
doujinku domain

### ISSUE THREAD

**Issue by diecko69** [KotatsuApp/kotatsu-parsers#947]
### Source information

Doujinku

### Kotatsu version

7.3

### Android version

Android 13

### Other details

change domain doujinku.xyz to doujinku.org

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
Already changed 
   https://github.com/KotatsuApp/kotatsu-parsers/blob/53ca9c9677af59bb841310977a9011826454ab8c/src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangareader/id/DoujinKu.kt#L12
