### ISSUE TITLE
Issue with AsuraScans source (asuracomic.net, asurascans.com)

### ISSUE THREAD

**Issue by quillasp** [KotatsuApp/kotatsu-parsers#949]
### Source information

AsuraScans

### Steps to reproduce

Hello,

Thank you for this app!

It seems that since an update on the backend (I believe they changed their provider and domain from asuratoon.com to asuracomic.net), the manhwa chapters are no longer loading.

I have already tried changing the source domain setting, but it still doesn't work. I'm not sure what changes were made on their backend.

Thank you for your time and help.

Best regards,
quillasp

### Kotatsu version

7.3

### Android version

Android 14

### Other details

I don't know if you are already working on it, sorry for the occasional redundancy. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
#929
