### ISSUE TITLE
manhwaku

### ISSUE THREAD

**Issue by diecko69** [KotatsuApp/kotatsu-parsers#956]
### Source name

manhwaku

### Source link

manhwaku.id

### Language

indonesia

### Other details

site for reading manhua and manhwa

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
add in https://github.com/KotatsuApp/kotatsu-parsers/commit/50194df24df27303d77cc48537fdf2b076a5296d
