### ISSUE TITLE
Asurascans not working even after the new update 

### ISSUE THREAD

**Issue by Shadow573** [KotatsuApp/kotatsu-parsers#960]
### Source information

Asurascans

### Steps to reproduce

Changed the domains as suggested in the discord but it was not the official scans and the website is already back and running but the source in kotatsu still not working.
![Screenshot_20240730_155835_Kotatsu](https://github.com/user-attachments/assets/f3ebea87-a843-4255-a21a-753240d12182)
![Screenshot_20240730_155830_Kotatsu](https://github.com/user-attachments/assets/b5146a02-9ceb-46aa-a6af-4c515f0eb41a)

### Kotatsu version

7.4

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
Make sure you have the url “asuracomic.net” because it is possible that you have left a wrong domain name (to be sure to delete what you have added to return to the default url).
