### ISSUE TITLE
doujindesu

### ISSUE THREAD

**Issue by kenewjr** [KotatsuApp/kotatsu-parsers#963]
### Source information

doujindesu.tv

### Steps to reproduce

1.open tab explore
2.choose manga sources doujindesu.tv
3.got a few update manga
4.scroll down to get more manga but got error "Cannot get relative url for href: "

### Kotatsu version

7.4

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
there are 3 doujindesu and all 3 work, you need more info, the exact source the name of the manga

**Comment by kenewjr** [comment]
edited, my bad
