### ISSUE TITLE
ExH*nt*i Code

### ISSUE THREAD

**Issue by memereb** [KotatsuApp/kotatsu-parsers#964]
### Source information

ExHentai

### Steps to reproduce

I don't really know if it's only on mine but here's how i did it:
1. Go to "Explore"
2. Visit's source "Exhentai"
3. Got "kotlin.Unit cannot be cast to java.lang.Void."

### Kotatsu version

Any

### Android version

Any

### Other details

The problem is whenever i try to read any manga in this source, it says "kotlin.Unit cannot be cast to java.lang.Void." When i open the site in browser, it's fine but in Kotatsu it doesn't let me read. Maybe,bit's a language-type problem??? Coding?? I don't really know. Hope you can help me with that problem if there's a way to fix it. 

![Screenshot_20240731_110602](https://github.com/user-attachments/assets/beedcc7b-4ce3-4b47-876f-8b202677c6a7)
![Screenshot_20240801_114957](https://github.com/user-attachments/assets/aa682e42-5680-4815-aa73-2dea8b373359)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
fix in https://github.com/KotatsuApp/kotatsu-parsers/commit/853c21e49f1ad6131727d5489485cd749fe51547
