### ISSUE TITLE
Source works fine but chapters are missing 

### ISSUE THREAD

**Issue by Shadow573** [KotatsuApp/kotatsu-parsers#976]
### Source information

Asurascans

### Steps to reproduce

When opened the source works fine and able to view different manhwa but when opening a chapter, content not found or removed is mentioned.
![Screenshot_20240805_144118_Kotatsu](https://github.com/user-attachments/assets/489194b9-b2e1-4ec0-8a92-66b99b596bc2)

### Kotatsu version

7.4.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Shadow573** [comment]
Issue has been addressed by discord.

**Comment by IndraTensei** [comment]
Found the problem?

**Comment by MaDMax708** [comment]
Did it get solved

**Comment by Shadow573** [comment]
No sadly, it was mentioned in the discord but reaper scans also not working
same way.
