### ISSUE TITLE
asuracomic.net  is not working properly.

### ISSUE THREAD

**Issue by utkarshbansod** [KotatsuApp/kotatsu-parsers#981]
### Source information

asuracomic.net

### Steps to reproduce

asuracomic.net  is not working properly. when I try to open my manga/manwha it just show "This Chapter is Missing" please try and fix this problem as soon as possible.

### Kotatsu version

7.4.1

### Android version

Android 11

### Other details

![Screenshot_2024-08-06-22-43-15-91_a5af3585a93e2016f6667aaf7e1e2f32](https://github.com/user-attachments/assets/d72a4945-328d-450b-bcf2-102a42dc427a)

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
Fix in https://github.com/KotatsuApp/kotatsu-parsers/commit/71affd155ca51b3b396e3130a907b5f04cefc359
