### ISSUE TITLE
Asurascans shows content not found or removed

### ISSUE THREAD

**Issue by Elto-bite** [KotatsuApp/kotatsu-parsers#984]
### Source information

AsuraScans

### Steps to reproduce

1. Open asurascans
2. Click on any manhwa and press read
![Screenshot_20240806_222420_Kotatsu](https://github.com/userattachments/assets/3fcaf995-ca89-44a1-98b9-b13bb972d72b)

### Kotatsu version

7.4.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by mickbou25** [comment]
Most if not all of the manhwas on asura scans have this issue...

**Comment by davvarrr** [comment]
https://github.com/KotatsuApp/kotatsu-parsers/issues/960 Please look for the answer before asking.

**Comment by mickbou25** [comment]
When can we expect the update to be available ?
