### ISSUE TITLE
Various sources not working properly 

### ISSUE THREAD

**Issue by ClnSrt** [KotatsuApp/kotatsu-parsers#989]
### Source information

ReaperComics AsuraComics 

### Steps to reproduce

1. Open one of the two source
2. Open any manhwa/manga
![Screenshot_2024-08-08-08-56-39-341_org koitharu kotatsu](https://github.com/user-attachments/assets/6013df48-332d-4ac8-80ee-f2df522cc8df)

### Kotatsu version

7.4.1

### Android version

13

### Other details

Note that it's not an issue on the unofficial version like the french version of reaper scan or AsuraScansGg and AsuraScan.us

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment]
https://github.com/KotatsuApp/kotatsu-parsers/issues/966 , https://github.com/KotatsuApp/kotatsu-parsers/issues/960 Please look for the answer before asking.
