### ISSUE TITLE
Comicextra not working

### ISSUE THREAD

**Issue by LuffySolos24** [KotatsuApp/kotatsu-parsers#991]
### Source information

Comicextra

### Steps to reproduce

I opened a comic I had already downloaded from comicextra today but no comic was found, I checked for other comics from comicextra and faced same problem.

### Kotatsu version

7.4.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Rubic13** [comment]
I have the same issue. Other sources work fine and the comic extra website is still up.

**Comment by dragonx943** [comment]
Fixed https://github.com/KotatsuApp/kotatsu-parsers/pull/1294
