### ISSUE TITLE
Source Request

### ISSUE THREAD

**Issue by egayghost** [KotatsuApp/kotatsu-parsers#993]
### Source name

CoffeeManga

### Source link

https://coffeemanga.io/

### Language

English

### Other details

I also noticed that this website is fast and still currently being updated, and some chapters are cut from bato.to and this website has the missing parts.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have checked that the source does not already exist on the app.
- [X] I have checked that the source does not already exist by searching the [GitHub repository](https://github.com/KotatsuApp/kotatsu-parsers) and verified it does not appear in the code base.

**Comment by davvarrr** [comment]
https://github.com/KotatsuApp/kotatsu-parsers/blob/71affd155ca51b3b396e3130a907b5f04cefc359/src/main/kotlin/org/koitharu/kotatsu/parsers/site/madara/en/CoffeeManga.kt#L10
